#!/usr/bin/env python3
"""
TWIST-BDG-46: Twisted BdG Spectral Triple on SU(3)
====================================================

Gate: TWIST-BDG-46
  PASS: KO-dimension preserved AND Krein signature matches (3,1) per family
  FAIL: Axioms violated

Construct the twisted BdG spectral triple (A_F, H_BdG, D_BdG, J_BdG, gamma_BdG)
and verify the NCG axioms.  The twist is generated by the BCS order parameter Delta.

Mathematical framework (Papers 30, 33, 44):
  - A twisted spectral triple (A, H, D, sigma) replaces the first-order condition
    [[D,a], b^o] = 0 with the sigma-twisted condition [[D,a], sigma(b)^o] = 0.
  - The twist automorphism sigma: A -> A induces a Krein fundamental symmetry
    eta on H when sigma^2 != 1.
  - For the BdG doubling: H_BdG = H + H* (Nambu-Gorkov), and the BCS gap Delta
    provides a natural twist generator.

Key distinction (Connes NCG theorist note):
  The twist in Papers 30/33/44 is an automorphism of the ALGEBRA A, not a
  conjugation of D.  We implement both constructions and identify the obstruction.

Provenance:
  - s44_n3_bdg.npz: BdG eigenvalues, gaps, single-particle energies
  - s39_bdg_simulation.npz: u_k, v_k Bogoliubov coefficients
  - s45_occ_spectral.npz: eigenvalues, BCS occupations, Delta vs tau
  - s45_weak_order_one.npz: algebra structure, order-one data
  - canonical_constants.py: tau_fold, Delta_0_GL, E_cond

Session: 46, Wave 3, Task W3-2
Agent: connes-ncg-theorist
"""

import numpy as np
from scipy import linalg as la
import sys
import os
import time

sys.path.insert(0, os.path.join(os.path.dirname(__file__)))
from canonical_constants import (
    tau_fold, Delta_0_GL, E_cond, Delta_0_OES,
    E_B1, E_B2_mean, E_B3_mean
)

t_start = time.time()

# =============================================================================
# 1. LOAD DATA
# =============================================================================

d_bdg = np.load('tier0-computation/s44_n3_bdg.npz', allow_pickle=True)
d_sim = np.load('tier0-computation/s39_bdg_simulation.npz', allow_pickle=True)
d_occ = np.load('tier0-computation/s45_occ_spectral.npz', allow_pickle=True)

# BdG data from S44
E_BdG_fold = d_bdg['E_BdG_fold']      # 16 BdG eigenvalues
xi_all = d_bdg['xi_all']              # 8 single-particle energies
Delta_all = d_bdg['Delta_all']        # 8 gap values

# Bogoliubov coefficients from S39
u0 = d_sim['u0']                      # 8 u_k values
v0 = d_sim['v0']                      # 8 v_k values

# Delta profile
Delta_tau = d_occ['Delta_vs_tau']
Delta_fold = Delta_tau[11]  # tau=0.190

print(f"Delta at fold (tau={tau_fold}): {Delta_fold:.6f} M_KK")
print(f"u^2+v^2 check: {np.max(np.abs(u0**2 + v0**2 - 1)):.2e}")

# =============================================================================
# 2. CONSTRUCT THE 8-MODE BdG SPECTRAL TRIPLE (BLOCK-DIAGONAL)
# =============================================================================

N_modes = 8
N_BdG = 2 * N_modes  # = 16

epsilon = xi_all.copy()       # 8 single-particle energies
Delta_diag = Delta_all.copy()  # 8 gap values (5 non-zero, 3 zero)

# BdG Dirac operator: block-diagonal with 2x2 blocks per mode
# h_k = | eps_k    Delta_k |
#        | Delta_k* -eps_k  |
D_BdG = np.zeros((N_BdG, N_BdG))
for k in range(N_modes):
    i = 2 * k
    D_BdG[i, i] = epsilon[k]
    D_BdG[i, i + 1] = Delta_diag[k]
    D_BdG[i + 1, i] = np.conj(Delta_diag[k])
    D_BdG[i + 1, i + 1] = -epsilon[k]

sa_err = np.max(np.abs(D_BdG - D_BdG.conj().T))
print(f"\nD_BdG self-adjoint error: {sa_err:.2e}")
assert sa_err < 1e-14

E_BdG_computed = la.eigvalsh(D_BdG)
print(f"D_BdG eigenvalues: {E_BdG_computed}")
print(f"S44 reference:     {E_BdG_fold}")

E_diff = np.max(np.abs(np.sort(E_BdG_computed) - np.sort(E_BdG_fold)))
print(f"Eigenvalue match to S44: {E_diff:.2e}")

# PH symmetry check: eigenvalues in +/- pairs
E_sorted = np.sort(E_BdG_computed)
ph_err = np.max(np.abs(E_sorted[:N_modes] + E_sorted[N_modes:][::-1]))
print(f"PH symmetry (E + E_mirror): {ph_err:.2e}")

# =============================================================================
# 3. PARTICLE-HOLE OPERATOR C (BdG PH symmetry)
# =============================================================================
# Standard BdG PH: C = i*sigma_y per block, composed with complex conjugation K
# sigma_y h_k sigma_y = -h_k for real h_k (verified analytically)
# C^2 = -I (class D PH symmetry)

C_ph = np.zeros((N_BdG, N_BdG))
for k in range(N_modes):
    i = 2 * k
    # i*sigma_y = |0, 1; -1, 0|
    C_ph[i, i + 1] = 1.0
    C_ph[i + 1, i] = -1.0

# Verify C D C^{-1} = -D
C_inv = la.inv(C_ph)
CDC = C_ph @ D_BdG @ C_inv
ph_anti_err = np.max(np.abs(CDC + D_BdG))
print(f"\nC D C^{{-1}} + D error: {ph_anti_err:.2e}")

# C^2
C_sq = C_ph @ C_ph.conj()  # C^2 = C_matrix * conj(C_matrix) for C = C_ph * K
C_sq_plus_I = np.max(np.abs(C_sq + np.eye(N_BdG)))
print(f"C^2 + I error: {C_sq_plus_I:.2e} (C^2 = -I -> AZ class D)")

# =============================================================================
# 4. REAL STRUCTURE J_BdG AND GRADING gamma_BdG
# =============================================================================

# ---- Real structure ----
# In the NCG formalism, J is the REAL STRUCTURE (charge conjugation), distinct
# from the BdG PH operator C.
#
# S35 BdG workshop (PERMANENT result): For the FULL spinor bundle on SU(3),
# J_BdG = (0, C2; C2, 0) * K with C2 = gamma_1*gamma_3*gamma_5*gamma_7.
# This gives (eps, eps', eps'') = (+1, +1, -1) -> KO-dim 6 PRESERVED.
#
# In the 8-mode BCS truncation, we do NOT have the full Clifford algebra.
# The mode space is an abstract 8-dimensional vector space without the
# gamma matrix structure.  We analyze two candidates for J:
#
# Candidate 1: J = sigma_x per block (swap particle/hole) * K
# Candidate 2: J = identity * K (trivial charge conjugation in mode space)
#
# We use Candidate 1 (sigma_x swap) which is the physical particle-hole swap.

J_matrix = np.zeros((N_BdG, N_BdG))
for k in range(N_modes):
    i = 2 * k
    J_matrix[i, i + 1] = 1.0
    J_matrix[i + 1, i] = 1.0

# J^2 = J_matrix * J_matrix^* = J_matrix^2 (real matrix)
J_sq = J_matrix @ J_matrix
J_sq_err = np.max(np.abs(J_sq - np.eye(N_BdG)))
eps_J = +1
print(f"\nJ^2 = +I error: {J_sq_err:.2e} -> eps = +1")

# J D J^{-1} (for real J and D):
# J_matrix @ D_BdG @ J_matrix (J is its own inverse)
JDJ = J_matrix @ D_BdG @ J_matrix

# For each 2x2 block: sigma_x (eps, Delta; Delta*, -eps) sigma_x
# = (-eps, Delta*; Delta, eps)
# Compare with D = (eps, Delta; Delta*, -eps):
# JDJ[i,i] = -eps != eps, JDJ[i,i+1] = Delta* = Delta (real) = Delta
# So JDJ != +D and JDJ != -D unless Delta = 0 and eps = 0.
# Let's compute:
comm_JD = np.max(np.abs(JDJ - D_BdG))
anti_JD = np.max(np.abs(JDJ + D_BdG))

print(f"JDJ - D error: {comm_JD:.4f}")
print(f"JDJ + D error: {anti_JD:.4f}")

# Neither! J (sigma_x swap) neither commutes nor anticommutes with D_BdG.
# Decompose: JDJ = -D + 2*Delta_part
# where Delta_part has Delta on the diagonal and eps on the off-diagonal.
# This is the mixed structure of BdG.

# For the PH operator C (i*sigma_y):
# sigma_y (eps, Delta; Delta, -eps) sigma_y = (-eps, -Delta; -Delta, eps) = -D. CHECK.
# So C anticommutes with D: eps'_C = -1.

# For sigma_x swap (our J):
# sigma_x (eps, Delta; Delta, -eps) sigma_x = (-eps, Delta; Delta, eps)
# This equals -D + 2*diag(0, Delta; Delta, 0)... no, let me write it:
# JDJ block k: | -eps_k  Delta_k |    vs    D_k: | eps_k   Delta_k |
#               | Delta_k  eps_k  |               | Delta_k -eps_k  |
# Difference: JDJ - D = |-2eps_k  0     |
#                        | 0      2eps_k |
# So JDJ = D - 2*eps_k*tau_3 per block. NOT a simple sign relation.

# With the standard BdG PH sigma_y, eps'=-1.
# With the particle-hole SWAP sigma_x: neither commutes nor anticommutes.
# The S35 resolution: J contains the INTERNAL charge conjugation C2 from the
# Clifford algebra, NOT just a Nambu-space operation.

# For the gate assessment: we CANNOT determine eps' in the 8-mode truncation
# without the Clifford algebra. We defer to the S35 full-spinor result.

# Determine eps' from the PH operator C (the only well-defined symmetry operator):
eps_prime_C = -1  # C D C^{-1} = -D (verified above)

# ---- Grading ----
gamma_BdG = np.zeros((N_BdG, N_BdG))
for k in range(N_modes):
    i = 2 * k
    gamma_BdG[i, i] = 1.0       # particle: +1
    gamma_BdG[i + 1, i + 1] = -1.0  # hole: -1

gamma_sq_err = np.max(np.abs(gamma_BdG @ gamma_BdG - np.eye(N_BdG)))
print(f"\ngamma^2 = I error: {gamma_sq_err:.2e}")

# {gamma, D} anticommutation
gamma_D_anti = gamma_BdG @ D_BdG + D_BdG @ gamma_BdG
gamma_D_err = np.max(np.abs(gamma_D_anti))
print(f"{{gamma, D}} error: {gamma_D_err:.4f}")
if gamma_D_err < 1e-10:
    print("  gamma anticommutes with D -> orientability PASS")
    orientability = True
else:
    # {gamma, D} per block: tau_3 h_k + h_k tau_3
    # = (eps, Delta; -Delta, -eps) + (eps, -Delta; Delta, -eps)
    # = (2eps, 0; 0, -2eps) -> non-zero iff eps != 0
    # So {gamma_BdG, D_BdG} = 2*diag(eps_k, -eps_k) != 0 for eps_k != 0
    # The anticommutator norm is 2*max(|eps_k|) = 2*max(xi_all)
    expected_norm = 2 * np.max(np.abs(epsilon))
    print(f"  {{gamma, D}} = 2*eps (not zero due to diagonal part)")
    print(f"  Expected norm: {expected_norm:.4f}, actual: {gamma_D_err:.4f}")
    orientability = False

# J gamma relation:
# J_matrix gamma_BdG J_matrix per block: sigma_x tau_3 sigma_x = -tau_3
J_gamma_J = J_matrix @ gamma_BdG @ J_matrix
Jg_err = np.max(np.abs(J_gamma_J + gamma_BdG))  # should be zero if anticommutes
Jg_comm_err = np.max(np.abs(J_gamma_J - gamma_BdG))
print(f"\nJ gamma J + gamma error: {Jg_err:.2e}")
print(f"J gamma J - gamma error: {Jg_comm_err:.2e}")

if Jg_err < 1e-10:
    eps_double_prime = -1
    print(f"J gamma = -gamma J -> eps'' = -1")
elif Jg_comm_err < 1e-10:
    eps_double_prime = +1
    print(f"J gamma = +gamma J -> eps'' = +1")
else:
    eps_double_prime = 0
    print(f"J gamma neither commutes nor anticommutes with gamma")

# =============================================================================
# 5. KO-DIMENSION SUMMARY
# =============================================================================

print("\n" + "=" * 60)
print("KO-DIMENSION ANALYSIS")
print("=" * 60)

# KO-dim table for even dimensions with all three signs:
KO_table = {
    (+1, +1, +1): 0,
    (-1, +1, +1): 2,
    (-1, +1, -1): 4,
    (+1, +1, -1): 6,
}

# From 8-mode truncation:
print(f"  eps (J^2=+1):        {eps_J:+d}")
print(f"  eps' from C (anticomm): {eps_prime_C:+d} (BdG PH, NOT J)")
print(f"  eps'' (J*gamma):     {eps_double_prime:+d}")
print()

# The 8-mode truncation gives:
#   eps = +1 (J_swap), eps'_C = -1 (BdG PH), eps'' = -1 (J gamma anticommute)
# This would be (+1, -1, -1) which does not correspond to any even KO-dim.
# It corresponds to KO-dim 1 (odd).
#
# The resolution (from S35 workshop):
# In the FULL spectral triple on SU(3), the real structure J includes C2
# (product of real gamma matrices in the 8D Clifford algebra).
# The S35 result: (eps, eps', eps'') = (+1, +1, -1) -> KO-dim 6 PRESERVED.
# This was verified to machine epsilon in the full spinor bundle.
#
# The 8-mode BCS truncation loses the Clifford algebra structure,
# so we cannot independently verify KO-dim 6 here.
# We cite the S35 result as authoritative.

print("FULL SPINOR BUNDLE (S35 workshop, PERMANENT):")
print(f"  (eps, eps', eps'') = (+1, +1, -1) -> KO-dim 6")
print(f"  Verified to machine epsilon on the full spinor BdG triple.")
print()
print("8-MODE TRUNCATION (this computation):")
print(f"  Mode space lacks Clifford algebra.")
print(f"  PH operator C gives eps'_C = -1 (distinct from NCG real structure J).")
print(f"  eps'' = -1 confirmed (sigma_x tau_3 sigma_x = -tau_3).")
print(f"  KO-dim cannot be independently determined from mode space alone.")

# =============================================================================
# 6. TWIST CONSTRUCTION: THREE APPROACHES
# =============================================================================

print("\n" + "=" * 60)
print("TWIST CONSTRUCTION")
print("=" * 60)

# ---- Approach 1: Grading twist sigma = Ad(gamma_BdG) ----
print("\n--- Approach 1: Grading twist sigma(a) = gamma a gamma ---")
# A_F acts on H_BdG via a_BdG = diag(a, a) in Nambu space.
# sigma_1(a) = gamma * diag(a, a) * gamma = diag(a, a) = a
# because gamma = tau_3 is diagonal and diag(a,a) is block-diagonal.
# RESULT: trivial. The grading commutes with the diagonal algebra embedding.
print("  sigma_1 = Ad(tau_3) acts on diag(a,a) trivially.")
print("  TRIVIAL: no non-trivial twist from Nambu grading alone.")

# ---- Approach 2: Prompt construction rho = exp(i*pi*Delta_hat/Delta_max) ----
print("\n--- Approach 2: rho-conjugation D_rho = rho D rho^{-1} ---")

Delta_max = np.max(np.abs(Delta_diag))
if Delta_max < 1e-15:
    Delta_max = 1.0

# Gap operator normalized
Delta_op = np.zeros((N_BdG, N_BdG))
for k in range(N_modes):
    i = 2 * k
    d = Delta_diag[k] / Delta_max
    Delta_op[i, i + 1] = d
    Delta_op[i + 1, i] = np.conj(d)

rho = la.expm(1j * np.pi * Delta_op)
rho_inv = la.expm(-1j * np.pi * Delta_op)
rho_unit_err = np.max(np.abs(rho @ rho.conj().T - np.eye(N_BdG)))
print(f"  rho unitarity error: {rho_unit_err:.2e}")

# D_rho = rho D rho^{-1}
D_rho = rho @ D_BdG @ rho_inv
D_rho_herm = 0.5 * (D_rho + D_rho.conj().T)
E_rho = la.eigvalsh(D_rho_herm)

spec_change = np.max(np.abs(np.sort(np.real(E_rho)) - np.sort(E_BdG_computed)))
print(f"  Spectrum change under rho-twist: {spec_change:.2e}")
print(f"  (Expected: 0 — unitary conjugation preserves spectrum)")

# Krein structure from rho^2
eta_rho2 = rho @ rho
eta_rho2_herm = 0.5 * (eta_rho2 + eta_rho2.conj().T)
eta_rho2_evals = la.eigvalsh(eta_rho2_herm)
eta_sq_test = eta_rho2 @ eta_rho2
eta_invol_err = np.max(np.abs(eta_sq_test - np.eye(N_BdG)))
print(f"\n  eta = rho^2 eigenvalues: {np.sort(np.real(eta_rho2_evals))}")
print(f"  eta^2 = I error: {eta_invol_err:.2e}")

if eta_invol_err > 0.01:
    print(f"  eta^2 != I: rho^2 is NOT a fundamental symmetry.")
    print(f"  Paper 44 Theorem 3.2 requires eta^2=1 for Krein structure.")
    print(f"  -> rho-twist does NOT produce a valid Krein fundamental symmetry.")
    rho_krein_valid = False
else:
    rho_krein_valid = True
    n_pos_rho = np.sum(eta_rho2_evals > 0.5)
    n_neg_rho = np.sum(eta_rho2_evals < -0.5)
    print(f"  Krein signature from rho^2: ({n_pos_rho}, {n_neg_rho})")

# ---- Approach 3: Bogoliubov transformation as Hilbert space twist ----
print("\n--- Approach 3: Bogoliubov transformation U_BCS ---")

U_bcs = np.zeros((N_BdG, N_BdG))
for k in range(N_modes):
    i = 2 * k
    U_bcs[i, i] = u0[k]
    U_bcs[i, i + 1] = v0[k]
    U_bcs[i + 1, i] = -v0[k]
    U_bcs[i + 1, i + 1] = u0[k]

U_unit_err = np.max(np.abs(U_bcs @ U_bcs.T - np.eye(N_BdG)))
print(f"  U_BCS unitarity error: {U_unit_err:.2e}")

# U_BCS^2 (involutive?)
U_sq = U_bcs @ U_bcs
U_invol_err = np.max(np.abs(U_sq - np.eye(N_BdG)))
print(f"  U_BCS^2 = I error: {U_invol_err:.4f} (NOT involutive)")

# Action on D:
D_bogo = U_bcs @ D_BdG @ U_bcs.T
E_bogo = la.eigvalsh(D_bogo)
spec_bogo = np.max(np.abs(np.sort(E_bogo) - np.sort(E_BdG_computed)))
print(f"  Spectrum change: {spec_bogo:.2e} (preserved by unitarity)")

# Action on algebra: sigma(a) = U a U^T for a = diag(a, a)
# For diagonal a in Nambu space and block-diagonal U:
#   block k: (u, v; -v, u) (a, 0; 0, a) (u, -v; v, u) = (a, 0; 0, a) = a
# TRIVIAL: U_BCS commutes with diagonal algebra embedding.
print(f"  sigma(a) = U_BCS * diag(a,a) * U_BCS^T = diag(a,a)")
print(f"  TRIVIAL: BCS transformation commutes with A_F embedding.")
print(f"  -> BCS is a HILBERT SPACE transformation, not an ALGEBRA automorphism.")

# ---- Approach 4: Natural Nambu Krein structure ----
print("\n--- Approach 4: Natural BdG Krein structure eta = tau_3 ---")

eta_nambu = gamma_BdG.copy()  # tau_3 in block form
n_pos_nambu = N_modes   # 8 particle modes
n_neg_nambu = N_modes   # 8 hole modes
print(f"  eta = tau_3 (Nambu grading)")
print(f"  eta^2 = I: verified (trivially)")
print(f"  Krein signature: ({n_pos_nambu}, {n_neg_nambu})")

# Krein self-adjointness of D:
# D^# = eta D^dag eta = tau_3 D tau_3 (for Hermitian D)
D_krein_adj = eta_nambu @ D_BdG @ eta_nambu
krein_sa_err = np.max(np.abs(D_krein_adj - D_BdG))
krein_anti_err = np.max(np.abs(D_krein_adj + D_BdG))
print(f"  D^# = D error (Krein self-adjoint): {krein_sa_err:.4f}")
print(f"  D^# = -D error (Krein anti-self-adjoint): {krein_anti_err:.4f}")

# Per block: tau_3 (eps, Delta; Delta, -eps) tau_3 = (eps, -Delta; -Delta, -eps)
# This is NOT D (which has +Delta off-diagonal) and NOT -D.
# D^# = D - 2*Delta_off_diag
# So D is NOT Krein-self-adjoint.
print(f"  D_BdG is NOT Krein-self-adjoint w.r.t. eta=tau_3.")
print(f"  The off-diagonal Delta breaks Krein self-adjointness.")

# =============================================================================
# 7. THE FUNDAMENTAL OBSTRUCTION
# =============================================================================

print("\n" + "=" * 60)
print("FUNDAMENTAL OBSTRUCTION")
print("=" * 60)

print("""
THEOREM (structural, from this computation):
  The BdG Nambu doubling does NOT admit a non-trivial twist sigma
  from A_F automorphisms when A_F = C + H + M_3(C) acts diagonally
  in the Nambu-Gorkov space.

PROOF:
  An element a in A_F is represented on H_BdG = H + H* as:
    pi_BdG(a) = diag(pi(a), pi(a)^*)
  where pi: A_F -> End(H) is the original representation.

  For any automorphism sigma in Aut(A_F):
    sigma acts on a, giving pi_BdG(sigma(a)) = diag(pi(sigma(a)), pi(sigma(a))^*)

  The twisted first-order condition becomes:
    [[D_BdG, pi_BdG(a)], pi_BdG(sigma(b))^o] = 0

  Since pi_BdG(a) is DIAGONAL in Nambu space and D_BdG has off-diagonal
  Delta terms, the commutator [D_BdG, pi_BdG(a)] generates off-diagonal
  contributions proportional to [Delta, a] - [Delta, a].

  For diagonal a (as in the mode basis): [D_BdG, pi_BdG(a)] is diagonal
  in each 2x2 block (proportional to [eps_k, a_k] in the particle sector
  and [-eps_k, a_k] in the hole sector).  The outer commutator with
  pi_BdG(sigma(b))^o is then the same as the original order-one condition,
  independent of sigma.

  CONSEQUENCE: The twisted first-order condition is IDENTICAL to the
  untwisted one.  The twist sigma has NO EFFECT on the order-one axiom
  when A_F acts diagonally in Nambu space.

  This is because Aut(A_F) acts on the algebra A_F, while the Nambu
  doubling acts on the HILBERT SPACE H.  These are independent structures.
  The twist changes the algebra relations; the BdG doubling changes
  the representation space.  They do not interact non-trivially.

IMPLICATION FOR THE FRAMEWORK:
  To obtain a non-trivial twist in the BdG setting, one needs EITHER:
  (1) An enlarged algebra that acts non-diagonally in Nambu space
      (e.g., A_BdG = A_F otimes M_2(C) with Nambu matrices as algebra elements)
  (2) A twist that acts on the representation pi rather than the algebra A
      (this is the Bogoliubov transformation, but it is not an NCG twist)
  (3) A completely different approach: use the BdG structure to CONSTRUCT
      a new spectral triple (as in the S35 workshop), rather than twisting
      an existing one.
""")

# =============================================================================
# 8. KREIN SIGNATURE ANALYSIS
# =============================================================================

print("=" * 60)
print("KREIN SIGNATURE ANALYSIS")
print("=" * 60)

print(f"""
  BdG Krein signature: ({n_pos_nambu}, {n_neg_nambu}) = (8, 8)

  The (3,1) Lorentzian signature CANNOT emerge from the internal space alone.

  Paper 44 (Martinetti 2026) Krein signature:
    The SM fermionic Hilbert space H_F = C^32 under minimal twist gives
    signature (8, 8) per generation = (8+: chirality-left, 8-: chirality-right).
    The U(2,2) subgroup of U(8,8) acts on 4 of the 16 internal directions,
    recovering the conformal group of Minkowski spacetime.

  Our BdG result (8, 8):
    - 8 particle modes (positive metric): represent "matter" directions
    - 8 hole modes (negative metric): represent "antimatter" directions
    - U(8,8) symmetry group contains U(2,2)
    - CONSISTENT with Paper 44 in structure, though the (3,1) requires
      composition with spacetime M^4

  For the FULL product geometry M^4 x SU(3) with BdG:
    Krein signature would be dim(M^4) x (8,8) = (4x8, 4x8) = (32,32)
    with the spacetime factor contributing (3,1) through Wick rotation.
    The (3,1) is a spacetime property, not an internal-space property.

  TARGET (3,1) REACHED: NO
  STRUCTURAL REASON: (3,1) requires M^4 factor, internal BdG gives (N,N)
""")

# =============================================================================
# 9. AXIOM VERIFICATION SUMMARY
# =============================================================================

print("=" * 60)
print("AXIOM VERIFICATION SUMMARY")
print("=" * 60)

axiom_results = {}

# A1: Self-adjointness
axiom_results['A1_self_adjoint'] = sa_err < 1e-10
print(f"\n(A1) D self-adjoint: {sa_err:.2e} -> {'PASS' if axiom_results['A1_self_adjoint'] else 'FAIL'}")

# A2: Compact resolvent (finite-dim = automatic)
axiom_results['A2_compact_resolvent'] = True
print(f"(A2) Compact resolvent: dim={N_BdG} (finite) -> PASS")

# A3: Order-one
# Inherited failure from D_K (norm 4.000, S46 OMEGA-CLASSIFY-46)
axiom_results['A3_order_one'] = False
print(f"(A3) Order-one: FAILS (inherited from D_K, norm 4.000)")
print(f"     BdG adds O(Delta*4.000) ~ {abs(Delta_diag[0])*4:.3f} (S35 workshop)")
print(f"     Twist has NO effect (trivial on diagonal A_F, see Section 7)")

# A4: KO-dimension
axiom_results['A4_KO_dim'] = True  # S35 result
print(f"(A4) KO-dim 6: PASS (S35 workshop, full spinor bundle)")
print(f"     8-mode truncation: eps={eps_J}, eps''={eps_double_prime}, eps'_C={eps_prime_C}")
print(f"     (mode space cannot determine eps' for J)")

# A5: Poincare duality
axiom_results['A5_poincare'] = True
print(f"(A5) Poincare duality: PASS (K_0(A_F)=Z^3 unchanged by BdG)")

# A6: Orientability
axiom_results['A6_orientability'] = orientability
if not orientability:
    print(f"(A6) Orientability: FAIL")
    print(f"     {{gamma_BdG, D_BdG}} = {gamma_D_err:.4f} (non-zero)")
    print(f"     Expected: 2*max(eps_k) = {2*np.max(np.abs(epsilon)):.4f}")
    print(f"     BCS pairing Delta breaks the Nambu grading.")
    print(f"     STRUCTURAL: any non-zero pairing breaks orientability in Nambu space.")
else:
    print(f"(A6) Orientability: PASS")

# A7: Regularity (finite-dim = automatic)
axiom_results['A7_regularity'] = True
print(f"(A7) Regularity: PASS (finite-dimensional)")

# Count
n_pass = sum(v for v in axiom_results.values())
n_fail = sum(not v for v in axiom_results.values())
print(f"\nAxioms: {n_pass}/7 PASS, {n_fail}/7 FAIL")
print(f"Failed: A3 (order-one, inherited), A6 (orientability, BCS structural)")

# =============================================================================
# 10. GATE VERDICT
# =============================================================================

print("\n" + "=" * 60)
print("GATE VERDICT: TWIST-BDG-46")
print("=" * 60)

ko_preserved = True         # KO-dim 6 from S35, invariant under twists (Paper 30)
krein_31 = False             # (8,8), not (3,1)
axiom_violated = not orientability  # A6 fails

# Gate: PASS if KO-dim preserved AND Krein (3,1)
# FAIL if axioms violated
verdict = "FAIL"
if ko_preserved and krein_31 and not axiom_violated:
    verdict = "PASS"

print(f"""
  KO-dimension preserved: {ko_preserved}
    KO-dim 6 invariant under twists (Paper 30, Filaci-Martinetti theorem).
    S35 workshop: (eps,eps',eps'')=(+1,+1,-1) for full spinor BdG triple.

  Krein signature = (3,1): {krein_31}
    BdG Nambu doubling gives (N_modes, N_modes) = ({n_pos_nambu}, {n_neg_nambu}).
    (3,1) requires spacetime M^4 (external factor), not available from SU(3).
    Paper 44: (8,8) per generation, consistent with our result.

  Axiom violations:
    A3 (order-one): FAIL (inherited, norm 4.000)
    A6 (orientability): FAIL (Delta breaks Nambu grading, {{gamma,D}}={gamma_D_err:.4f})

  VERDICT: {verdict}

  STRUCTURAL CONCLUSION:
    The BCS order parameter Delta is NOT an algebra automorphism of A_F.
    It is a Hilbert space transformation (Bogoliubov rotation).
    These are mathematically distinct operations:
      - NCG twist: sigma in Aut(A_F), acts on algebra elements
      - BCS transformation: U in U(H_BdG), acts on states
    The twist has NO non-trivial action on the BdG triple when A_F acts
    diagonally in Nambu space (proven in Section 7).

    The Krein structure (8,8) from particle-hole is well-defined but does
    NOT reduce to (3,1) without the spacetime manifold M^4.

    The correct NCG object for the BCS system is the UNTWISTED BdG spectral
    triple from S35 (KO-dim 6 preserved, both KILL gates PASS).
    Twisting adds nothing: the BCS physics lives in the Hilbert space, not
    the algebra.
""")

# =============================================================================
# 11. SAVE RESULTS
# =============================================================================

runtime = time.time() - t_start
print(f"Runtime: {runtime:.1f} s")

results = {
    # BdG spectral triple
    'D_BdG': D_BdG,
    'E_BdG': E_BdG_computed,
    'epsilon': epsilon,
    'Delta_diag': Delta_diag,
    'N_modes': np.int64(N_modes),
    'N_BdG': np.int64(N_BdG),

    # Bogoliubov data
    'u0': u0,
    'v0': v0,
    'theta_bogo': np.arctan2(v0, u0),

    # Symmetry operators
    'J_matrix': J_matrix,
    'C_ph': C_ph,
    'gamma_BdG': gamma_BdG,

    # Signs
    'eps_J': np.int64(eps_J),
    'eps_prime_C': np.int64(eps_prime_C),
    'eps_double_prime': np.int64(eps_double_prime),

    # Twist analysis
    'D_rho': D_rho_herm,
    'E_rho': E_rho,
    'rho_spectrum_change': spec_change,
    'rho_krein_valid': rho_krein_valid,

    # Krein structure
    'krein_signature': np.array([n_pos_nambu, n_neg_nambu]),
    'krein_31_target': krein_31,

    # Axiom results
    'sa_err': sa_err,
    'gamma_D_anticomm_norm': gamma_D_err,
    'orientability_pass': orientability,
    'order_one_pass': False,
    'ko_preserved': ko_preserved,

    # Gate
    'verdict': np.array([verdict]),
    'runtime': runtime,
    'Delta_fold': Delta_fold,
}

np.savez('tier0-computation/s46_twist_bdg.npz', **results)
print(f"Saved: tier0-computation/s46_twist_bdg.npz")

# =============================================================================
# 12. DIAGNOSTIC PLOT
# =============================================================================

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

fig, axes = plt.subplots(2, 3, figsize=(16, 10))
fig.suptitle('TWIST-BDG-46: Twisted BdG Spectral Triple on SU(3)\n'
             f'VERDICT: {verdict}', fontsize=14, fontweight='bold')

# Panel 1: BdG spectrum
ax = axes[0, 0]
E_sorted = np.sort(E_BdG_computed)
colors_spec = ['steelblue' if e > 0 else 'coral' for e in E_sorted]
ax.barh(range(len(E_sorted)), E_sorted, color=colors_spec)
ax.axvline(0, color='k', lw=0.5)
ax.set_xlabel('Energy (M_KK)')
ax.set_ylabel('Mode index')
ax.set_title('BdG Spectrum at Fold')
ax.text(0.05, 0.95, f'16 eigenvalues\n8 +/- pairs\nPH err: {ph_err:.1e}',
        transform=ax.transAxes, va='top', fontsize=9)

# Panel 2: Bogoliubov angles
ax = axes[0, 1]
thetas = np.arctan2(v0, u0) * 180 / np.pi
colors_bogo = ['C0'] * 4 + ['C1'] + ['C2'] * 3
ax.bar(range(N_modes), thetas, color=colors_bogo)
ax.axhline(45, color='r', ls='--', lw=1, label=r'$\pi/4$ (max mixing)')
ax.set_xlabel('Mode index')
ax.set_ylabel('Bogoliubov angle (deg)')
ax.set_title('BCS Mixing Angles')
ax.legend(fontsize=8)
for k in range(N_modes):
    ax.text(k, thetas[k] + 1, f'{thetas[k]:.1f}', ha='center', fontsize=7)

# Panel 3: Krein signature
ax = axes[0, 2]
krein_vals = np.zeros(N_BdG)
krein_vals[::2] = +1   # particle: positive
krein_vals[1::2] = -1  # hole: negative
colors_krein = ['steelblue' if v > 0 else 'coral' for v in krein_vals]
ax.bar(range(N_BdG), krein_vals, color=colors_krein)
ax.set_xlabel('BdG index (particle/hole alternating)')
ax.set_ylabel('Krein sign')
ax.set_title(f'Krein Signature: ({n_pos_nambu}, {n_neg_nambu})')
ax.text(0.5, 0.05, 'TARGET (3,1): NOT REACHED',
        transform=ax.transAxes, ha='center', fontsize=11, color='red', fontweight='bold')

# Panel 4: rho^2 eigenvalues
ax = axes[1, 0]
eta_sorted = np.sort(np.real(eta_rho2_evals))
ax.bar(range(len(eta_sorted)), eta_sorted, color='purple', alpha=0.7)
ax.axhline(1, color='k', ls='--', lw=0.5, alpha=0.5)
ax.axhline(-1, color='k', ls='--', lw=0.5, alpha=0.5)
ax.set_xlabel('Index')
ax.set_ylabel(r'$\eta = \rho^2$ eigenvalue')
ax.set_title(r'$\rho = e^{i\pi\hat{\Delta}}$: $\eta = \rho^2$')
ax.text(0.05, 0.95, r'$\eta^2 = I$ err: ' + f'{eta_invol_err:.1e}\n'
        + ('NOT involutive' if eta_invol_err > 0.01 else 'Involutive'),
        transform=ax.transAxes, va='top', fontsize=9,
        color='red' if eta_invol_err > 0.01 else 'green')

# Panel 5: Spectrum comparison D vs D_rho
ax = axes[1, 1]
x_idx = np.arange(N_BdG)
ax.plot(x_idx, np.sort(E_BdG_computed), 'bo-', ms=4, label=r'$D_{BdG}$')
ax.plot(x_idx, np.sort(np.real(E_rho)), 'r^--', ms=4, label=r'$D_\rho = \rho D \rho^{-1}$')
ax.set_xlabel('Eigenvalue index')
ax.set_ylabel('Energy (M_KK)')
ax.set_title(r'Spectrum: $D_{BdG}$ vs $D_\rho$')
ax.legend(fontsize=9)
ax.text(0.05, 0.05, f'Max diff: {spec_change:.1e}\n(unitary preserves spectrum)',
        transform=ax.transAxes, fontsize=9)

# Panel 6: Axiom summary
ax = axes[1, 2]
ax.axis('off')
axiom_text = (
    f"AXIOM VERIFICATION\n"
    f"{'='*40}\n"
    f"A1 Self-adjoint:      PASS ({sa_err:.1e})\n"
    f"A2 Compact resolvent: PASS (finite-dim)\n"
    f"A3 Order-one:         FAIL (4.000, inherited)\n"
    f"A4 KO-dim 6:          PASS (S35, invariant)\n"
    f"A5 Poincare duality:  PASS (K_0 unchanged)\n"
    f"A6 Orientability:     FAIL ({gamma_D_err:.3f})\n"
    f"A7 Regularity:        PASS (finite-dim)\n"
    f"{'='*40}\n"
    f"5/7 PASS, 2/7 FAIL\n\n"
    f"STRUCTURAL:\n"
    f"BCS = Hilbert space transform\n"
    f"NCG twist = algebra automorphism\n"
    f"These are DISTINCT operations.\n"
    f"No non-trivial BCS twist exists\n"
    f"when A_F acts diag in Nambu space."
)
ax.text(0.05, 0.95, axiom_text, transform=ax.transAxes, va='top', fontsize=9.5,
        family='monospace', bbox=dict(boxstyle='round', facecolor='lightyellow', alpha=0.8))

plt.tight_layout()
plt.savefig('tier0-computation/s46_twist_bdg.png', dpi=150, bbox_inches='tight')
print("Saved: tier0-computation/s46_twist_bdg.png")
