#!/usr/bin/env python3
"""
s70_phi_eff_compound.py — SU(1,1) Reconciliation of Squeeze Phases
===================================================================

Session 70, W2-D: PHI-EFF-COMPOUND-70

Physics:
    W1-A (PHI-EFF-69) computed the per-mode BCS squeeze phase:
        cos(phi_eff) = -0.181 (weakly destructive interference)
    W2-B (SU11-PHASE-69) computed the spatial thermal phase coherence:
        <cos(phi)> = +0.800 (constructive interference, von Mises distribution)

    These are different projections of the same SU(1,1) algebraic structure.
    The per-mode BCS squeeze is an element of SU(1,1) with squeeze parameter
    r_k and phase phi_k. The spatial thermal average is an integration over
    the U(1) subgroup (generated by K_0).

    The compound squeeze parameter is obtained by SU(1,1) group multiplication:
        S_compound = S_spatial * S_BCS

    where each S is a 2x2 matrix in the Bargmann representation:
        S(r, phi) = [[cosh(r), e^{i*phi} * sinh(r)],
                      [e^{-i*phi} * sinh(r), cosh(r)]]

    The spatial phase is drawn from a von Mises distribution P_vM(phi; kappa)
    and averaged over.

Pre-registered gate: PHI-EFF-COMPOUND-70
    Range: cos(phi_compound) in [-0.181, +0.800]
    INFO: report compound r and phi for all modes

Input files:
    - computations/_shared/canonical_constants.py
    - computations/session-69/s69_phi_eff.npz (per-mode BCS squeeze phases)
    - computations/session-69/s69_su11_phase.npz (spatial thermal phase distribution)
    - computations/session-69/s69_squeeze_reconciled.npz (reconciled squeeze parameters)

Output files:
    - computations/session-70/s70_phi_eff_compound.npz
"""

import numpy as np
from scipy.special import i0 as bessel_I0, i1 as bessel_I1
from scipy.integrate import quad
import sys
import os

# Import canonical constants
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from canonical_constants import (
    Delta_BCS, T_acoustic, N_dof_BCS, J_C2
)


# =============================================================================
#  Section 1: Load input data
# =============================================================================

print("=" * 72)
print("S70 W2-D: PHI-EFF-COMPOUND-70 — SU(1,1) Reconciliation")
print("=" * 72)

# Load per-mode BCS squeeze data from S69
phi_eff_data = np.load("computations/session-69/s69_phi_eff.npz", allow_pickle=True)
labels = phi_eff_data["labels"]  # 8 modes: B2[0..3], B1, B3[0..2]
xi_k = phi_eff_data["xi_k"]     # Single-particle energies relative to mu
E_k = phi_eff_data["E_k"]       # Quasiparticle energies
u_k_sq = phi_eff_data["u_k_sq"]
v_k_sq = phi_eff_data["v_k_sq"]
uv_product = phi_eff_data["uv_product"]
theta_BCS = phi_eff_data["theta_BCS"]         # BCS mixing angle
phi_anomalous = phi_eff_data["phi_anomalous"] # Anomalous phase per mode
phi_k_total = phi_eff_data["phi_k_total"]     # Total BCS phase per mode
cos_phi_k = phi_eff_data["cos_phi_k_total"]   # cos of total BCS phase
phi_eff_scalar = float(phi_eff_data["phi_eff"])
cos_phi_eff_bcs = float(phi_eff_data["cos_phi_eff"])
r_eff_bcs = float(phi_eff_data["r_eff"])

# Load spatial phase data from S69
phase_data = np.load("computations/session-69/s69_su11_phase.npz", allow_pickle=True)
kappa_vM = float(phase_data["thermal_kappa"])            # von Mises concentration
cos_phi_spatial = float(phase_data["thermal_cos_weighted_mean"])  # <cos(phi)>_spatial
T_GGE = float(phase_data["T_GGE"])

# Load reconciled squeeze parameters from S69
recon_data = np.load("computations/session-69/s69_squeeze_reconciled.npz", allow_pickle=True)
r_acoustic = float(recon_data["r_acoustic"])
r_leggett = float(recon_data["r_leggett"])
r_optical = float(recon_data["r_optical"])
r_eff_canonical = float(recon_data["r_eff_canonical"])
OOM_canonical = float(recon_data["OOM_canonical"])
f_w_acoustic = float(recon_data["f_w_acoustic"])
f_w_leggett = float(recon_data["f_w_leggett"])
f_w_optical = float(recon_data["f_w_optical"])

print(f"\n--- Input Summary ---")
print(f"BCS per-mode:  cos(phi_eff) = {cos_phi_eff_bcs:+.6f}, "
      f"r_eff = {r_eff_bcs:.4f}, phi_eff = {phi_eff_scalar:.6f} rad")
print(f"Spatial:       <cos(phi)> = {cos_phi_spatial:+.6f}, "
      f"kappa = {kappa_vM:.4f}, T_GGE = {T_GGE:.4f}")
print(f"Reconciled:    r_acoustic = {r_acoustic:.4f}, "
      f"r_leggett = {r_leggett:.4f}, r_optical = {r_optical:.4f}")
print(f"               r_eff_canonical = {r_eff_canonical:.4f}, "
      f"OOM_canonical = {OOM_canonical:.4f}")
print(f"               f_w = ({f_w_acoustic:.4f}, {f_w_leggett:.4f}, {f_w_optical:.4f})")


# =============================================================================
#  Section 2: SU(1,1) Bargmann representation
# =============================================================================
#
# The Bargmann (fundamental) representation of SU(1,1) for a two-mode squeeze:
#
#   S(r, phi) = [[cosh(r),           e^{i*phi} * sinh(r)],
#                [e^{-i*phi} * sinh(r), cosh(r)          ]]
#
# This satisfies det(S) = cosh^2(r) - sinh^2(r) = 1, as required for SU(1,1).
#
# Group multiplication: S_compound = S_1 * S_2 gives a new SU(1,1) element
# from which we extract compound (r, phi).
#
# The generators are:
#   K_0 = 0.5 * [[1, 0], [0, -1]]     (number operator)
#   K_+ = 0.5 * [[0, 1], [0, 0]]      (squeeze creation)
#   K_- = 0.5 * [[0, 0], [1, 0]]      (squeeze annihilation)
#
# The BCS squeeze is parametrized by (r_k, phi_k) for each mode k.
# The spatial phase fluctuation adds a random phase phi drawn from von Mises.
# The spatial element is S(r_spatial, phi_spatial) where r_spatial encodes
# the amplitude of inter-site coherence and phi_spatial is the random angle.

def su11_matrix(r, phi):
    """Construct the SU(1,1) Bargmann matrix S(r, phi)."""
    cr = np.cosh(r)
    sr = np.sinh(r)
    ep = np.exp(1j * phi)
    em = np.exp(-1j * phi)
    return np.array([[cr, ep * sr],
                     [em * sr, cr]], dtype=complex)


def extract_su11_params(S):
    """
    Extract (r, phi) from an SU(1,1) Bargmann matrix.

    Given S = [[alpha, beta], [beta*, alpha*]] with |alpha|^2 - |beta|^2 = 1:
        cosh(r) = |alpha|
        sinh(r) = |beta|
        phi = arg(beta) + arg(alpha)  -- but alpha is real if we started clean

    More precisely:
        r = arccosh(|S[0,0]|)
        phi = angle(S[0,1])
    """
    alpha = S[0, 0]
    beta = S[0, 1]
    r_out = np.arccosh(np.abs(alpha))
    phi_out = np.angle(beta)
    return float(r_out), float(phi_out)


def von_mises_pdf(phi, kappa):
    """Von Mises probability density function on [0, 2*pi)."""
    return np.exp(kappa * np.cos(phi)) / (2 * np.pi * float(bessel_I0(kappa)))


# =============================================================================
#  Section 3: Determine spatial squeeze parameter r_spatial
# =============================================================================
#
# The spatial thermal phase coherence <cos(phi)> = I_1(kappa)/I_0(kappa) = 0.800
# from the von Mises distribution with kappa = E_J / T_GGE.
#
# The spatial squeeze parameter r_spatial encodes the amplitude of inter-site
# pair tunneling. In the Josephson array picture, a pair tunneling event across
# a junction with coupling E_J creates a two-mode squeezed state with:
#
#   r_spatial = arctanh(E_J / (E_J + 2*E_k))
#
# where E_k is the quasiparticle energy. For the thermal ensemble, the
# effective squeeze is weighted by the Boltzmann factor exp(-E_k / T_GGE).
#
# However, there is a cleaner derivation from the von Mises coherence directly.
# The von Mises parameter kappa = E_J / T_GGE determines both the phase
# distribution AND the squeeze amplitude. The effective spatial squeeze is:
#
#   r_spatial = 0.5 * ln((1 + <cos(phi)>) / (1 - <cos(phi)>))
#            = arctanh(<cos(phi)>)
#
# This maps the coherence directly to a squeeze parameter through the
# SU(1,1) algebraic identity: for a thermally-averaged squeeze, the
# mean off-diagonal element is <sinh(r)*e^{i*phi}> = sinh(r_eff)*<e^{i*phi}>
# and <cos(phi)> = I_1(kappa)/I_0(kappa).

print(f"\n--- Section 3: Spatial Squeeze Parameter ---")

# Method 1: Direct from coherence (arctanh mapping)
r_spatial_coherence = np.arctanh(cos_phi_spatial)
print(f"r_spatial (arctanh coherence) = {r_spatial_coherence:.6f}")
print(f"  cosh(2*r_spatial) = {np.cosh(2 * r_spatial_coherence):.6f}")

# Method 2: From Josephson coupling ratio
# E_J_eff is the weighted average Josephson coupling
# Using J_C2 = 0.933 as the dominant Josephson coupling
J_C2_val = J_C2  # From canonical constants (S47)
r_spatial_josephson = np.arctanh(J_C2_val / (J_C2_val + 2 * Delta_BCS))
print(f"r_spatial (Josephson/Delta) = {r_spatial_josephson:.6f}")

# Use Method 1 as the primary: it's a direct algebraic consequence
# of the von Mises thermal average, no model assumptions needed
r_spatial = r_spatial_coherence
print(f"\n=> Using r_spatial = {r_spatial:.6f} (coherence route, model-independent)")


# =============================================================================
#  Section 4: Per-mode compound squeeze via SU(1,1) multiplication
# =============================================================================
#
# For each BCS mode k, construct S_BCS(r_k, phi_k) and average
# the product S_spatial(r_spatial, phi) * S_BCS(r_k, phi_k) over the
# von Mises distribution of spatial phases phi.
#
# Per-mode squeeze parameters (from S69):
#   - B2 modes (flat band): r = arccosh(1/sqrt(1 - 4*u*v)) where u*v = 0.5
#     These are maximally squeezed at the flat band center
#   - B1 mode: slightly off-center, r ~ 0.617
#   - B3 modes: further off, r ~ 0.982
#
# The per-mode BCS squeeze parameter r_k is related to the Bogoliubov
# amplitudes by: tanh(r_k) = 2*u_k*v_k (the anomalous expectation value).

print(f"\n--- Section 4: Per-Mode Compound Squeeze ---")

# Extract per-mode squeeze parameters from BCS data
n_modes = len(labels)
r_k = np.zeros(n_modes)
phi_k = np.zeros(n_modes)  # BCS phases per mode

for i in range(n_modes):
    # BCS squeeze parameter: tanh(r_k) = 2*u_k*v_k (pair amplitude)
    # For the flat-band B2 modes with u=v=1/sqrt(2), this gives tanh(r)=1 -> r=inf
    # But physically, the squeeze is bounded by the gap structure.
    # The correct relation from the Bogoliubov transformation is:
    #   sinh(r_k) = v_k / sqrt(u_k^2 - v_k^2)  when u > v
    #   OR use r_k = arctanh(v_k/u_k) = 0.5 * theta_BCS
    # For u=v (flat band), we need the regularized form.

    uv = uv_product[i]
    u2 = u_k_sq[i]
    v2 = v_k_sq[i]

    if abs(u2 - v2) < 1e-10:
        # Flat-band B2 modes: maximally entangled, r -> large
        # Use the energy ratio: sinh(r_k) = Delta / (2*E_k) * (1/cos(theta_BCS))
        # For u=v=0.5: E_k = Delta, so cosh(2*r_k) = 1/(1-4*u*v) diverges
        # Regularize: use the physical bound from the mode energy
        # r_k = 0.5 * ln(2*E_k / delta_xi) where delta_xi is the level spacing
        # At the flat band, the BCS squeeze is parametrically large.
        # From reconciled data: r_acoustic = 1.786 captures this regime.
        r_k[i] = r_acoustic  # B2 flat-band modes use the acoustic squeeze
    elif u2 > v2:
        r_k[i] = 0.5 * np.log((u2 + v2 + 2 * uv) / (u2 + v2 - 2 * uv))
    else:
        r_k[i] = 0.5 * np.log((u2 + v2 + 2 * uv) / (u2 + v2 - 2 * uv))

    # BCS phase: the total phase per mode from the phi_eff computation
    phi_k[i] = phi_k_total[i]

print(f"\nPer-mode BCS squeeze parameters:")
print(f"{'Mode':<8} {'r_k':>8} {'phi_k (rad)':>12} {'cos(phi_k)':>12} {'cosh(2r_k)':>12}")
print("-" * 56)
for i in range(n_modes):
    print(f"{str(labels[i]):<8} {r_k[i]:>8.4f} {phi_k[i]:>12.4f} "
          f"{np.cos(phi_k[i]):>12.6f} {np.cosh(2*r_k[i]):>12.4f}")


# =============================================================================
#  Section 5: Numerical SU(1,1) group multiplication + von Mises average
# =============================================================================
#
# For each mode k:
#   <S_compound>_k = integral_0^{2*pi} S(r_spatial, phi) * S(r_k, phi_k)
#                     * P_vM(phi; kappa) dphi
#
# This integral can be computed analytically for the matrix elements.
# The (0,0) element of the product:
#   [S1 * S2]_{00} = cosh(r1)*cosh(r2) + e^{i(phi1 - phi2)}*sinh(r1)*sinh(r2)
# The (0,1) element:
#   [S1 * S2]_{01} = cosh(r1)*e^{i*phi2}*sinh(r2) + e^{i*phi1}*sinh(r1)*cosh(r2)
#
# Averaging over phi1 (the spatial phase) with von Mises P_vM(phi1; kappa):
#   <e^{i*phi1}> = I_1(kappa) / I_0(kappa) = <cos(phi)>_spatial (for real part)
#   <e^{-i*phi1}> = I_1(kappa) / I_0(kappa)  (von Mises is symmetric)
#   <e^{i*(phi1 - phi2)}> = e^{-i*phi2} * I_1(kappa) / I_0(kappa)
#
# So:
#   <[S1*S2]_{00}> = cosh(r1)*cosh(r2) + e^{-i*phi2}*sinh(r1)*sinh(r2) * C
#   <[S1*S2]_{01}> = cosh(r1)*e^{i*phi2}*sinh(r2) + sinh(r1)*cosh(r2) * C * e^{+i*mean}
#
# where C = I_1(kappa)/I_0(kappa) = <cos(phi)> and mean=0 for centered von Mises.
#
# BUT: The von Mises is centered at phi=0 (the equilibrium Josephson phase).
# So <e^{i*phi}> = I_1(kappa)/I_0(kappa) is real and positive.

print(f"\n--- Section 5: Compound SU(1,1) Computation ---")

# Von Mises coherence factor
C_vM = float(bessel_I1(kappa_vM)) / float(bessel_I0(kappa_vM))
print(f"Von Mises coherence: C = I_1(kappa)/I_0(kappa) = {C_vM:.6f}")
print(f"  (should match <cos(phi)>_spatial = {cos_phi_spatial:.6f})")

# Method A: Analytical von Mises-averaged SU(1,1) product
# For S_spatial(r_s, phi_random) * S_BCS(r_k, phi_k), averaging over phi_random:
#
#   <alpha_compound> = cosh(r_s)*cosh(r_k) + C_vM * sinh(r_s)*sinh(r_k) * e^{-i*phi_k}
#   <beta_compound>  = cosh(r_s)*sinh(r_k)*e^{i*phi_k} + C_vM * sinh(r_s)*cosh(r_k)
#
# The von Mises average damps the cross-terms by C_vM.

r_compound = np.zeros(n_modes)
phi_compound = np.zeros(n_modes)
cosh2r_compound = np.zeros(n_modes)
alpha_compound = np.zeros(n_modes, dtype=complex)
beta_compound = np.zeros(n_modes, dtype=complex)

for i in range(n_modes):
    rs = r_spatial
    rk = r_k[i]
    pk = phi_k[i]

    # Analytical average of SU(1,1) product over von Mises spatial phase
    a_avg = (np.cosh(rs) * np.cosh(rk)
             + C_vM * np.sinh(rs) * np.sinh(rk) * np.exp(-1j * pk))
    b_avg = (np.cosh(rs) * np.sinh(rk) * np.exp(1j * pk)
             + C_vM * np.sinh(rs) * np.cosh(rk))

    alpha_compound[i] = a_avg
    beta_compound[i] = b_avg

    # Extract compound parameters
    # |alpha|^2 - |beta|^2 should = 1 for exact SU(1,1).
    # After averaging, this is NOT exactly 1 (the average of SU(1,1) matrices
    # is not in SU(1,1) -- it's a positive map). The departure measures decoherence.
    det_check = np.abs(a_avg)**2 - np.abs(b_avg)**2

    # Compound squeeze parameter from |alpha| and |beta|
    r_compound[i] = np.arccosh(np.abs(a_avg)) if np.abs(a_avg) >= 1.0 else 0.0
    phi_compound[i] = np.angle(b_avg)
    cosh2r_compound[i] = 2 * np.abs(a_avg)**2 - 1  # cosh(2r) = 2*cosh^2(r) - 1

print(f"\nCompound squeeze parameters (analytical von Mises average):")
print(f"{'Mode':<8} {'r_comp':>8} {'phi_comp':>10} {'cos(phi_c)':>12} "
      f"{'cosh(2r_c)':>12} {'det':>10}")
print("-" * 66)
for i in range(n_modes):
    det_i = np.abs(alpha_compound[i])**2 - np.abs(beta_compound[i])**2
    print(f"{str(labels[i]):<8} {r_compound[i]:>8.4f} {phi_compound[i]:>10.4f} "
          f"{np.cos(phi_compound[i]):>12.6f} {cosh2r_compound[i]:>12.4f} "
          f"{det_i:>10.6f}")


# =============================================================================
#  Section 5b: Numerical verification via Monte Carlo integration
# =============================================================================

print(f"\n--- Section 5b: Monte Carlo Verification ---")

N_mc = 200_000
np.random.seed(42)

# Draw von Mises samples
# numpy's vonmises uses the convention centered at mu with concentration kappa
phi_samples = np.random.vonmises(mu=0.0, kappa=kappa_vM, size=N_mc)

r_compound_mc = np.zeros(n_modes)
phi_compound_mc = np.zeros(n_modes)
alpha_mc = np.zeros(n_modes, dtype=complex)
beta_mc = np.zeros(n_modes, dtype=complex)

for i in range(n_modes):
    rk = r_k[i]
    pk = phi_k[i]
    rs = r_spatial

    # For each MC sample, compute S_spatial * S_BCS
    a_sum = 0.0 + 0j
    b_sum = 0.0 + 0j

    # Vectorized computation
    crs = np.cosh(rs)
    srs = np.sinh(rs)
    crk = np.cosh(rk)
    srk = np.sinh(rk)
    ep_s = np.exp(1j * phi_samples)
    em_s = np.exp(-1j * phi_samples)
    ep_k = np.exp(1j * pk)
    em_k = np.exp(-1j * pk)

    # [S_s * S_k]_{00} = cosh(rs)*cosh(rk) + e^{i*phi_s} * sinh(rs) * e^{-i*phi_k} * sinh(rk)
    a_samples = crs * crk + ep_s * srs * em_k * srk
    # [S_s * S_k]_{01} = cosh(rs) * e^{i*phi_k} * sinh(rk) + e^{i*phi_s} * sinh(rs) * cosh(rk)
    b_samples = crs * ep_k * srk + ep_s * srs * crk

    a_avg_mc = np.mean(a_samples)
    b_avg_mc = np.mean(b_samples)

    alpha_mc[i] = a_avg_mc
    beta_mc[i] = b_avg_mc

    r_compound_mc[i] = np.arccosh(np.abs(a_avg_mc)) if np.abs(a_avg_mc) >= 1.0 else 0.0
    phi_compound_mc[i] = np.angle(b_avg_mc)

print(f"\nMonte Carlo vs Analytical comparison (N_mc = {N_mc:,}):")
print(f"{'Mode':<8} {'r_ana':>8} {'r_mc':>8} {'|dr|':>10} "
      f"{'phi_ana':>10} {'phi_mc':>10} {'|dphi|':>10}")
print("-" * 68)
for i in range(n_modes):
    dr = abs(r_compound[i] - r_compound_mc[i])
    dphi = abs(phi_compound[i] - phi_compound_mc[i])
    print(f"{str(labels[i]):<8} {r_compound[i]:>8.4f} {r_compound_mc[i]:>8.4f} "
          f"{dr:>10.2e} {phi_compound[i]:>10.4f} {phi_compound_mc[i]:>10.4f} "
          f"{dphi:>10.2e}")


# =============================================================================
#  Section 6: Weighted compound observables
# =============================================================================
#
# The spectral weight fractions f_w determine the relative contribution
# of each channel to the total squeeze. From S69:
#   acoustic (B2): f_w = 0.0326
#   Leggett (B1 + 2 of B3): f_w = 0.4619
#   optical (B3 subset): f_w = 0.5056
#
# We assign each mode its channel weight:
#   B2[0..3]: acoustic, 4 modes, weight = f_w_acoustic / 4 each
#   B1:       Leggett, 1 mode + 2 of B3, weight = f_w_leggett / 3
#   B3[0..2]: Leggett contributes f_w_leggett via B1+some B3,
#             optical is the remaining B3 weight
#
# Actually, the spectral weights from S69 are defined for three CHANNELS,
# not individual modes. The mapping is:
#   Acoustic channel: 4 B2 modes
#   Leggett channel: 1 B1 + (weighted) B3 contribution
#   Optical channel: 3 B3 modes (partially shared with Leggett)
#
# For the compound observable, we use the per-mode squeeze parameters
# with the channel spectral weights.

print(f"\n--- Section 6: Weighted Compound Observables ---")

# Mode weights based on channel decomposition
# From S69 phi_eff: w_leggett and w_optical give per-mode weights
w_leggett = phi_eff_data["w_leggett"]  # 3 weights for Leggett channel modes
w_optical = phi_eff_data["w_optical"]  # 4 weights for optical channel modes

# Construct per-mode weight array matching the 8 modes
# B2[0..3] = acoustic, B1 = Leggett[0], B3[0..2] = optical/Leggett
mode_weights = np.zeros(n_modes)

# B2 modes (0-3): acoustic channel
for i in range(4):
    mode_weights[i] = f_w_acoustic / 4.0

# B1 mode (4): Leggett channel center
mode_weights[4] = f_w_leggett * w_leggett[2]  # B1 is w_leggett[2]

# B3 modes (5-7): mixed optical + Leggett
for i in range(3):
    mode_weights[5 + i] = (f_w_leggett * w_leggett[i]
                           + f_w_optical * w_optical[1 + i])

# Normalize
mode_weights /= mode_weights.sum()

print(f"\nPer-mode spectral weights (normalized):")
for i in range(n_modes):
    print(f"  {str(labels[i]):<8}: w = {mode_weights[i]:.6f}")

# Weighted compound phase
cos_phi_compound_weighted = np.sum(mode_weights * np.cos(phi_compound))

# Weighted compound squeeze
r_compound_weighted = np.sum(mode_weights * r_compound)
cosh2r_compound_weighted = np.sum(mode_weights * cosh2r_compound)

print(f"\nWeighted compound results:")
print(f"  cos(phi_compound)_weighted = {cos_phi_compound_weighted:+.6f}")
print(f"  r_compound_weighted = {r_compound_weighted:.6f}")
print(f"  <cosh(2*r_compound)>_weighted = {cosh2r_compound_weighted:.6f}")

# Alternative: compound from the TOTAL averaged matrix
# Instead of averaging r and phi per mode then weighting,
# form the full compound matrix by mode-weighted sum
alpha_total = np.sum(mode_weights * alpha_compound)
beta_total = np.sum(mode_weights * beta_compound)
r_total = np.arccosh(np.abs(alpha_total)) if np.abs(alpha_total) >= 1.0 else 0.0
phi_total = np.angle(beta_total)
cos_phi_total = np.cos(phi_total)

print(f"\nTotal compound (matrix-element weighted):")
print(f"  alpha_total = {alpha_total:.6f}")
print(f"  beta_total = {beta_total:.6f}")
print(f"  r_total = {r_total:.6f}")
print(f"  phi_total = {phi_total:.6f} rad")
print(f"  cos(phi_total) = {cos_phi_total:+.6f}")
print(f"  det check = {np.abs(alpha_total)**2 - np.abs(beta_total)**2:.6f}")


# =============================================================================
#  Section 7: SU(1,1) decomposition into channels
# =============================================================================
#
# The three channels (acoustic, Leggett, optical) have different BCS squeeze
# parameters and different BCS phases. The compound observable for each channel:

print(f"\n--- Section 7: Channel-Level Compound Analysis ---")

channels = {
    "Acoustic (B2)": {"modes": [0, 1, 2, 3], "r_channel": r_acoustic,
                       "cos_bcs": float(phi_eff_data["cos_phi_acoustic"])},
    "Leggett (B1)":  {"modes": [4], "r_channel": r_leggett,
                       "cos_bcs": float(phi_eff_data["cos_phi_leggett"])},
    "Optical (B3)":  {"modes": [5, 6, 7], "r_channel": r_optical,
                       "cos_bcs": float(phi_eff_data["cos_phi_optical"])},
}

channel_r_compound = {}
channel_phi_compound = {}
channel_cos_compound = {}
channel_cosh2r = {}
channel_OOM = {}

for name, ch in channels.items():
    idx = ch["modes"]
    r_ch = np.mean(r_compound[idx])
    phi_ch = np.mean(phi_compound[idx])
    cos_ch = np.mean(np.cos(phi_compound[idx]))
    cosh2r_ch = np.mean(cosh2r_compound[idx])
    oom_ch = np.log10(cosh2r_ch) if cosh2r_ch > 1.0 else 0.0

    channel_r_compound[name] = r_ch
    channel_phi_compound[name] = phi_ch
    channel_cos_compound[name] = cos_ch
    channel_cosh2r[name] = cosh2r_ch
    channel_OOM[name] = oom_ch

    print(f"\n  {name}:")
    print(f"    BCS:       r = {ch['r_channel']:.4f}, cos(phi_BCS) = {ch['cos_bcs']:+.6f}")
    print(f"    Compound:  r = {r_ch:.4f}, cos(phi) = {cos_ch:+.6f}, "
          f"cosh(2r) = {cosh2r_ch:.4f}, OOM = {oom_ch:.4f}")


# =============================================================================
#  Section 7b: Decoherence-corrected compound parameters
# =============================================================================
#
# CRITICAL: The von Mises-averaged SU(1,1) matrix has det != 1.
# This means the averaged matrix is NOT in SU(1,1) -- it's a general positive
# map. The departure from det = 1 measures thermal decoherence.
#
# The physical compound squeeze must be renormalized back onto SU(1,1).
# Two canonical methods:
#
#   (A) Polar decomposition: project the averaged matrix onto SU(1,1) by
#       rescaling alpha -> alpha/sqrt(det), beta -> beta/sqrt(det)
#       This preserves the phase but reduces the squeeze.
#
#   (B) Trace-preserving map: the physical squeeze parameter is the one
#       that gives the same expectation values for SU(1,1) generators
#       as the averaged density matrix. This gives:
#       cosh(2*r_eff) = (|alpha|^2 + |beta|^2) / det

print(f"\n--- Section 7b: Decoherence-Corrected Compound ---")

r_compound_corrected = np.zeros(n_modes)
phi_compound_corrected = np.zeros(n_modes)
cosh2r_compound_corrected = np.zeros(n_modes)

for i in range(n_modes):
    a = alpha_compound[i]
    b = beta_compound[i]
    det_i = np.abs(a)**2 - np.abs(b)**2

    # Method A: Polar decomposition (project back to SU(1,1))
    sqrt_det = np.sqrt(det_i)
    a_norm = a / sqrt_det
    b_norm = b / sqrt_det
    # Now |a_norm|^2 - |b_norm|^2 = 1

    r_corrected = np.arccosh(np.abs(a_norm)) if np.abs(a_norm) >= 1.0 else 0.0
    phi_corrected = np.angle(b_norm)
    cosh2r_corrected = np.cosh(2 * r_corrected)

    r_compound_corrected[i] = r_corrected
    phi_compound_corrected[i] = phi_corrected
    cosh2r_compound_corrected[i] = cosh2r_corrected

print(f"\nDecoherence-corrected compound (polar projection onto SU(1,1)):")
print(f"{'Mode':<8} {'r_raw':>8} {'r_corr':>8} {'cos_raw':>10} {'cos_corr':>10} "
      f"{'c2r_raw':>10} {'c2r_corr':>10}")
print("-" * 68)
for i in range(n_modes):
    print(f"{str(labels[i]):<8} {r_compound[i]:>8.4f} {r_compound_corrected[i]:>8.4f} "
          f"{np.cos(phi_compound[i]):>10.4f} {np.cos(phi_compound_corrected[i]):>10.4f} "
          f"{cosh2r_compound[i]:>10.2f} {cosh2r_compound_corrected[i]:>10.2f}")

# Corrected weighted observables
cos_phi_compound_corrected_w = np.sum(mode_weights * np.cos(phi_compound_corrected))
r_compound_corrected_w = np.sum(mode_weights * r_compound_corrected)
cosh2r_compound_corrected_w = np.sum(mode_weights * cosh2r_compound_corrected)

print(f"\nCorrected weighted compound:")
print(f"  cos(phi_compound)_corrected = {cos_phi_compound_corrected_w:+.6f}")
print(f"  r_compound_corrected = {r_compound_corrected_w:.6f}")
print(f"  <cosh(2r)>_corrected = {cosh2r_compound_corrected_w:.4f}")

# Decoherence factor
decoherence_factor = np.mean([np.abs(alpha_compound[i])**2 - np.abs(beta_compound[i])**2
                              for i in range(n_modes)])
print(f"  Mean det (decoherence) = {decoherence_factor:.6f} (1.0 = pure, >1 = decohered)")

# Corrected A_s enhancement
total_enh_corrected = 0.0  # (local)
for i in range(n_modes):
    c2r = cosh2r_compound_corrected[i]
    t2r = np.tanh(2 * r_compound_corrected[i])
    enh_i = c2r * (1.0 + np.sin(phi_compound_corrected[i]) * t2r)
    if enh_i > 0:
        total_enh_corrected += mode_weights[i] * enh_i

OOM_compound_corrected = np.log10(total_enh_corrected) if total_enh_corrected > 0 else 0.0
print(f"  OOM_compound_corrected = {OOM_compound_corrected:+.4f}")
print(f"  OOM_compound_raw = {np.log10(np.sum(mode_weights * cosh2r_compound)):+.4f}")


# =============================================================================
#  Section 8: A_s correction budget
# =============================================================================
#
# The A_s enhancement from squeezing is:
#   A_s / A_s^{unsqueezed} = cosh(2*r) * (1 + sin(phi)*tanh(2*r))
#
# For the compound observable, the correction in OOM is:
#   delta_OOM = log10(cosh(2*r_compound) * (1 + sin(phi_compound)*tanh(2*r_compound)))
#
# Compared to the separate corrections:
#   W1-A (BCS phase alone): +0.043 OOM
#   W1-F-equivalent (squeeze alone): +0.226 OOM (canonical)
#
# Key question: does the compound give LARGER or SMALLER than the sum?

print(f"\n--- Section 8: A_s Correction Budget ---")

# Separate corrections (from S69)
OOM_bcs_phase = float(phi_eff_data["A_s_correction_OOM"])  # 0.043
OOM_squeeze_canonical = OOM_canonical  # 0.226

print(f"\nSeparate corrections (S69):")
print(f"  BCS phase correction:  {OOM_bcs_phase:+.4f} OOM")
print(f"  Squeeze canonical:     {OOM_squeeze_canonical:+.4f} OOM")
print(f"  Sum (linear):          {OOM_bcs_phase + OOM_squeeze_canonical:+.4f} OOM")

# Compound correction using the weighted compound parameters
# Full formula: A_s enhancement = cosh(2r) * (1 + sin(phi)*tanh(2r))
def As_enhancement_OOM(r, phi):
    """Log10 of the A_s enhancement factor from squeezing."""
    c2r = np.cosh(2 * r)
    s2r = np.sinh(2 * r)
    t2r = np.tanh(2 * r)
    enhancement = c2r * (1.0 + np.sin(phi) * t2r)
    if enhancement > 0:
        return np.log10(enhancement)
    else:
        return np.log10(c2r)  # Phase destructive; use magnitude only

# Per-channel compound OOM
print(f"\nCompound A_s corrections by channel:")
for name, ch in channels.items():
    idx = ch["modes"]
    r_ch = np.mean(r_compound[idx])
    phi_ch = np.mean(phi_compound[idx])
    oom_compound = As_enhancement_OOM(r_ch, phi_ch)
    oom_squeeze_only = np.log10(np.cosh(2 * ch["r_channel"]))
    oom_phase_only = np.log10(1.0 + np.sin(np.mean(phi_k[idx]))
                              * np.tanh(2 * ch["r_channel"]))

    print(f"  {name}:")
    print(f"    Squeeze only:  {oom_squeeze_only:+.4f} OOM")
    print(f"    Phase only:    {oom_phase_only:+.4f} OOM")
    print(f"    Compound:      {oom_compound:+.4f} OOM")
    print(f"    Nonlinearity:  {oom_compound - (oom_squeeze_only + oom_phase_only):+.4f} OOM "
          f"(compound - sum)")

# Total weighted compound (RAW -- inflated by det != 1)
total_enhancement_raw = 0.0  # (local)
for i in range(n_modes):
    c2r = cosh2r_compound[i]
    t2r = np.tanh(2 * r_compound[i])
    enh_i = c2r * (1.0 + np.sin(phi_compound[i]) * t2r)
    if enh_i > 0:
        total_enhancement_raw += mode_weights[i] * enh_i

OOM_compound_raw = np.log10(total_enhancement_raw) if total_enhancement_raw > 0 else 0.0

# Total weighted compound (CORRECTED -- projected back onto SU(1,1))
# This is the physically meaningful number.
OOM_compound_total = OOM_compound_corrected  # from Section 7b

print(f"\nTotal weighted compound correction:")
print(f"  delta_OOM_raw (det!=1):       {OOM_compound_raw:+.4f}")
print(f"  delta_OOM_corrected (SU(1,1)):{OOM_compound_total:+.4f}")
print(f"  vs separate sum:               {OOM_bcs_phase + OOM_squeeze_canonical:+.4f}")
print(f"  vs squeeze-only:               {OOM_squeeze_canonical:+.4f}")
print(f"  Nonlinear gain (corrected):    {OOM_compound_total - (OOM_bcs_phase + OOM_squeeze_canonical):+.4f} OOM")

# Does compound give MORE or LESS than sum?
if OOM_compound_total > OOM_bcs_phase + OOM_squeeze_canonical:
    nonlinear_direction = "LARGER (synergistic)"
elif OOM_compound_total < OOM_bcs_phase + OOM_squeeze_canonical:
    nonlinear_direction = "SMALLER (partially destructive)"
else:
    nonlinear_direction = "EQUAL (additive)"
print(f"  SU(1,1) nonlinearity: {nonlinear_direction}")


# =============================================================================
#  Section 9: A_s gap update
# =============================================================================

print(f"\n--- Section 9: A_s Gap Assessment ---")

# Current gap from S69: 0.485 OOM
A_s_gap_s69 = 0.485  # (local)
# Applied corrections from S69: 0.315 OOM (already counted)
A_s_applied_s69 = 0.315  # (local)

# The compound observable potentially changes the correction budget
# The separate corrections (0.043 + 0.226) were already partially counted in S69
# The compound effect is the REPLACEMENT, not an addition
print(f"  S69 gap:              {A_s_gap_s69:.3f} OOM")
print(f"  S69 applied:          {A_s_applied_s69:.3f} OOM")
print(f"  Compound correction:  {OOM_compound_total:+.4f} OOM")
print(f"  Previous separate:    {OOM_bcs_phase + OOM_squeeze_canonical:+.4f} OOM")
delta_from_compound = OOM_compound_total - (OOM_bcs_phase + OOM_squeeze_canonical)
print(f"  Net change from SU(1,1) nonlinearity: {delta_from_compound:+.4f} OOM")

# Updated gap
A_s_gap_updated = A_s_gap_s69 - delta_from_compound
print(f"  Updated A_s gap:      {A_s_gap_updated:.3f} OOM")


# =============================================================================
#  Section 10: Gate Verdict
# =============================================================================

print(f"\n{'=' * 72}")
print(f"GATE VERDICT: PHI-EFF-COMPOUND-70")
print(f"{'=' * 72}")

# The primary observable is cos(phi_compound) -- use CORRECTED (physical) value
# Pre-registered range: [-0.181, +0.800]
gate_observable = cos_phi_compound_corrected_w
gate_lo = -0.181  # (local)
gate_hi = +0.800

in_range = gate_lo <= gate_observable <= gate_hi

print(f"  Observable:  cos(phi_compound)_weighted = {gate_observable:+.6f}")
print(f"  Pre-reg range: [{gate_lo:+.3f}, {gate_hi:+.3f}]")
print(f"  In range:    {in_range}")

if in_range:
    gate_verdict = "INFO"
    gate_detail = (f"cos(phi_compound) = {gate_observable:+.4f} in "
                   f"[{gate_lo:+.3f}, {gate_hi:+.3f}]. "
                   f"r_compound_corrected = {r_compound_corrected_w:.4f}. "
                   f"delta_OOM = {OOM_compound_total:+.4f}. "
                   f"det = {decoherence_factor:.3f}. "
                   f"Nonlinear: {nonlinear_direction}.")
else:
    if gate_observable < gate_lo:
        gate_verdict = "ANOMALY"
        gate_detail = (f"cos(phi_compound) = {gate_observable:+.4f} BELOW range. "
                       f"More destructive than BCS alone.")
    else:
        gate_verdict = "ANOMALY"
        gate_detail = (f"cos(phi_compound) = {gate_observable:+.4f} ABOVE range. "
                       f"More constructive than spatial alone.")

print(f"  Verdict:     {gate_verdict}")
print(f"  Detail:      {gate_detail}")

# Summary table
print(f"\n--- Summary Table ---")
print(f"{'Observable':<40} {'Value':>12} {'Source':>15}")
print("-" * 70)
print(f"{'cos(phi_eff)_BCS (W1-A)':<40} {cos_phi_eff_bcs:>+12.4f} {'S69 PHI-EFF':>15}")
print(f"{'<cos(phi)>_spatial (W2-B)':<40} {cos_phi_spatial:>+12.4f} {'S69 SU11-PHASE':>15}")
print(f"{'cos(phi_compound)_corrected':<40} {cos_phi_compound_corrected_w:>+12.4f} {'THIS (W2-D)':>15}")
print(f"{'cos(phi_compound)_raw':<40} {cos_phi_compound_weighted:>+12.4f} {'THIS (raw)':>15}")
print(f"{'r_spatial':<40} {r_spatial:>12.4f} {'arctanh(C_vM)':>15}")
print(f"{'r_compound_corrected_weighted':<40} {r_compound_corrected_w:>12.4f} {'THIS':>15}")
print(f"{'r_compound_raw_weighted':<40} {r_compound_weighted:>12.4f} {'THIS (raw)':>15}")
print(f"{'OOM_compound_corrected':<40} {OOM_compound_total:>+12.4f} {'THIS':>15}")
print(f"{'OOM_compound_raw':<40} {OOM_compound_raw:>+12.4f} {'THIS (raw)':>15}")
print(f"{'OOM_separate_sum':<40} {OOM_bcs_phase + OOM_squeeze_canonical:>+12.4f} {'S69':>15}")
print(f"{'delta_OOM (nonlinear, corrected)':<40} {delta_from_compound:>+12.4f} {'THIS':>15}")
print(f"{'decoherence det':<40} {decoherence_factor:>12.4f} {'THIS':>15}")
print(f"{'A_s_gap (updated)':<40} {A_s_gap_updated:>12.3f} {'THIS':>15}")


# =============================================================================
#  Section 11: Save results
# =============================================================================

outfile = "computations/session-70/s70_phi_eff_compound.npz"
np.savez(
    outfile,
    # Gate
    gate_name="PHI-EFF-COMPOUND-70",
    gate_verdict=gate_verdict,
    gate_detail=gate_detail,
    # Primary observables (CORRECTED = physical)
    cos_phi_compound_corrected=cos_phi_compound_corrected_w,
    r_compound_corrected_weighted=r_compound_corrected_w,
    cosh2r_compound_corrected_weighted=cosh2r_compound_corrected_w,
    # Raw (uncorrected for det != 1)
    cos_phi_compound_raw=cos_phi_compound_weighted,
    cos_phi_compound_matrix=cos_phi_total,
    r_compound_raw_weighted=r_compound_weighted,
    r_total=r_total,
    phi_total=phi_total,
    cos_phi_total=cos_phi_total,
    # A_s corrections
    OOM_compound_corrected=OOM_compound_total,
    OOM_compound_raw=OOM_compound_raw,
    OOM_separate_sum=OOM_bcs_phase + OOM_squeeze_canonical,
    delta_OOM_nonlinear=delta_from_compound,
    A_s_gap_updated=A_s_gap_updated,
    nonlinear_direction=nonlinear_direction,
    # Decoherence
    decoherence_det=decoherence_factor,
    # Per-mode compound parameters (raw)
    labels=labels,
    r_k_bcs=r_k,
    phi_k_bcs=phi_k,
    r_compound=r_compound,
    phi_compound=phi_compound,
    cos_phi_compound_per_mode=np.cos(phi_compound),
    cosh2r_compound=cosh2r_compound,
    # Per-mode corrected
    r_compound_corrected=r_compound_corrected,
    phi_compound_corrected=phi_compound_corrected,
    cos_phi_compound_corrected_per_mode=np.cos(phi_compound_corrected),
    cosh2r_compound_corrected=cosh2r_compound_corrected,
    # Spatial parameters
    r_spatial=r_spatial,
    kappa_vM=kappa_vM,
    C_vM=C_vM,
    # Channel results
    channel_names=list(channel_r_compound.keys()),
    channel_r_compound=np.array(list(channel_r_compound.values())),
    channel_phi_compound=np.array(list(channel_phi_compound.values())),
    channel_cos_compound=np.array(list(channel_cos_compound.values())),
    channel_cosh2r=np.array(list(channel_cosh2r.values())),
    channel_OOM=np.array(list(channel_OOM.values())),
    # Mode weights
    mode_weights=mode_weights,
    # Inputs echoed
    cos_phi_eff_bcs=cos_phi_eff_bcs,
    cos_phi_spatial=cos_phi_spatial,
    r_eff_bcs=r_eff_bcs,
    r_eff_canonical=r_eff_canonical,
    OOM_canonical=OOM_canonical,
    # Monte Carlo verification
    r_compound_mc=r_compound_mc,
    phi_compound_mc=phi_compound_mc,
    alpha_compound=alpha_compound,
    beta_compound=beta_compound,
)

print(f"\nResults saved to: {outfile}")
print(f"\n{'=' * 72}")
print(f"PHI-EFF-COMPOUND-70: {gate_verdict}")
print(f"{'=' * 72}")
