"""Dump every entry from tools/knowledge-index.json into per-table markdown files.

One row per entry; one file per top-level table key. Complex (list/dict) values
are serialized as JSON strings so they survive the markdown-table row constraint.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
INDEX_PATH = ROOT / "knowledge-index.json"
OUT_DIR = ROOT / "kb-dumps"
OUT_DIR.mkdir(parents=True, exist_ok=True)

SKIP_KEYS = {"$schema", "generated"}


def md_escape(v) -> str:
    """Escape a value for safe inclusion in a markdown table cell."""
    if v is None:
        return ""
    if isinstance(v, (list, dict)):
        s = json.dumps(v, ensure_ascii=False, separators=(",", ":"))
    else:
        s = str(v)
    return (
        s.replace("\\", "\\\\")
        .replace("|", "\\|")
        .replace("\r", "")
        .replace("\n", "<br>")
    )


def main() -> None:
    with INDEX_PATH.open("r", encoding="utf-8") as f:
        idx = json.load(f)

    summary: list[tuple[str, int, int, int]] = []  # (name, rows, cols, bytes)

    for table_name, rows in idx.items():
        if table_name in SKIP_KEYS or not isinstance(rows, list):
            continue

        out = OUT_DIR / f"{table_name}.md"

        if not rows:
            out.write_text(f"# {table_name}\n\n(empty)\n", encoding="utf-8")
            summary.append((table_name, 0, 0, out.stat().st_size))
            continue

        # Collect column order: insertion-order union of keys across all dict rows.
        all_keys: list[str] = []
        seen: set[str] = set()
        for r in rows:
            if isinstance(r, dict):
                for k in r.keys():
                    if k not in seen:
                        seen.add(k)
                        all_keys.append(k)

        with out.open("w", encoding="utf-8") as f:
            f.write(f"# {table_name} ({len(rows):,} entries)\n\n")
            if all_keys:
                f.write("| " + " | ".join(all_keys) + " |\n")
                f.write("|" + "|".join(["---"] * len(all_keys)) + "|\n")
                for r in rows:
                    if isinstance(r, dict):
                        cells = [md_escape(r.get(k, "")) for k in all_keys]
                        f.write("| " + " | ".join(cells) + " |\n")
                    else:
                        # Non-dict row — single-cell.
                        f.write(f"| {md_escape(r)} |\n")
            else:
                # All rows are scalars.
                f.write("| value |\n|---|\n")
                for r in rows:
                    f.write(f"| {md_escape(r)} |\n")

        summary.append((table_name, len(rows), len(all_keys), out.stat().st_size))

    # Index README.
    readme = OUT_DIR / "README.md"
    with readme.open("w", encoding="utf-8") as f:
        f.write("# Knowledge Base Dumps\n\n")
        f.write(f"Source: `tools/knowledge-index.json`\n")
        f.write(f"Generated by: `tools/_dump_kb_to_markdown.py`\n\n")
        f.write("One row per entry, one markdown file per top-level table key. ")
        f.write("List/dict values are serialized as compact JSON strings.\n\n")
        f.write("| Table | Entries | Columns | Size | File |\n")
        f.write("|:------|--------:|--------:|-----:|:-----|\n")
        for name, n, cols, sz in sorted(summary, key=lambda x: -x[1]):
            sz_str = f"{sz / 1024 / 1024:.2f} MB" if sz >= 1024 * 1024 else f"{sz / 1024:.1f} KB"
            f.write(f"| {name} | {n:,} | {cols} | {sz_str} | `{name}.md` |\n")
        total_rows = sum(n for _, n, _, _ in summary)
        total_bytes = sum(sz for _, _, _, sz in summary)
        f.write(f"\n**Total**: {total_rows:,} rows across {len(summary)} tables ")
        f.write(f"({total_bytes / 1024 / 1024:.2f} MB).\n")

    print(f"Dumped {len(summary)} tables to {OUT_DIR}")
    print(f"{'Table':<25} {'Entries':>10} {'Cols':>6} {'Size':>12}")
    print("-" * 60)
    for name, n, cols, sz in sorted(summary, key=lambda x: -x[1]):
        sz_str = f"{sz / 1024 / 1024:.2f} MB" if sz >= 1024 * 1024 else f"{sz / 1024:.1f} KB"
        print(f"{name:<25} {n:>10,} {cols:>6} {sz_str:>12}")


if __name__ == "__main__":
    main()
