"""Dump the canonical-constants backfill worklist as a focused markdown file.

Reads tools/knowledge-index.json, filters the `constants` table to rows that
have no PROVENANCE entry (session is null), and writes a clean markdown table
to tools/kb-dumps/constants_backfill.md so the user can hand-fill provenance
records (session / source / gate) and then add them to the PROVENANCE dict in
computations/_shared/canonical_constants.py.

The full constants table is at tools/kb-dumps/constants.md (generated by
_dump_kb_to_markdown.py). This script is for the BACKFILL subset only.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
INDEX_PATH = ROOT / "knowledge-index.json"
OUT_PATH = ROOT / "kb-dumps" / "constants_backfill.md"


def _short_value(v) -> str:
    """Truncate long value representations for the markdown table cell."""
    s = "" if v is None else str(v)
    s = s.replace("|", "\\|").replace("\n", " ")
    if len(s) > 80:
        s = s[:77] + "..."
    return s


def main() -> None:
    with INDEX_PATH.open("r", encoding="utf-8") as f:
        idx = json.load(f)

    constants = idx.get("constants", [])
    backfill = [c for c in constants if isinstance(c, dict) and not c.get("session")]

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with OUT_PATH.open("w", encoding="utf-8") as f:
        f.write(f"# constants — backfill worklist ({len(backfill):,} of {len(constants):,} entries)\n\n")
        f.write(
            "Constants in `computations/_shared/canonical_constants.py` that "
            "currently have no PROVENANCE entry. Hand-fill the session/source/"
            "gate fields and append to the `PROVENANCE` dict in that file. "
            "After adding, re-run `tools/_build_constants_table.py --apply` (or "
            "`/weave --update` once Stage B lands) to refresh the table.\n\n"
        )
        f.write(
            "Schema: `session` (e.g., 'S82'), `source` (e.g., 'PDG 2024' or "
            "'sessions/.../wpaper.md §X'), `gate` (e.g., 'S82-XYZ' or null), "
            "`superseded` (bool, default false).\n\n"
        )
        f.write("| name | value | value_type | line | source_file |\n")
        f.write("|:-----|:------|:-----------|-----:|:------------|\n")
        for c in backfill:
            name = c.get("name", "")
            value = _short_value(c.get("value"))
            value_type = c.get("value_type", "")
            line = c.get("line", "")
            source_file = c.get("source_file", "")
            f.write(f"| `{name}` | `{value}` | {value_type} | {line} | {source_file} |\n")

    print(f"Wrote {len(backfill):,} backfill rows to {OUT_PATH}")
    print(f"({len(constants) - len(backfill):,} constants already have provenance — not listed)")


if __name__ == "__main__":
    main()
