#!/usr/bin/env python3
"""Generate sessions/framework/registry/orphan-content-watchlist.md from
the Phase 0.9 zero-coverage JSON.

Surfaces the 156 FORMAT-MISS "orphan-content" candidates — files that
match no recognized aggregator archetype and emit no attribution edge.
Each is a candidate for one of:
  (i)   genuine orphan content worth resurfacing
  (ii)  a one-off format the regex doesn't catch yet
  (iii) an unusual review/audit pattern

Sorted by size (largest first — biggest signal for orphan content).
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "tools" / "_format_generation_zero_coverage.json"
OUT = ROOT / "sessions" / "framework" / "registry" / "orphan-content-watchlist.md"


def main() -> None:
    with SRC.open("r", encoding="utf-8") as f:
        data = json.load(f)

    fm = [x for x in data["zero_files"] if x["category"] == "FORMAT-MISS"]
    aggregator_archetypes = ("master-collab", "master-synthesis",
                             "results-workingpaper", "wave")

    def is_aggregator(rec: dict) -> bool:
        n = rec["path"].split("/")[-1]
        return any(a in n for a in aggregator_archetypes)

    orphans = [r for r in fm if not is_aggregator(r)]
    aggregators = [r for r in fm if is_aggregator(r)]

    orphans.sort(key=lambda r: (-r["size"], r["sid"]))
    aggregators.sort(key=lambda r: (-r["size"], r["sid"]))

    md: list[str] = []
    md.append("---")
    md.append("type: orphan-watchlist")
    md.append("ingested-by: /weave --update")
    md.append("---")
    md.append("")
    md.append("# Orphan-content watchlist")
    md.append("")
    md.append("**Registry ID**: `orphan-content-watchlist`  ")
    md.append("**Owner agent(s)**: `orchestrator` (sole writer)  ")
    md.append("**Last updated**: 2026-05-17, Phase 0.9 / Task #9  ")
    md.append("**Source**: `tools/_format_generation_zero_coverage.json` "
              "(generated by `tools/_format_generation_zero_coverage.py`)  ")
    md.append("**Generator**: `tools/_emit_orphan_watchlist.py`")
    md.append("")
    md.append("---")
    md.append("")
    md.append("## Scope")
    md.append("")
    md.append("This registry lists session markdown files that emit ZERO "
              "attribution edges in the Phase 1 harvester run "
              "(`tools/harvest_attribution_edges.py`). These files are NOT "
              "system-scaffolding, NOT empty shells, NOT pre-G3 narrative — "
              "they are FORMAT-MISS files whose attribution my regex set "
              "fails to extract. Each is a candidate for one of three follow-up "
              "actions:")
    md.append("")
    md.append("- **(i) Resurface as orphan content** — a forgotten one-off, "
              "an early-era investigation index, a way-forward planning doc "
              "that contains substantive ideas not promoted to current registries.")
    md.append("- **(ii) Regex refinement** — a one-off format my regex set "
              "doesn't catch yet (e.g., `**Reviewer**:` was missed before S87 "
              "sampling surfaced it).")
    md.append("- **(iii) Unusual review/audit pattern** — multi-agent "
              "synthesis files (master-collab, audit chains) where attribution "
              "is implicit in the file structure rather than a header line.")
    md.append("")
    md.append(f"**File counts**:  ")
    md.append(f"- (B) Orphan-content candidates (this watchlist): "
              f"**{len(orphans)} files**, "
              f"{sum(r['size'] for r in orphans):,} bytes total  ")
    md.append(f"- (A) Master-aggregator pattern (design-correct, NOT this list): "
              f"{len(aggregators)} files  ")
    md.append("")
    md.append("---")
    md.append("")
    md.append("## How to use this list")
    md.append("")
    md.append("Each row below is a candidate for manual inspection in a separate "
              "session. The recommended workflow is:")
    md.append("")
    md.append("1. Read the file head (first 30-50 lines).")
    md.append("2. Determine which of the three candidate-classes (i/ii/iii) fits.")
    md.append("3. If (ii) regex-refinement: identify the missing pattern, add "
              "a fixture to `tools/_format_generation_regex_set.py::FIXTURES`, "
              "re-run self-test (must stay 18+/18+ PASS), re-run "
              "`tools/harvest_attribution_edges.py`. The "
              "edge-count delta tells you how many edges the new pattern unlocked.")
    md.append("4. If (i) orphan content: read the file in full, decide whether "
              "the ideas should be promoted to an existing registry (e.g., "
              "`evoi-framework.md`, falsifier-master-inventory, etc.) or marked "
              "as historically interesting only.")
    md.append("5. If (iii) unusual review/audit: emit explicit `authored_by` / "
              "`reviewed_by` edges via a new harvester pattern. The "
              "`master-collab` files in particular likely deserve "
              "`synthesized_by: file -> orchestrator` edges.")
    md.append("")
    md.append("After inspection, mark a row's `status` field in this table:")
    md.append("- `UNREVIEWED` (default; this watchlist's landing state)")
    md.append("- `ORPHAN-PROMOTED` (content moved to a target registry)")
    md.append("- `REGEX-FIXED` (pattern added; row no longer zero-coverage)")
    md.append("- `MULTI-AUTHOR` (file's authorship is implicit; emit synth edge)")
    md.append("- `HISTORICAL-ONLY` (interesting but no forward action)")
    md.append("")
    md.append("---")
    md.append("")
    md.append(f"## (B) Orphan-content candidates ({len(orphans)} files)")
    md.append("")
    md.append("Sorted by size (largest first — biggest signal for orphan content).")
    md.append("")
    md.append("| # | Status | Gen | Sess | File | Size | First header | Head preview |")
    md.append("|--:|:-------|:----|:-----|:-----|-----:|:-------------|:-------------|")
    for i, r in enumerate(orphans, start=1):
        hd = (r.get("first_header") or "").replace("|", "\\|")[:100]
        pv = (r.get("head_preview") or "").replace("|", "\\|")[:140]
        path_short = r["path"].split("/", 2)[-1] if r["path"].count("/") >= 2 else r["path"]
        md.append(f"| {i} | UNREVIEWED | {r['generation']} | S{r['sid']} | "
                  f"`{path_short}` | {r['size']:,} | {hd} | {pv} |")
    md.append("")
    md.append("---")
    md.append("")
    md.append(f"## (A) Master-aggregator pattern reference ({len(aggregators)} files)")
    md.append("")
    md.append("These files have NO attribution by design — authorship is "
              "offloaded to sister files (`session-N-{agent}-{topic}.md`). "
              "Listed here for reference, not for inspection.")
    md.append("")
    md.append("| Gen | Sess | File | Size | First header |")
    md.append("|:----|:-----|:-----|-----:|:-------------|")
    for r in aggregators:
        hd = (r.get("first_header") or "").replace("|", "\\|")[:100]
        path_short = r["path"].split("/", 2)[-1] if r["path"].count("/") >= 2 else r["path"]
        md.append(f"| {r['generation']} | S{r['sid']} | "
                  f"`{path_short}` | {r['size']:,} | {hd} |")
    md.append("")
    md.append("---")
    md.append("")
    md.append("## Cross-references")
    md.append("")
    md.append("- Format-generation spec: `sessions/framework/registry/session-format-generations.md`")
    md.append("- Regex module + self-test: `tools/_format_generation_regex_set.py`")
    md.append("- Phase 0.9 zero-coverage scan: `tools/_format_generation_zero_coverage.py`")
    md.append("- Phase 1 harvester: `tools/harvest_attribution_edges.py`")
    md.append("- Per-run audit log: `tools/harvest_attribution_edges.log`")
    md.append("- Per-run summary: `tools/harvest_attribution_edges.summary.json`")
    md.append("")
    md.append("## Change log")
    md.append("")
    md.append("| Date | Session | Change | Author |")
    md.append("|:-----|:--------|:-------|:-------|")
    md.append("| 2026-05-17 | Phase 0.9 / Task #9 | Initial landing — "
              "156 orphan candidates surfaced from full-corpus zero-coverage scan "
              "| orchestrator |")
    md.append("")

    OUT.write_text("\n".join(md), encoding="utf-8")
    print(f"Wrote {OUT} ({OUT.stat().st_size:,}B)")
    print(f"  Orphan candidates: {len(orphans)}")
    print(f"  Aggregator references: {len(aggregators)}")


if __name__ == "__main__":
    main()
