"""Harvest constant-usage edges from computation-archive Python scripts.

Walks computations/**/*.py, strips comments + docstrings, finds tokens
matching the canonical_constants vocabulary, and emits edges in the
[EDGE:depends_on] format consumed by the downstream pipeline.

Output: computations/_shared/archive_script_import_edges.txt

Discipline:
- Skip files matching ^_, canonical_constants.py, __init__.py
- Skip files with no vocab matches
- Edge source ID is the bare script filename (no path)
- Edges are deduplicated
"""

from __future__ import annotations

import importlib.util
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
# computation-archive content was integrated into computations/session-N/ and
# computations/_shared/ at Phase 5 cutover (2026-05-03). Repointed at the
# migrated location 2026-05-04: extract_entities.py never picked up the
# script→constant edges from the migrated scripts, so we walk computations/
# directly and re-emit the edge file the extractor consumes.
ARCHIVE = ROOT / "computations"
CANONICAL = ROOT / "computations" / "_shared" / "canonical_constants.py"
OUTPUT = ROOT / "computations" / "_shared" / "archive_script_import_edges.txt"


def load_vocab() -> set[str]:
    """Import canonical_constants.py and extract public identifier names.

    Filters out re-exported modules / functions / classes / built-ins so that
    names like `np`, `sys`, `warnings`, `warn_stale` do not pollute the
    constant vocabulary. Mirrors the filter pattern in harvest_archive_edges.py
    `load_canonical_names`. The unfiltered form leaks badly here because this
    is a source-text harvester (every `import numpy as np` line hits `np`).
    """
    import inspect
    import types
    spec = importlib.util.spec_from_file_location("canonical_constants", CANONICAL)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"could not load spec for {CANONICAL}")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    out: set[str] = set()
    for name in dir(mod):
        if name.startswith("_") or not name.isidentifier():
            continue
        obj = getattr(mod, name)
        if isinstance(obj, types.ModuleType):
            continue
        if (inspect.isfunction(obj) or inspect.isclass(obj)
                or inspect.isbuiltin(obj) or inspect.ismethod(obj)):
            continue
        out.add(name)
    return out


# Strip triple-quoted strings (docstrings + multi-line strings) and # comments.
_TRIPLE_RE = re.compile(r'("""|\'\'\')(?:.|\n)*?\1', re.MULTILINE)
_LINE_COMMENT_RE = re.compile(r"#.*?$", re.MULTILINE)
_SINGLE_QUOTED_RE = re.compile(r"'([^'\\\n]|\\.)*'")
_DOUBLE_QUOTED_RE = re.compile(r'"([^"\\\n]|\\.)*"')
_TOKEN_RE = re.compile(r"\b[A-Za-z_][A-Za-z0-9_]*\b")


def strip_source(src: str) -> str:
    """Remove docstrings, comments, and string literals so token search hits real identifiers."""
    src = _TRIPLE_RE.sub(" ", src)
    src = _LINE_COMMENT_RE.sub(" ", src)
    src = _SINGLE_QUOTED_RE.sub(" ", src)
    src = _DOUBLE_QUOTED_RE.sub(" ", src)
    return src


def is_skipped(path: Path) -> bool:
    name = path.name
    if name == "canonical_constants.py":
        return True
    if name == "__init__.py":
        return True
    if name.startswith("_"):
        return True
    return False


def main() -> int:
    vocab = load_vocab()
    print(f"[harvest] vocab size: {len(vocab)}", file=sys.stderr)

    if not ARCHIVE.is_dir():
        print(f"[harvest] ERROR: archive not found at {ARCHIVE}", file=sys.stderr)
        return 1

    edges: set[tuple[str, str]] = set()
    inbound_degree: dict[str, int] = {}
    scanned = 0
    errored: list[tuple[str, str]] = []

    for py in ARCHIVE.rglob("*.py"):
        if is_skipped(py):
            continue
        scanned += 1
        try:
            src = py.read_text(encoding="utf-8", errors="replace")
        except Exception as exc:  # noqa: BLE001
            errored.append((str(py), repr(exc)))
            continue
        try:
            stripped = strip_source(src)
            tokens = set(_TOKEN_RE.findall(stripped))
        except Exception as exc:  # noqa: BLE001
            errored.append((str(py), repr(exc)))
            continue

        hits = tokens & vocab
        if not hits:
            continue
        bare = py.name
        for c in hits:
            edge = (bare, c)
            if edge in edges:
                continue
            edges.add(edge)
            inbound_degree[c] = inbound_degree.get(c, 0) + 1

    # Write output.
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT.open("w", encoding="utf-8") as f:
        f.write("# archive_script_import_edges.txt\n")
        f.write(f"# Generated by tools/harvest_archive_script_import_edges.py\n")
        f.write(f"# Scanned {scanned} archive scripts; emitted {len(edges)} unique edges.\n")
        f.write("# Edge format: [EDGE:depends_on] data_provenance:<script>.py -> constants:<NAME>  # archive-script uses <NAME>\n")
        f.write("#\n")
        for bare, c in sorted(edges):
            f.write(
                f"[EDGE:depends_on] data_provenance:{bare} -> constants:{c}"
                f"  # archive-script uses {c}\n"
            )

    # Report.
    print(f"[harvest] scanned: {scanned}", file=sys.stderr)
    print(f"[harvest] unique edges: {len(edges)}", file=sys.stderr)
    top = sorted(inbound_degree.items(), key=lambda kv: (-kv[1], kv[0]))[:15]
    print("[harvest] top 15 constants by inbound degree:", file=sys.stderr)
    for name, deg in top:
        print(f"  {deg:>5d}  {name}", file=sys.stderr)
    print(f"[harvest] errored files: {len(errored)}", file=sys.stderr)
    for path, exc in errored[:25]:
        print(f"  ERROR  {path}  {exc}", file=sys.stderr)

    print(f"[harvest] wrote {OUTPUT}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
