r"""Harvest constant-usage edges from computations/_shared/s*.py scripts.

For each computation script, detect which canonical-constants names it imports or
references (via `from canonical_constants import *`) and emit one
`[EDGE:depends_on]` line per (script, constant) pair into
`computations/_shared/script_import_edges.txt`.

Discipline:
- Strip docstrings and `#` comments before scanning, so a constant mentioned
  only in prose does not produce an edge.
- Ignore helper/private modules (`_audit_*`, `canonical_constants.py`,
  `__init__.py`); script filename must match `^s\d+[a-z]?_`.
- Importing-but-unused still counts as a declared dependency.
"""

from __future__ import annotations

import re
import sys
import types
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
COMPUTATIONS = ROOT / "computations"
OUTFILE = COMPUTATIONS / "script_import_edges.txt"

# Load canonical-constants vocab. Filter out re-exported modules / functions
# / classes (e.g. numpy aliased as np, sys, warnings, helper functions like
# warn_stale) — those are not framework constants.
sys.path.insert(0, str(COMPUTATIONS))
import canonical_constants as CC  # noqa: E402

_CALLABLE_OR_MODULE = (
    types.ModuleType,
    types.FunctionType,
    types.BuiltinFunctionType,
    type,
)
VOCAB = {
    n
    for n in dir(CC)
    if not n.startswith("_")
    and n.isidentifier()
    and not isinstance(getattr(CC, n), _CALLABLE_OR_MODULE)
}

SCRIPT_NAME_RE = re.compile(r"^s\d+[a-z]?_")
TOKEN_RE = re.compile(r"\b[A-Za-z_]\w*\b")


def strip_strings_and_comments(src: str) -> str:
    """Remove triple-quoted strings, single-line strings, and # comments.

    Conservative: replaces them with spaces so line/column structure roughly
    survives but their textual contents are gone.
    """
    # Triple-quoted strings (greedy-safe, non-greedy body).
    src = re.sub(r'"""[\s\S]*?"""', " ", src)
    src = re.sub(r"'''[\s\S]*?'''", " ", src)
    # Single-line strings ('..' and "..") — handle escapes minimally.
    src = re.sub(r'"(?:\\.|[^"\\\n])*"', " ", src)
    src = re.sub(r"'(?:\\.|[^'\\\n])*'", " ", src)
    # `#` comments to end-of-line.
    src = re.sub(r"#[^\n]*", " ", src)
    return src


# Match `from canonical_constants import ...` allowing parens + multi-line.
IMPORT_RE = re.compile(
    r"from\s+canonical_constants\s+import\s+(\*|\([\s\S]*?\)|[^\n;()]+)",
    re.MULTILINE,
)


def parse_imports(clean_src: str) -> tuple[set[str], bool]:
    """Return (explicit_names, has_star_import)."""
    names: set[str] = set()
    has_star = False
    for m in IMPORT_RE.finditer(clean_src):
        body = m.group(1).strip()
        if body == "*":
            has_star = True
            continue
        # Strip surrounding parens.
        if body.startswith("(") and body.endswith(")"):
            body = body[1:-1]
        # Split on commas, then strip "as" aliases — we want the source name.
        for piece in body.split(","):
            piece = piece.strip()
            if not piece:
                continue
            # Handle `Name as Alias` — keep the source name (canonical side).
            piece = re.split(r"\s+as\s+", piece, maxsplit=1)[0].strip()
            if piece.isidentifier():
                names.add(piece)
    return names, has_star


def harvest_script(path: Path) -> set[str]:
    """Return the set of canonical-constant names this script depends on."""
    raw = path.read_text(encoding="utf-8", errors="replace")
    clean = strip_strings_and_comments(raw)

    explicit, has_star = parse_imports(clean)
    found = {n for n in explicit if n in VOCAB}

    if has_star:
        # Scan body tokens; anything in vocab is a referenced constant.
        for tok in TOKEN_RE.findall(clean):
            if tok in VOCAB:
                found.add(tok)
    return found


def main() -> int:
    scripts = sorted(COMPUTATIONS.glob("s*.py"))
    edges: dict[str, set[str]] = defaultdict(set)
    errors: list[tuple[str, str]] = []
    inbound: Counter[str] = Counter()
    scanned = 0
    skipped_name = 0

    for path in scripts:
        name = path.name
        if not SCRIPT_NAME_RE.match(name):
            skipped_name += 1
            continue
        if name == "canonical_constants.py" or name == "__init__.py":
            continue
        try:
            consts = harvest_script(path)
        except Exception as exc:  # pragma: no cover - reported below
            errors.append((name, f"{type(exc).__name__}: {exc}"))
            continue
        scanned += 1
        for c in consts:
            edges[name].add(c)
            inbound[c] += 1

    # Emit.
    lines = [
        "## Script Constant-Import Edges",
        "## Generated by tools/harvest_script_import_edges.py",
        "## Source: computations/_shared/s*.py imports of canonical_constants",
        "## Edge type: data_provenance -> constants (depends_on)",
        "",
    ]
    total_edges = 0
    for script in sorted(edges):
        for const in sorted(edges[script]):
            lines.append(
                f"[EDGE:depends_on] data_provenance:{script} "
                f"-> constants:{const}  # script imports {const}"
            )
            total_edges += 1

    OUTFILE.write_text("\n".join(lines) + "\n", encoding="utf-8")

    # Report.
    print(f"scripts scanned : {scanned}")
    print(f"scripts skipped (name pattern) : {skipped_name}")
    print(f"unique edges emitted : {total_edges}")
    print(f"output : {OUTFILE.relative_to(ROOT)}")
    print()
    print("Top 15 constants by inbound degree:")
    for const, count in inbound.most_common(15):
        print(f"  {count:4d}  {const}")
    print()
    if errors:
        print(f"Parse errors ({len(errors)}):")
        for name, err in errors:
            print(f"  {name} : {err}")
    else:
        print("Parse errors: none")
    return 0


if __name__ == "__main__":
    sys.exit(main())
