#!/usr/bin/env python3
"""
Harvest constants -> sessions edges from PROVENANCE inline comments in
`computations/_shared/canonical_constants.py`.

Pattern matched: any assignment of the form

    NAME = <value>  # ... S{NN} ...

emits an edge `[EDGE:derived_from] constants:NAME -> sessions:NN`.

Edge type rationale: `derived_from` is one of the 13 typed edges in the
schema (per the prior session's REAL_EDGES inventory). Semantically:
"constant NAME was set / derived in session NN."

Why this exists: the archive harvester only emits gates -> constants edges
when a constant name appears in a verdict-row cell. Many constants do not
appear in tables at all -- their canonical value comes from a script
output that landed in canonical_constants.py with a session-tagged
comment. Mining those comments gives every named constant at least one
provenance edge to its set-session.

Output: `computations/_shared/canonical_constants_provenance_edges.txt`
(single file; not per-session, since the source is one file).

Gate ID for this tool: PROVENANCE-EDGE-HARVEST (NON-PHONONIC, infrastructure).
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
COMPUTATIONS_DIR = PROJECT_ROOT / "computations"
CC_PATH = COMPUTATIONS_DIR / "_shared" / "canonical_constants.py"
OUT_PATH = COMPUTATIONS_DIR / "canonical_constants_provenance_edges.txt"

# Match an assignment line with an inline comment.
RE_ASSIGN_COMMENT = re.compile(
    r"^([A-Za-z_]\w*)\s*=.+?#(.+)$",
    re.MULTILINE,
)
# Session refs: S<num> or S<num><lower-letter> or "session NN"
RE_SESS = re.compile(r"\bS(\d+)[a-z]?\b|\bsession[- ](\d+)", re.IGNORECASE)


def load_canonical_names() -> set[str]:
    """Mirror harvest_archive_edges.py.load_canonical_names — including
    the module/function/class filter that prevents `np`, `sys`,
    `warnings`, `warn_stale` from leaking into the vocab."""
    import inspect
    import types
    sys.path.insert(0, str(COMPUTATIONS_DIR / "_shared"))
    try:
        import canonical_constants as CC  # noqa: WPS433
    except Exception:
        return set()
    out: set[str] = set()
    for name in dir(CC):
        if name.startswith("_") or not name.isidentifier():
            continue
        obj = getattr(CC, name)
        if isinstance(obj, types.ModuleType):
            continue
        if (inspect.isfunction(obj) or inspect.isclass(obj)
                or inspect.isbuiltin(obj) or inspect.ismethod(obj)):
            continue
        out.add(name)
    return out


def harvest() -> list[tuple[str, str, str]]:
    """Return list of (constant_name, session_id, comment_excerpt)."""
    if not CC_PATH.exists():
        return []
    text = CC_PATH.read_text(encoding="utf-8", errors="replace")
    canonical_names = load_canonical_names()
    seen: set[tuple[str, str]] = set()
    edges: list[tuple[str, str, str]] = []
    for m in RE_ASSIGN_COMMENT.finditer(text):
        name = m.group(1)
        comment = m.group(2).strip()
        if name not in canonical_names:
            continue
        for sm in RE_SESS.finditer(comment):
            sess = sm.group(1) or sm.group(2)
            key = (name, sess)
            if key in seen:
                continue
            seen.add(key)
            edges.append((name, sess, comment[:120]))
    return edges


HEADER = (
    "## Canonical Constants Provenance Edges\n"
    "## Generated by tools/harvest_provenance_edges.py\n"
    "## Source: computations/_shared/canonical_constants.py inline comments\n"
    "## Edge type: constants -> sessions (derived_from)\n"
    "\n"
)


def main() -> int:
    edges = harvest()
    if not edges:
        print("No provenance edges harvested.")
        return 0
    lines = [HEADER]
    for name, sess, comment in edges:
        lines.append(
            f"[EDGE:derived_from] constants:{name} -> sessions:{sess}  "
            f"# provenance: {comment}\n"
        )
    OUT_PATH.write_text("".join(lines), encoding="utf-8")
    distinct_constants = len({n for n, _, _ in edges})
    distinct_sessions = len({s for _, s, _ in edges})
    print(
        f"Wrote {OUT_PATH.relative_to(PROJECT_ROOT)}: {len(edges)} edges "
        f"({distinct_constants} constants -> {distinct_sessions} sessions)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
