"""
PHASE 2b: EXPLICIT A_F EXTRACTION FROM R_{u(2)} COMMUTANT
===========================================================

This script extracts Connes' finite algebra A_F = C + H + M_3(C) from the
128-dimensional J-compatible commutant of R_{u(2)} computed in Phase 2a.

STRATEGY (REVISED after two failed approaches)
===============================================
Approach 1 (linear): Find {a : [a, b^o]=0 for all b in commutant} = CENTER (dim 5). Too small.
Approach 2 (per-factor): o-map mixes Wedderburn factors. Cannot decompose per-factor.

CORRECT APPROACH: Start from KNOWN generators and compute algebraic closure.

The L_{su(3)} generators (8 elements, anti-Hermitian) are in the R_{u(2)} commutant
and are J-compatible. Their algebraic closure in End(C^32) generates an algebra
that should contain M_3(C) (since L acts as the fundamental 3-rep on color indices).

Additionally, the H quaternion generators {1, e_1, e_2, e_3} act on the weak
doublet structure and commute with R_{u(2)}.

We construct A_F by:
1. Compute the algebra generated by L_{su(3)} within the commutant
2. Compute the algebra generated by H-operators within the commutant
3. Add the lepton number operator for the C factor
4. Assemble and test order-zero

The key insight from the failed approaches: the order-zero condition is
SELF-REFERENTIAL (only within A_F), so we must CONSTRUCT A_F first,
then VERIFY order-zero, rather than trying to extract it from the commutant
by imposing order-zero globally.

Author: KK Theorist Agent (phonon-exflation project, Session 10)
Date: 2026-02-12
"""

import numpy as np
from scipy.linalg import null_space, orth
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from branching_computation import (
    gell_mann_matrices, su3_basis, u2_basis_in_su3,
    L_action_matrix, R_action_matrix, LR_action_matrix,
)

np.set_printoptions(precision=8, linewidth=130, suppress=True)

# =============================================================================
# INFRASTRUCTURE FROM PHASE 2a
# =============================================================================

particle_names_plus = [
    'nu_R', 'u_R^r', 'u_R^g', 'u_R^b',
    'e_R^-', 'nu_L', 'e_L^-',
    'd_R^r', 'd_R^g', 'd_R^b',
    'u_L^r', 'u_L^g', 'u_L^b',
    'd_L^r', 'd_L^g', 'd_L^b',
]
particle_names = particle_names_plus + ['anti_' + p for p in particle_names_plus]

def get_column_index(flat_idx):
    if flat_idx == 0: return 0
    elif 1 <= flat_idx <= 3: return flat_idx
    elif 4 <= flat_idx <= 6: return 0
    else: return (flat_idx - 7) % 3 + 1

gamma5_diag = np.array([1.0, 1.0, -1.0, -1.0])
G5_signs = np.array([-gamma5_diag[get_column_index(k)] for k in range(16)])
G5 = np.diag(G5_signs)

Xi = np.zeros((32, 32))
Xi[:16, 16:] = -G5
Xi[16:, :16] = -G5

gamma_F = np.zeros((32, 32))
gamma_F[:16, :16] = np.eye(16)
gamma_F[16:, 16:] = -np.eye(16)

def rho_minus(rho_plus_v):
    return G5 @ np.conj(rho_plus_v) @ G5

def build_full_32(gens_16):
    gens_32 = []
    for g16 in gens_16:
        g32 = np.zeros((32, 32), dtype=complex)
        g32[:16, :16] = g16
        g32[16:, 16:] = rho_minus(g16)
        gens_32.append(g32)
    return gens_32

n = 32
basis_u2 = u2_basis_in_su3()
basis_su3 = su3_basis()

# =============================================================================
# PART 0: COMPUTE R_{u(2)} COMMUTANT (compact version)
# =============================================================================

print("=" * 72)
print("PHASE 2b: A_F EXTRACTION VIA GENERATOR CLOSURE + ORDER-ZERO TEST")
print("=" * 72)

print("\n[PART 0] Computing R_{u(2)} J-compatible commutant...")

R_u2_gens_16 = [R_action_matrix(v) for v in basis_u2]
R_u2_gens_32 = build_full_32(R_u2_gens_16)

constraint_blocks = []
for rv in R_u2_gens_32:
    block = np.zeros((n * n, n * n), dtype=complex)
    for i in range(n):
        for j in range(n):
            row = i * n + j
            for k in range(n):
                block[row, i * n + k] += rv[k, j]
                block[row, k * n + j] -= rv[i, k]
    constraint_blocks.append(block)

A_constraint = np.vstack(constraint_blocks)
ns_gauge = null_space(A_constraint, rcond=1e-10)
d_gauge = ns_gauge.shape[1]
comm_basis_raw = [ns_gauge[:, k].reshape(n, n) for k in range(d_gauge)]

d = d_gauge
A_mats = [(comm_basis_raw[k] @ Xi - Xi @ np.conj(comm_basis_raw[k])).flatten() for k in range(d)]
B_mats = [(comm_basis_raw[k] @ Xi + Xi @ np.conj(comm_basis_raw[k])).flatten() for k in range(d)]

C_mat = np.zeros((2 * n * n, 2 * d))
for m in range(n * n):
    for k in range(d):
        C_mat[2 * m, k] = A_mats[k][m].real
        C_mat[2 * m, d + k] = -B_mats[k][m].imag
        C_mat[2 * m + 1, k] = A_mats[k][m].imag
        C_mat[2 * m + 1, d + k] = B_mats[k][m].real

ns_J = null_space(C_mat, rcond=1e-10)
J_null_dim = ns_J.shape[1]
Jbasis_raw = [sum((ns_J[k, idx] + 1j * ns_J[d + k, idx]) * comm_basis_raw[k]
                   for k in range(d)) for idx in range(J_null_dim)]

real_vecs = [np.concatenate([T.flatten().real, T.flatten().imag]) for T in Jbasis_raw]
V_mat = np.column_stack(real_vecs)
Q_comm = orth(V_mat)
d_orth = Q_comm.shape[1]
n_flat = n * n
orth_basis = [(Q_comm[:, k][:n_flat] + 1j * Q_comm[:, k][n_flat:]).reshape(n, n) for k in range(d_orth)]

print(f"  R_u(2) J-compatible commutant: dim = {d_orth}")


# =============================================================================
# PART 1: L_{su(3)} GENERATORS AND THEIR ALGEBRAIC CLOSURE
# =============================================================================

print("\n" + "=" * 72)
print("[PART 1] L_{su(3)} algebraic closure within the commutant")
print("=" * 72)

L_su3_gens_16 = [L_action_matrix(v) for v in basis_su3]
L_su3_gens_32 = build_full_32(L_su3_gens_16)

# Verify L is in commutant
max_L_resid = 0
for L_g in L_su3_gens_32:
    pv = np.concatenate([L_g.flatten().real, L_g.flatten().imag])
    coeffs = Q_comm.T @ pv
    resid = np.linalg.norm(pv - Q_comm @ coeffs)
    max_L_resid = max(max_L_resid, resid)
print(f"  L generators in commutant: max residual = {max_L_resid:.2e} (PASS)")

# Compute algebraic closure of L_{su(3)}:
# Start with {L_1,...,L_8}, add products L_i*L_j, keep only independent ones,
# continue until no new elements.

def algebraic_closure_in_space(generators, Q_space, max_iter=5, tol=1e-8):
    """
    Compute the algebraic closure of generators within a vector space.

    generators: list of n x n matrices
    Q_space: orthonormal basis for the ambient space (real representation)

    Returns: orthonormal basis Q for the closure, and the basis matrices.
    """
    n_dim = generators[0].shape[0]
    n_flat = n_dim * n_dim

    # Start with generators
    current = list(generators)
    current_vecs = [np.concatenate([T.flatten().real, T.flatten().imag]) for T in current]
    Q_cur = orth(np.column_stack(current_vecs))
    d_cur = Q_cur.shape[1]

    for iteration in range(max_iter):
        # Generate products of existing basis with generators
        cur_basis = [(Q_cur[:, k][:n_flat] + 1j * Q_cur[:, k][n_flat:]).reshape(n_dim, n_dim)
                     for k in range(d_cur)]

        new_vecs = []
        for T1 in cur_basis:
            for T2 in generators:
                prod = T1 @ T2
                # Project out existing space
                pv = np.concatenate([prod.flatten().real, prod.flatten().imag])
                # Check if in ambient space
                coeffs_amb = Q_space.T @ pv
                resid_amb = np.linalg.norm(pv - Q_space @ coeffs_amb)
                if resid_amb > 0.1:
                    continue  # product left the commutant
                # Project to ambient space
                pv_proj = Q_space @ coeffs_amb
                # Check if new w.r.t. current basis
                coeffs_cur = Q_cur.T @ pv_proj
                resid = np.linalg.norm(pv_proj - Q_cur @ coeffs_cur)
                if resid > tol:
                    new_vecs.append(pv_proj)

        if not new_vecs:
            break

        # Add new vectors
        all_vecs = np.column_stack([Q_cur] + [np.column_stack(new_vecs)])
        Q_new = orth(all_vecs)
        d_new = Q_new.shape[1]

        if d_new == d_cur:
            break

        print(f"    Iteration {iteration+1}: dim {d_cur} -> {d_new} (+{d_new - d_cur})")
        Q_cur = Q_new
        d_cur = d_new

    basis_mats = [(Q_cur[:, k][:n_flat] + 1j * Q_cur[:, k][n_flat:]).reshape(n_dim, n_dim)
                  for k in range(d_cur)]
    return Q_cur, basis_mats, d_cur


# Also add the identity (it's in the commutant and in any algebra)
identity_32 = np.eye(32, dtype=complex)
L_gens_plus_id = L_su3_gens_32 + [identity_32]

print("  Computing algebraic closure of L_{su(3)} + I...")
Q_L_closure, L_closure_basis, d_L_closure = algebraic_closure_in_space(
    L_gens_plus_id, Q_comm)
print(f"  L_su(3) closure: dim = {d_L_closure}")

# Verify closure
max_L_closure = 0
for i in range(d_L_closure):
    for j in range(d_L_closure):
        prod = L_closure_basis[i] @ L_closure_basis[j]
        pv = np.concatenate([prod.flatten().real, prod.flatten().imag])
        coeffs = Q_L_closure.T @ pv
        resid = np.linalg.norm(pv - Q_L_closure @ coeffs)
        max_L_closure = max(max_L_closure, resid)
print(f"  Closure check: max residual = {max_L_closure:.2e}")


# =============================================================================
# PART 2: H QUATERNION GENERATORS
# =============================================================================

print("\n" + "=" * 72)
print("[PART 2] Quaternion algebra (weak isospin) generators")
print("=" * 72)

# The H generators act on the weak doublet structure:
# Left-handed doublets: (nu_L=5, e_L=6), (u_L^c=10+c, d_L^c=13+c) for c=0,1,2
# Right-handed: e_1 = i*sigma_3 action, e_2 = i*sigma_2, e_3 = i*sigma_1

# Build on Psi_+ then extend via J-compatibility

LH_DOUBLETS = [(5, 6), (10, 13), (11, 14), (12, 15)]
RH_UP = [0, 1, 2, 3]    # nu_R, u_R^r, u_R^g, u_R^b
RH_DOWN = [4, 7, 8, 9]  # e_R, d_R^r, d_R^g, d_R^b

def make_H_gen(label):
    """
    Build 32x32 quaternion generator.
    label: '1', 'i', 'j', 'k'
    """
    T_plus = np.zeros((16, 16), dtype=complex)

    if label == '1':
        T_plus = np.eye(16, dtype=complex)
    elif label == 'i':
        # diag(i,-i) on doublets, i on RH-up, -i on RH-down
        for idx in RH_UP: T_plus[idx, idx] = 1j
        for idx in RH_DOWN: T_plus[idx, idx] = -1j
        for (up, dn) in LH_DOUBLETS:
            T_plus[up, up] = 1j
            T_plus[dn, dn] = -1j
    elif label == 'j':
        # ((0,1),(-1,0)) on doublets, 0 on RH
        for (up, dn) in LH_DOUBLETS:
            T_plus[up, dn] = 1.0
            T_plus[dn, up] = -1.0
    elif label == 'k':
        # ((0,i),(i,0)) on doublets, 0 on RH
        for (up, dn) in LH_DOUBLETS:
            T_plus[up, dn] = 1j
            T_plus[dn, up] = 1j

    T = np.zeros((32, 32), dtype=complex)
    T[:16, :16] = T_plus
    T[16:, 16:] = G5 @ np.conj(T_plus) @ G5
    return T

H_1 = make_H_gen('1')  # = identity
H_i = make_H_gen('i')
H_j = make_H_gen('j')
H_k = make_H_gen('k')

H_gens = [H_1, H_i, H_j, H_k]
H_names = ['1', 'i', 'j', 'k']

# Verify quaternion relations
print("  Quaternion relations on full C^32:")
relations = [
    ('i*i', H_i, H_i, -H_1),
    ('j*j', H_j, H_j, -H_1),
    ('k*k', H_k, H_k, -H_1),
    ('i*j', H_i, H_j, H_k),
    ('j*k', H_j, H_k, H_i),
    ('k*i', H_k, H_i, H_j),
]
quat_pass = True
for name, A, B, C_expected in relations:
    prod = A @ B
    err = np.max(np.abs(prod - C_expected))
    status = 'PASS' if err < 1e-10 else 'FAIL'
    print(f"    {name} = expected: {status} (err={err:.2e})")
    if err > 1e-10: quat_pass = False

# Verify in commutant
max_HR = max(np.max(np.abs(T @ R_g - R_g @ T))
             for T in H_gens for R_g in R_u2_gens_32)
print(f"  [H, R_u(2)]: max error = {max_HR:.2e}")

max_HJ = max(np.max(np.abs(T @ Xi - Xi @ np.conj(T))) for T in H_gens)
print(f"  H J-compat: max error = {max_HJ:.2e}")

max_H_resid = 0
for T in H_gens:
    pv = np.concatenate([T.flatten().real, T.flatten().imag])
    coeffs = Q_comm.T @ pv
    resid = np.linalg.norm(pv - Q_comm @ coeffs)
    max_H_resid = max(max_H_resid, resid)
print(f"  H in commutant: max residual = {max_H_resid:.2e} "
      f"({'PASS' if max_H_resid < 1e-8 else 'FAIL'})")


# =============================================================================
# PART 3: ALGEBRAIC CLOSURE OF L_{su(3)} x H GENERATORS
# =============================================================================

print("\n" + "=" * 72)
print("[PART 3] Algebraic closure of L_{su(3)} x H")
print("=" * 72)

# Key idea: A_F = C + H + M_3(C) where:
# - M_3(C) is generated by L_{su(3)} (via products -> full matrix algebra on colors)
# - H is generated by {e_1, e_2, e_3} (quaternions on doublet structure)
# - C is the center restricted to the lepton sector
#
# Since L and H act on "different indices" (color vs weak isospin), their
# products L_i * H_j should span the tensor product representation.

# Combine all generators:
all_generators = L_su3_gens_32 + [H_i, H_j, H_k, identity_32]

print(f"  Starting generators: {len(all_generators)} "
      f"(8 L_su(3) + 3 H + identity)")
print("  Computing algebraic closure...")
Q_AF_closure, AF_closure_basis, d_AF = algebraic_closure_in_space(
    all_generators, Q_comm, max_iter=10)
print(f"  Total closure dimension: {d_AF} (A_F target: 24)")

# Verify closure
max_AF_closure = 0
for i in range(min(d_AF, 30)):
    for j in range(min(d_AF, 30)):
        prod = AF_closure_basis[i] @ AF_closure_basis[j]
        pv = np.concatenate([prod.flatten().real, prod.flatten().imag])
        coeffs = Q_AF_closure.T @ pv
        resid = np.linalg.norm(pv - Q_AF_closure @ coeffs)
        max_AF_closure = max(max_AF_closure, resid)
print(f"  Closure: max residual = {max_AF_closure:.2e}")


# =============================================================================
# PART 4: ORDER-ZERO TEST ON THE CLOSURE
# =============================================================================

print("\n" + "=" * 72)
print("[PART 4] Order-zero test on the closure algebra")
print("=" * 72)

# Test [a, Xi @ b^T @ Xi] = 0 for ALL pairs a, b in the closure
max_o0 = 0
o0_violations = 0
total_pairs = d_AF * d_AF

print(f"  Testing {total_pairs} pairs...")
for i in range(d_AF):
    for j in range(d_AF):
        a = AF_closure_basis[i]
        b_opp = Xi @ AF_closure_basis[j].T @ Xi
        comm = a @ b_opp - b_opp @ a
        err = np.max(np.abs(comm))
        max_o0 = max(max_o0, err)
        if err > 1e-6:
            o0_violations += 1

print(f"  Max |[a, Xi b^T Xi]|: {max_o0:.2e}")
print(f"  Violations: {o0_violations} / {total_pairs}")
print(f"  Order-zero: {'PASS' if max_o0 < 1e-6 else 'VIOLATED'}")

# If violated, test individual generator types
if max_o0 > 1e-6:
    print("\n  Detailed order-zero by generator type:")

    # L x L
    max_LL = 0
    for i in range(8):
        for j in range(8):
            a = L_su3_gens_32[i]
            b_opp = Xi @ L_su3_gens_32[j].T @ Xi
            comm = a @ b_opp - b_opp @ a
            max_LL = max(max_LL, np.max(np.abs(comm)))
    print(f"    [L_i, o(L_j)]: max = {max_LL:.2e}")

    # H x H
    max_HH = 0
    for i in range(4):
        for j in range(4):
            a = H_gens[i]
            b_opp = Xi @ H_gens[j].T @ Xi
            comm = a @ b_opp - b_opp @ a
            max_HH = max(max_HH, np.max(np.abs(comm)))
    print(f"    [H_i, o(H_j)]: max = {max_HH:.2e}")

    # L x H
    max_LH = 0
    for i in range(8):
        for j in range(4):
            a = L_su3_gens_32[i]
            b_opp = Xi @ H_gens[j].T @ Xi
            comm = a @ b_opp - b_opp @ a
            max_LH = max(max_LH, np.max(np.abs(comm)))
    print(f"    [L_i, o(H_j)]: max = {max_LH:.2e}")

    # H x L
    max_HL = 0
    for i in range(4):
        for j in range(8):
            a = H_gens[i]
            b_opp = Xi @ L_su3_gens_32[j].T @ Xi
            comm = a @ b_opp - b_opp @ a
            max_HL = max(max_HL, np.max(np.abs(comm)))
    print(f"    [H_i, o(L_j)]: max = {max_HL:.2e}")

    # What does the o-map do to L and H generators?
    print("\n  o-map images of L generators:")
    for i in range(8):
        L_opp = Xi @ L_su3_gens_32[i].T @ Xi
        # Project onto L-generators
        L_coeffs = np.zeros(8)
        for j in range(8):
            L_coeffs[j] = np.trace(L_opp @ L_su3_gens_32[j].conj().T).real / \
                           np.trace(L_su3_gens_32[j] @ L_su3_gens_32[j].conj().T).real
        resid_L = L_opp - sum(L_coeffs[j] * L_su3_gens_32[j] for j in range(8))
        print(f"    o(L_{i+1}): L-coeffs norm={np.linalg.norm(L_coeffs):.4f}, "
              f"residual={np.max(np.abs(resid_L)):.4f}")

    print("\n  o-map images of H generators:")
    for i in range(4):
        H_opp = Xi @ H_gens[i].T @ Xi
        H_coeffs = np.zeros(4)
        for j in range(4):
            nrm = np.trace(H_gens[j] @ H_gens[j].conj().T).real
            if nrm > 1e-10:
                H_coeffs[j] = np.trace(H_opp @ H_gens[j].conj().T).real / nrm
        resid_H = H_opp - sum(H_coeffs[j] * H_gens[j] for j in range(4))
        print(f"    o(H_{H_names[i]}): H-coeffs={np.round(H_coeffs, 4)}, "
              f"residual={np.max(np.abs(resid_H)):.4f}")


# =============================================================================
# PART 4b: WEDDERBURN DECOMPOSITION AND CROSS-FACTOR ORDER-ZERO
# =============================================================================

print("\n" + "=" * 72)
print("[PART 4b] Wedderburn decomposition of 40-dim closure")
print("=" * 72)

# Compute o-map matrix and structure constants on the closure
O_map = np.zeros((d_AF, d_AF))
for i in range(d_AF):
    T_opp = Xi @ AF_closure_basis[i].T @ Xi
    pv = np.concatenate([T_opp.flatten().real, T_opp.flatten().imag])
    O_map[:, i] = Q_AF_closure.T @ pv

struct_const = np.zeros((d_AF, d_AF, d_AF))
for i in range(d_AF):
    for j in range(d_AF):
        prod = AF_closure_basis[i] @ AF_closure_basis[j]
        pv = np.concatenate([prod.flatten().real, prod.flatten().imag])
        struct_const[i, j, :] = Q_AF_closure.T @ pv

# Verify o-stability
max_o_leak = max(np.linalg.norm(
    np.concatenate([(Xi @ AF_closure_basis[i].T @ Xi).flatten().real,
                     (Xi @ AF_closure_basis[i].T @ Xi).flatten().imag])
    - Q_AF_closure @ O_map[:, i]) for i in range(d_AF))
print(f"  o-map stable on closure: {max_o_leak:.2e}")
print(f"  o^2 = I: {np.max(np.abs(O_map @ O_map - np.eye(d_AF))):.2e}")

# Center computation
comm_sc = struct_const - struct_const.transpose(1, 0, 2)
center_rows = []
for j in range(d_AF):
    for k in range(d_AF):
        center_rows.append(comm_sc[:, j, k])
center_mat = np.array(center_rows)
center_ns = null_space(center_mat, rcond=1e-8)
center_dim = center_ns.shape[1]
print(f"  Center dimension: {center_dim}")

# Wedderburn decomposition via random center element
center_basis_mats = [sum(center_ns[i, idx] * AF_closure_basis[i]
                         for i in range(d_AF))
                     for idx in range(center_dim)]

np.random.seed(42)
rc = np.random.randn(center_dim)
gc = sum(c * T for c, T in zip(rc, center_basis_mats))
evals_gc, evecs_gc = np.linalg.eig(gc)

tol_wd = 1e-3
used_wd = np.zeros(n, dtype=bool)
wd_factors = []
for i in range(n):
    if used_wd[i]:
        continue
    ev = evals_gc[i]
    close = np.abs(evals_gc - ev) < tol_wd
    close_conj = np.abs(evals_gc - np.conj(ev)) < tol_wd
    idx_set = np.where(close | close_conj)[0]
    for idx in idx_set:
        used_wd[idx] = True
    V_ev = evecs_gc[:, idx_set]
    wd_factors.append({'ev': ev, 'dim_V': len(idx_set), 'V': V_ev})

# For each factor: compute restriction of algebra and its rank
for f_idx, f in enumerate(wd_factors):
    V = f['V']
    proj_vecs = [np.concatenate([(V.conj().T @ T @ V).flatten().real,
                                  (V.conj().T @ T @ V).flatten().imag])
                 for T in AF_closure_basis]
    P = np.column_stack(proj_vecs)
    f['alg_rank'] = np.linalg.matrix_rank(P, tol=1e-6)
    f['P'] = P  # projections for later use

    # Identify particles
    particles = []
    for k in range(n):
        e_k = np.zeros(n, dtype=complex)
        e_k[k] = 1.0
        proj = V @ (V.conj().T @ e_k)
        overlap = np.linalg.norm(proj)
        if overlap > 0.3:
            particles.append((k, particle_names[k], overlap))
    f['particles'] = particles

print(f"\n  Wedderburn: {len(wd_factors)} factors")
for f_idx, f in enumerate(wd_factors):
    print(f"    Factor {f_idx}: dim_V={f['dim_V']}, rank={f['alg_rank']}")
    for k, name, ov in f['particles']:
        print(f"      idx {k:>2}: {name:>15}  overlap={ov:.4f}")

total_rank = sum(f['alg_rank'] for f in wd_factors)
print(f"\n  Total rank: {total_rank} (target: 24)")


# =============================================================================
# PART 5: o-MAP ACTION ON WEDDERBURN FACTORS
# =============================================================================

print("\n" + "=" * 72)
print("[PART 5] How the o-map acts on Wedderburn factors")
print("=" * 72)

# For each factor, compute the o-image of its elements and check which
# factor the o-image lands in.
# Factor i: spanned by projections P_i @ T @ P_i for T in algebra.
# o(P_i T P_i) = Xi (P_i T P_i)^T Xi -- does this project onto factor j?

n_factors = len(wd_factors)

# Build projectors onto each factor's subspace of C^32
factor_projs = []
for f in wd_factors:
    V = f['V']
    P = V @ V.conj().T  # projector onto this subspace of C^32
    factor_projs.append(P)

# For each factor pair (i,j), compute max |[a_i, o(b_j)]| where
# a_i is in factor i and b_j is in factor j
print("\n  Cross-factor o-commutation matrix:")
print(f"  {'':>12}", end='')
for j in range(n_factors):
    print(f"  o(F{j})", end='')
print()

cross_factor_oz = np.zeros((n_factors, n_factors))
for fi in range(n_factors):
    Vi = wd_factors[fi]['V']
    print(f"  F{fi} (r={wd_factors[fi]['alg_rank']:>2}):", end='')
    for fj in range(n_factors):
        Vj = wd_factors[fj]['V']
        max_comm = 0
        # Sample algebra elements from each factor
        for T in AF_closure_basis:
            # Restrict T to factor fi: a = Vi Vi^H T Vi Vi^H
            a = Vi @ (Vi.conj().T @ T @ Vi) @ Vi.conj().T
            # Restrict T to factor fj and take o-image
            b_fj = Vj @ (Vj.conj().T @ T @ Vj) @ Vj.conj().T
            b_opp = Xi @ b_fj.T @ Xi
            comm = a @ b_opp - b_opp @ a
            max_comm = max(max_comm, np.max(np.abs(comm)))
        cross_factor_oz[fi, fj] = max_comm
        status = 'ok' if max_comm < 1e-6 else f'{max_comm:.2f}'
        print(f"  {status:>5}", end='')
    print()

# Identify which factor pairs satisfy order-zero
oz_pairs = []
for fi in range(n_factors):
    for fj in range(n_factors):
        if cross_factor_oz[fi, fj] < 1e-6:
            oz_pairs.append((fi, fj))

print(f"\n  Order-zero pairs: {len(oz_pairs)} / {n_factors**2}")

# Now: check if o maps each factor to itself or to another factor
print("\n  o-map action on factor subspaces:")
for fi in range(n_factors):
    Vi = wd_factors[fi]['V']
    # Take the projector of factor fi and compute its o-image
    # o(P_fi) projects onto the o-image of this factor's SUBSPACE
    # But we want: where do algebra elements of fi go under o?
    # Take basis of factor fi's algebra: restrict each AF_closure_basis[k] to fi
    fi_basis = []
    for T in AF_closure_basis:
        a = Vi @ (Vi.conj().T @ T @ Vi) @ Vi.conj().T
        if np.max(np.abs(a)) > 1e-10:
            fi_basis.append(a)

    # o-images of fi_basis elements
    o_overlaps = np.zeros(n_factors)
    n_tested = 0
    for a in fi_basis[:20]:  # sample first 20
        a_opp = Xi @ a.T @ Xi
        if np.max(np.abs(a_opp)) < 1e-10:
            continue
        n_tested += 1
        for fj in range(n_factors):
            Vj = wd_factors[fj]['V']
            proj_to_fj = Vj @ (Vj.conj().T @ a_opp @ Vj) @ Vj.conj().T
            frac = np.linalg.norm(proj_to_fj) / max(np.linalg.norm(a_opp), 1e-15)
            o_overlaps[fj] = max(o_overlaps[fj], frac)

    print(f"    o(F{fi}) overlaps: ", end='')
    for fj in range(n_factors):
        print(f"F{fj}={o_overlaps[fj]:.3f}  ", end='')
    print()


# =============================================================================
# PART 6: ORDER-ZERO SUBALGEBRA VIA FACTOR COMBINATIONS
# =============================================================================

print("\n" + "=" * 72)
print("[PART 6] Order-zero subalgebra: factor combinations")
print("=" * 72)

# The order-zero condition [a, o(b)] = 0 must hold for all a,b in A_F.
# For A_F = direct sum of factors, this means:
# 1. [Fi, o(Fj)] = 0 for all factor pairs (i,j)
# 2. Each factor must commute with the o-image of every other factor
#
# Since the 40-dim algebra is too large (40 > 24), we need to find a
# SUBALGEBRA (combination of sub-factors or restricted factors) that
# satisfies order-zero.
#
# Strategy: For each Wedderburn factor, compute the o-image algebra,
# then find the subalgebra that commutes with all o-images.

# First, build per-factor algebra bases within the 40-dim coordinate system
factor_bases_40 = []
for fi in range(n_factors):
    Vi = wd_factors[fi]['V']
    d_V = wd_factors[fi]['dim_V']
    # Restrict each AF_closure_basis to this factor
    vecs_40 = []
    for k in range(d_AF):
        T = AF_closure_basis[k]
        a = Vi @ (Vi.conj().T @ T @ Vi) @ Vi.conj().T
        pv = np.concatenate([a.flatten().real, a.flatten().imag])
        coeffs = Q_AF_closure.T @ pv
        vecs_40.append(coeffs)
    P_fi = np.column_stack(vecs_40)
    Q_fi = orth(P_fi)
    factor_bases_40.append(Q_fi)
    print(f"  Factor {fi}: rank in 40-dim algebra = {Q_fi.shape[1]}")

# Now build the o-commutator tensor (only once)
F_tensor = np.zeros((d_AF, d_AF, d_AF))  # F[k,i,j] = [e_i, o(e_j)]_k
comm_sc_2 = struct_const - struct_const.transpose(1, 0, 2)
for k in range(d_AF):
    F_tensor[k] = comm_sc_2[:, :, k].T @ O_map

# Verify F-tensor
max_F_err = 0
for i in range(min(d_AF, 5)):
    for j in range(min(d_AF, 5)):
        a = AF_closure_basis[i]
        b_opp = Xi @ AF_closure_basis[j].T @ Xi
        comm_direct = a @ b_opp - b_opp @ a
        pv = np.concatenate([comm_direct.flatten().real, comm_direct.flatten().imag])
        coeffs_d = Q_AF_closure.T @ pv
        coeffs_t = F_tensor[:, i, j]
        max_F_err = max(max_F_err, np.linalg.norm(coeffs_d - coeffs_t))
print(f"  F-tensor verification: {max_F_err:.2e}")

# For each factor, test order-zero WITHIN the factor
print("\n  Within-factor order-zero (should FAIL for non-commutative factors):")
for fi in range(n_factors):
    Q_fi = factor_bases_40[fi]
    d_fi = Q_fi.shape[1]
    max_oz = 0
    for alpha in range(d_fi):
        for beta in range(d_fi):
            va = Q_fi[:, alpha]
            vb = Q_fi[:, beta]
            # [a, o(b)]_k = sum_ij va_i F^k_{ij} vb_j
            comm_k = np.einsum('i,kij,j->k', va, F_tensor, vb)
            max_oz = max(max_oz, np.max(np.abs(comm_k)))
    print(f"    F{fi} (rank {d_fi}): max |[a, o(b)]| = {max_oz:.4f}")

# For each pair of factors, test cross-factor order-zero
print("\n  Cross-factor order-zero:")
cross_oz_matrix = np.zeros((n_factors, n_factors))
for fi in range(n_factors):
    Q_fi = factor_bases_40[fi]
    d_fi = Q_fi.shape[1]
    for fj in range(n_factors):
        if fi == fj:
            continue
        Q_fj = factor_bases_40[fj]
        d_fj = Q_fj.shape[1]
        max_oz = 0
        for alpha in range(d_fi):
            for beta in range(d_fj):
                va = Q_fi[:, alpha]
                vb = Q_fj[:, beta]
                comm_k = np.einsum('i,kij,j->k', va, F_tensor, vb)
                max_oz = max(max_oz, np.max(np.abs(comm_k)))
        cross_oz_matrix[fi, fj] = max_oz

print(f"  {'':>12}", end='')
for j in range(n_factors):
    print(f"  o(F{j})", end='')
print()
for fi in range(n_factors):
    print(f"  F{fi} (r={factor_bases_40[fi].shape[1]:>2}):", end='')
    for fj in range(n_factors):
        if fi == fj:
            print(f"  {'self':>5}", end='')
        else:
            v = cross_oz_matrix[fi, fj]
            s = f'{v:.3f}' if v > 1e-6 else 'PASS'
            print(f"  {s:>5}", end='')
    print()


# =============================================================================
# PART 7: MAXIMAL ORDER-ZERO SUBALGEBRA WITHIN EACH FACTOR
# =============================================================================

print("\n" + "=" * 72)
print("[PART 7] Finding order-zero subalgebra within each factor")
print("=" * 72)

# For a factor F_i with within-factor order-zero violation, we need to find
# the maximal subalgebra S_i of F_i such that [S_i, o(S_i)] = 0.
#
# For a simple factor M_k(K), the maximal order-zero subalgebra depends on
# how o acts:
# - If o fixes the factor (o: F_i -> F_i), the o-zero subalgebra is the
#   FIXED-POINT algebra of the anti-automorphism o|_{F_i}
# - If o swaps two factors (o: F_i -> F_j), then S = F_i + F_j trivially
#   satisfies [F_i, o(F_j)] = [F_i, F_i'] where F_i' lives in a different
#   factor slot, so they commute.
#
# KEY INSIGHT: We need to understand the o-map's action on the factor ALGEBRA,
# not just the factor SUBSPACE. The o-map is an ANTI-homomorphism.

# For each factor, compute the o-restriction
print("\n  o-map restricted to each factor:")
for fi in range(n_factors):
    Q_fi = factor_bases_40[fi]
    d_fi = Q_fi.shape[1]

    # The o-map in the 40-dim basis: O_map
    # Restricted to factor fi: O_fi = Q_fi^T O_map Q_fi
    O_fi = Q_fi.T @ O_map @ Q_fi

    # How much leaks out?
    O_fi_full = O_map @ Q_fi  # d_AF x d_fi
    proj_back = Q_fi @ (Q_fi.T @ O_fi_full)
    leak = np.max(np.abs(O_fi_full - proj_back))

    # Check anti-homomorphism: o(ab) = o(b)o(a) on this factor
    # (This tests whether o is really an anti-hom on this factor)

    print(f"  Factor {fi} (rank {d_fi}): o-leak = {leak:.4f}, "
          f"o-within rank = {np.linalg.matrix_rank(O_fi, tol=1e-6)}")

    # If leak is significant, o maps this factor to another factor
    if leak > 0.1:
        # Find which factor the o-images land in
        for fj in range(n_factors):
            if fj == fi:
                continue
            Q_fj = factor_bases_40[fj]
            proj_to_fj = Q_fj @ (Q_fj.T @ O_fi_full)
            frac = np.linalg.norm(proj_to_fj) / max(np.linalg.norm(O_fi_full), 1e-15)
            if frac > 0.1:
                print(f"    o(F{fi}) -> F{fj}: fraction = {frac:.4f}")

# Now let's try the definitive approach: iterative pruning on the FULL algebra
# but using the BILINEAR structure of order-zero.
print("\n" + "-" * 60)
print("  ITERATIVE BICOMMUTANT APPROACH")
print("-" * 60)

# Start with the full 40-dim closure algebra.
# Compute: for each element a, the set of elements b such that [a, o(b)] = 0.
# Then: find the maximal subspace S = {a : [a, o(b)] = 0 for all b in S}
# by alternating projection.

# Phase 1: Compute o-commutant of the FULL algebra first
# oComm(A) = {a in A : [a, o(b)] = 0 for all b in A}
# This is a LINEAR problem: for each a, the condition is sum_i a_i F^k_{ij} = 0
# for all j, k. I.e., a is in the null space of F^k viewed as linear maps.

# Flatten F_tensor: for each j, the map a -> F(a, e_j) must be zero for all j.
# That means: the matrix M_j with M_j[k, i] = F^k_{ij} must satisfy M_j @ a = 0.
# Stack all M_j: big matrix (d_AF * d_AF) x d_AF
big_F = np.zeros((d_AF * d_AF, d_AF))
for j in range(d_AF):
    big_F[j * d_AF:(j + 1) * d_AF, :] = F_tensor[:, :, j]

oComm_A = null_space(big_F, rcond=1e-8)
d_oComm = oComm_A.shape[1]
print(f"\n  oComm(full 40-dim) = {{a : [a, o(b)]=0 for all b}} : dim = {d_oComm}")

# This is the CENTER of the opposite algebra action. It should be the same
# as Comm(o(A)) intersected with A.

# Phase 2: Compute the reverse: {b in A : [a, o(b)] = 0 for all a in A}
# I.e., o(b) commutes with all of A, meaning o(b) is in the center of A.
# Since o is an anti-automorphism, this means b is in o^{-1}(center) = o(center).
big_F_rev = np.zeros((d_AF * d_AF, d_AF))
for i in range(d_AF):
    big_F_rev[i * d_AF:(i + 1) * d_AF, :] = F_tensor[:, i, :]

oCent_A = null_space(big_F_rev, rcond=1e-8)
d_oCent = oCent_A.shape[1]
print(f"  {{b : [a, o(b)]=0 for all a}} : dim = {d_oCent}")
print(f"  (Should equal center dim = {center_dim} since o(center)=center)")

# Phase 3: ALTERNATING PROJECTION
# Start with S0 = full algebra (dim 40)
# S1 = {a in A : [a, o(b)] = 0 for all b in S0} = oComm(S0) = center-like (dim ~5-8)
# S2 = {a in A : [a, o(b)] = 0 for all b in S1} = larger (since S1 is smaller)
# Continue until S_n = S_{n+1} (fixed point)
# The fixed point is the maximal order-zero subalgebra IF it's a subalgebra.

print("\n  Alternating projection:")
S_cur = np.eye(d_AF)  # Start with full algebra
d_S_cur = d_AF

for step in range(20):
    # Compute oComm(S_cur) = {a in A : [a, o(b)] = 0 for all b in S_cur}
    # The constraint is: for all beta, k: sum_i a_i F^k_{i,j} (S_cur)_{j,beta} = 0
    # Equivalently: sum_i a_i (F^k @ S_cur)_{i, beta} = 0 for all k, beta
    # Build constraint matrix: rows are (k, beta), columns are i

    constraints = []
    for k in range(d_AF):
        # F_k = F_tensor[k, :, :]  shape (d_AF, d_AF)
        # F_k @ S_cur: (d_AF, d_S_cur) -- but we want sum_i a_i F_k[i, j] S_cur[j, beta]
        # = sum_i a_i (F_k @ S_cur)[i, beta]... wait, F_tensor[k, i, j] is the (k,i,j) entry
        # The constraint is: sum_i a_i * sum_j F[k,i,j] * S_cur[j, beta] = 0
        # = sum_i a_i * (F[k] @ S_cur)[i, beta] = 0
        F_k_S = F_tensor[k] @ S_cur[:, :d_S_cur]  # shape (d_AF, d_S_cur)
        for beta in range(d_S_cur):
            constraints.append(F_k_S[:, beta])  # row = constraint on a

    constraint_mat = np.array(constraints)  # shape (d_AF * d_S_cur, d_AF)
    oComm_S = null_space(constraint_mat, rcond=1e-8)
    d_oComm_S = oComm_S.shape[1]

    # Now compute the REVERSE: {b in A : [a, o(b)] = 0 for all a in oComm_S}
    constraints_rev = []
    for k in range(d_AF):
        # sum_j b_j * sum_i oComm_S[i, alpha] * F[k,i,j] = 0 for all alpha
        # = sum_j b_j * (oComm_S^T @ F[k])[:, j] = 0... let me be precise:
        # F[k,i,j], alpha indexes oComm_S columns
        # sum_j b_j (sum_i oComm_S[i,alpha] F[k,i,j]) = 0
        # = sum_j b_j (oComm_S[:,alpha]^T @ F[k,:,j]) = 0... no
        # Let M[alpha,j] = sum_i oComm_S[i,alpha] F[k,i,j]
        # = (oComm_S.T @ F[k])[alpha, j]
        M_alpha_j = oComm_S.T @ F_tensor[k]  # shape (d_oComm_S, d_AF)
        for alpha in range(d_oComm_S):
            constraints_rev.append(M_alpha_j[alpha, :])  # row constraining b

    constraint_mat_rev = np.array(constraints_rev)
    S_new = null_space(constraint_mat_rev, rcond=1e-8)
    d_S_new = S_new.shape[1]

    print(f"  Step {step+1}: oComm(S) dim={d_oComm_S}, "
          f"oComm^{{-1}}(oComm(S)) dim={d_S_new}")

    if d_S_new == d_S_cur:
        print(f"  Converged at dim = {d_S_new}")
        S_cur = S_new
        d_S_cur = d_S_new
        break

    S_cur = S_new
    d_S_cur = d_S_new

# The fixed point S_cur is our candidate order-zero set
print(f"\n  Fixed-point set dimension: {d_S_cur}")

# Check if it's a subalgebra
if d_S_cur > 0:
    max_closure_S = 0
    for alpha in range(d_S_cur):
        for beta in range(d_S_cur):
            ca = S_cur[:, alpha]
            cb = S_cur[:, beta]
            prod_k = np.einsum('i,j,ijk->k', ca, cb, struct_const)
            proj = S_cur.T @ prod_k
            resid = np.linalg.norm(prod_k - S_cur @ proj)
            max_closure_S = max(max_closure_S, resid)
    print(f"  Subalgebra closure: {max_closure_S:.2e} "
          f"({'PASS' if max_closure_S < 1e-6 else 'FAIL'})")

    # Verify order-zero on this set
    max_oz_S = 0
    for alpha in range(d_S_cur):
        for beta in range(d_S_cur):
            va = S_cur[:, alpha]
            vb = S_cur[:, beta]
            comm_k = np.einsum('i,kij,j->k', va, F_tensor, vb)
            max_oz_S = max(max_oz_S, np.max(np.abs(comm_k)))
    print(f"  Order-zero check: max = {max_oz_S:.2e} "
          f"({'PASS' if max_oz_S < 1e-6 else 'FAIL'})")

    if max_closure_S > 1e-6:
        print("\n  Computing algebraic closure of the fixed-point set...")
        S_mats_fp = [sum(S_cur[i, alpha] * AF_closure_basis[i]
                         for i in range(d_AF))
                     for alpha in range(d_S_cur)]
        Q_Salg, Salg_basis, d_Salg = algebraic_closure_in_space(
            S_mats_fp, Q_AF_closure, max_iter=5)
        print(f"  Algebraic closure dimension: {d_Salg}")

        # Check order-zero on the algebraic closure
        max_oz_alg = 0
        for i in range(d_Salg):
            for j in range(d_Salg):
                a = Salg_basis[i]
                b_opp = Xi @ Salg_basis[j].T @ Xi
                comm = a @ b_opp - b_opp @ a
                err = np.max(np.abs(comm))
                max_oz_alg = max(max_oz_alg, err)
        print(f"  Order-zero on closure: {max_oz_alg:.2e} "
              f"({'PASS' if max_oz_alg < 1e-6 else 'FAIL'})")

        if max_oz_alg < 1e-6:
            print(f"\n  ** CANDIDATE A_F found: dim = {d_Salg} **")
            # Analyze this algebra
            sc_cand = np.zeros((d_Salg, d_Salg, d_Salg))
            Q_cand_40 = np.zeros((d_AF, d_Salg))
            for i in range(d_Salg):
                pv = np.concatenate([Salg_basis[i].flatten().real,
                                     Salg_basis[i].flatten().imag])
                Q_cand_40[:, i] = Q_AF_closure.T @ pv

            for i in range(d_Salg):
                for j in range(d_Salg):
                    prod = Salg_basis[i] @ Salg_basis[j]
                    pv = np.concatenate([prod.flatten().real, prod.flatten().imag])
                    sc_cand[i, j, :] = Q_cand_40.T @ pv

            # Center
            comm_cand = sc_cand - sc_cand.transpose(1, 0, 2)
            rows_c = [comm_cand[:, j, k] for j in range(d_Salg) for k in range(d_Salg)]
            center_dim_cand = null_space(np.array(rows_c), rcond=1e-8).shape[1]
            print(f"  Center dimension: {center_dim_cand} (A_F target: 3)")

            # Trace form
            tf_cand = np.array([[np.trace(Salg_basis[i] @ Salg_basis[j]).real
                                 for j in range(d_Salg)] for i in range(d_Salg)])
            tf_rank_cand = np.linalg.matrix_rank(tf_cand, tol=1e-6)
            print(f"  Trace form rank: {tf_rank_cand} "
                  f"({'SEMISIMPLE' if tf_rank_cand == d_Salg else 'RADICAL'})")


# =============================================================================
# PART 8: DIRECT A_F CONSTRUCTION (CONNES' REPRESENTATION)
# =============================================================================

print("\n" + "=" * 72)
print("[PART 8] Direct A_F construction from Connes' representation theory")
print("=" * 72)

# In Connes' NCG Standard Model, A_F = C + H + M_3(C) acts on H_F as follows:
#
# Particle state: Psi is a 4x4 internal matrix (Baptista eq 2.12):
#   Psi = [[a,  c1, c2, c3],   where a in C (scalar), c in C^3 (color),
#          [b1, D11, D12, D13],  b in C^3 (color), D in M_3(C) (3x3 matrix)
#          [b2, D21, D22, D23],
#          [b3, D31, D32, D33]]
#
# Indices: row = weak doublet component, col = color
# Row 0 = "up" (neutrino/up-quark), rows 1-3 = "down" (electron/down-quark)
# Col 0 = lepton (singlet), cols 1-3 = quark colors (triplet)
#
# A_F acts by LEFT multiplication (Baptista eq 2.62):
#   For (lambda, q, m) in C + H + M_3(C):
#     lambda acts on the (0,0) entry: a -> lambda * a
#     q acts on the (0,0)-(1,0) column: (a, b1) -> q * (a, b1)  [as quaternion on C^2]
#     m acts on the (.,1-3) columns: D_ij -> sum_k m_jk D_ik  [as M_3 on color index]
#
# Wait -- this isn't quite right. Let me be more precise.
# In Connes' framework, for one generation, H_F = C^32 with:
#   Psi_+ = 16-dim (particles): our indices 0-15
#   Psi_- = 16-dim (antiparticles): indices 16-31
#
# The A_F representation on Psi_+ (eq 2.66 of Baptista):
# For (lambda, q, m) in A_F = C + H + M_3(C):
#
#   Psi_+ index layout (row-major of 4x4 matrix):
#     0: nu_R   (row=0, col=0) -> lambda acts
#     1: u_R^r  (row=0, col=1) -> nothing (color scalar for this row)
#     2: u_R^g  (row=0, col=2) -> nothing
#     3: u_R^b  (row=0, col=3) -> nothing
#     4: e_R    (row=1, col=0) -> lambda-bar acts
#     5: nu_L   (row=2, col=0) -> q acts on (5,6) doublet
#     6: e_L    (row=3, col=0) -> q acts on (5,6) doublet
#     7: d_R^r  (row=1, col=1) -> m acts on (7,8,9)
#     8: d_R^g  (row=1, col=2) -> m acts on (7,8,9)
#     9: d_R^b  (row=1, col=3) -> m acts on (7,8,9)
#    10: u_L^r  (row=2, col=1) -> q and m both act
#    11: u_L^g  (row=2, col=2) -> q and m both act
#    12: u_L^b  (row=2, col=3) -> q and m both act
#    13: d_L^r  (row=3, col=1) -> q and m both act
#    14: d_L^g  (row=3, col=2) -> q and m both act
#    15: d_L^b  (row=3, col=3) -> q and m both act
#
# Actually, Baptista eq 2.62 says L_v(Psi) = v*Psi (left multiplication of 4x4).
# For A_F element a = (lambda, q, m), the LEFT action is:
#   a * Psi = [[lambda, 0, 0, 0],  * [[a, c1, c2, c3],
#              [0, q_11, 0, 0],      [b1,...          ],
#              [0, q_21, 0, 0],      [b2,...          ],
#              [0, q_22, 0, 0]]      [b3,...          ]]
#
# No wait. Let me think about this more carefully using Baptista's actual L action.
# Baptista eq 2.62: L_v(Psi) = v*Psi where v in su(3) and Psi is 4x4.
# But A_F is NOT su(3). A_F is a SUBALGEBRA of End(H_F).
#
# The correct picture: L_v for v in su(3) represents the LEFT action of su(3)
# on the internal matrix Psi. The algebra A_F = C + H + M_3(C) is embedded as:
#
# (lambda, q, m) -> the 4x4 matrix:
#   [[lambda,   0  ,   0  ,   0  ],
#    [  0   , lambda-bar, 0,   0  ],
#    [  0   ,   0  ,   0  ,   0  ],
#    [  0   ,   0  ,   0  ,   0  ]]     for the C factor
#
# PLUS quaternion q embedded in the (row 2-3, col 0) block, etc.
#
# Actually, the cleanest way is to just BUILD the 16x16 matrix explicitly.
# The A_F representation on Psi_+ (one gen) is:
#
# For (lambda, q, m) in C + H + M_3(C):
#   pi(lambda, q, m) is a 16x16 matrix acting on Psi_+ = C^16.
#
# lambda acts as:
#   nu_R (idx 0) -> lambda * nu_R
#   u_R^c (idx 1,2,3) -> lambda * u_R^c  [SAME lambda, not lambda-bar!]
#   e_R (idx 4) -> lambda-bar * e_R
#   ALL LEFT-HANDED -> nothing from C part alone
#
# Actually I realize this depends critically on the EXACT conventions.
# Let me just construct the A_F generators and TEST them against the commutant.

print("  Building Connes' A_F generators directly on C^16 (Psi_+)...")

# The 24 real generators of A_F = C + H + M_3(C):
# C: 2 real generators (Re(lambda), Im(lambda))
# H: 4 real generators (1, i, j, k)
# M_3(C): 18 real generators (9 Re + 9 Im of 3x3 matrix entries)
#
# Total: 2 + 4 + 18 = 24

# LEPTON INDICES: nu_R=0, e_R=4, nu_L=5, e_L=6
# QUARK INDICES: u_R^c={1,2,3}, d_R^c={7,8,9}, u_L^c={10,11,12}, d_L^c={13,14,15}

# CONNES' A_F on Psi_+:
#
# (lambda, q, m) acts as the BLOCK DIAGONAL matrix:
# [[lambda_11 . lambda-bar_11 . q_11 . q_12 . m_11 . m_12 . m_13 . ...]
#
# More precisely, using Baptista's 4x4 matrix structure and LEFT multiplication:
#
# a = diag_4x4(lambda, lambda-bar, q) tensor_right diag_1x3(1, m)
#
# For the TOP ROW of the 4x4 (nu_R, u_R^r, u_R^g, u_R^b):
#   The left factor is lambda (scalar), the right factor is (1, m_11, m_12, m_13)
#   So: nu_R -> lambda * nu_R
#       u_R^c -> lambda * sum_c' m_{c'c} * u_R^{c'}   [NO -- m acts on COLUMN index]
#
# Hmm, this gets confusing with the 4x4 structure. Let me use a completely explicit
# approach: write down each A_F generator as a 16x16 matrix.

# APPROACH: The Connes representation pi: A_F -> End(C^16) is:
#
# pi(lambda, q, m) . Psi = left_multiply_by_(lambda,q) . Psi . right_multiply_by_(1,m^T)
#
# where Psi is 4x4, left multiply uses the row structure, right multiply uses columns.
#
# Left factor (acts on rows 0-3 of the 4x4):
#   row 0: multiply by lambda    (for "a" row = right-handed up)
#   row 1: multiply by lambda-bar (for "b" row = right-handed down)
#   rows 2-3: multiply by q (2x2 quaternion) (for "nu_L, e_L" = left-handed doublet)
#
# Right factor (acts on cols 0-3 of the 4x4):
#   col 0: multiply by 1 (lepton = color singlet)
#   cols 1-3: multiply by m^T (3x3 matrix on color triplet)
#
# So pi(lambda, q, m) . Psi_{ij} = sum_{k,l} L_{ik} * Psi_{kl} * R_{lj}
# where L = diag(lambda, lambda-bar, q) is 4x4
# and R = diag(1, m^T) is 4x4
#
# In the FLATTENED 16-dim basis (row-major: Psi_{ij} -> index 4*i + j):
#   pi(lambda, q, m)_{(4i+j),(4k+l)} = L_{ik} * R_{lj} = L_{ik} * R^T_{jl}
#   = (L tensor R^T)_{(4i+j),(4k+l)}

# BUT WAIT: Baptista's flattening is NOT row-major in the standard sense!
# From branching_computation.py:
#   idx 0 = a (row 0, col 0)
#   idx 1-3 = c = (row 0, col 1-3) [color of up-right]
#   idx 4-6 = b = (row 1-3, col 0) [color of down-right and left-doublet leptons]
#      But wait: 4=e_R (row 1, col 0), 5=nu_L (row 2, col 0), 6=e_L (row 3, col 0)
#   idx 7-15 = D = row-major of 3x3 block (rows 1-3, cols 1-3)
#      7-9 = d_R (row 1, cols 1-3)
#     10-12 = u_L (row 2, cols 1-3)
#     13-15 = d_L (row 3, cols 1-3)
#
# So the mapping from 4x4 matrix index (i,j) to flat index is:
#   (0,0) -> 0 [nu_R]
#   (0,1) -> 1, (0,2) -> 2, (0,3) -> 3 [u_R colors]
#   (1,0) -> 4 [e_R]
#   (2,0) -> 5 [nu_L]
#   (3,0) -> 6 [e_L]
#   (1,1) -> 7, (1,2) -> 8, (1,3) -> 9 [d_R colors]
#   (2,1) -> 10, (2,2) -> 11, (2,3) -> 12 [u_L colors]
#   (3,1) -> 13, (3,2) -> 14, (3,3) -> 15 [d_L colors]
#
# The 4x4 indices (i,j) with:
#   i: 0=up-RH, 1=down-RH, 2=up-LH, 3=down-LH  (weak structure)
#   j: 0=lepton, 1-3=quark colors  (color structure)

# Build flat_idx(i,j) mapping
# From branching_computation.py:
#   idx 0: a = (0,0)
#   idx 1-3: c = (0,1), (0,2), (0,3)  [row 0, cols 1-3]
#   idx 4-6: b = (1,0), (2,0), (3,0)  [rows 1-3, col 0]
#   idx 7-15: D = 3x3 row-major: (1,1)=7, (1,2)=8, (1,3)=9, (2,1)=10, ...
def flat_idx(row, col):
    """Convert 4x4 internal matrix position (row, col) to flat 16-index.

    Baptista convention:
      (0,0) -> 0 (a = nu_R)
      (0,j) -> j for j=1,2,3 (c = u_R colors)
      (i,0) -> i+3 for i=1,2,3 (b = e_R, nu_L, e_L)
      (i,j) -> 7 + 3*(i-1) + (j-1) for i,j=1,2,3 (D = quarks)
    """
    if row == 0 and col == 0:
        return 0
    elif row == 0:
        return col  # 1, 2, 3
    elif col == 0:
        return row + 3  # 4, 5, 6
    else:
        return 7 + 3 * (row - 1) + (col - 1)  # 7-15

# Verify mapping against known particle assignments (eq 2.66)
assert flat_idx(0, 0) == 0   # nu_R = a
assert flat_idx(0, 1) == 1   # u_R^r = c_1
assert flat_idx(0, 2) == 2   # u_R^g = c_2
assert flat_idx(0, 3) == 3   # u_R^b = c_3
assert flat_idx(1, 0) == 4   # e_R = b_1
assert flat_idx(2, 0) == 5   # nu_L = b_2
assert flat_idx(3, 0) == 6   # e_L = b_3
assert flat_idx(1, 1) == 7   # d_R^r = D_11
assert flat_idx(1, 2) == 8   # d_R^g = D_12
assert flat_idx(1, 3) == 9   # d_R^b = D_13
assert flat_idx(2, 1) == 10  # u_L^r = D_21
assert flat_idx(2, 2) == 11  # u_L^g = D_22
assert flat_idx(2, 3) == 12  # u_L^b = D_23
assert flat_idx(3, 1) == 13  # d_L^r = D_31
assert flat_idx(3, 2) == 14  # d_L^g = D_32
assert flat_idx(3, 3) == 15  # d_L^b = D_33

# Build the A_F generators as 16x16 matrices
# pi(lambda, q, m) acts on Psi_{ij} as:
#   (pi(a) . Psi)_{ij} = sum_k L_{ik} Psi_{kl} sum_l R_{lj}
# where L = block_diag(lambda, lambda-bar, q) : 4x4
#       R = block_diag(1, m^T) : 4x4
#
# In flat indices: (pi(a))_{flat(i,j), flat(k,l)} = L_{ik} * R_{lj}
# BUT only for (k,l) in the original 4x4 block structure.
# This is a tensor product: pi = L tensor R, in the (i,j), (k,l) basis.
# Flattened: pi_{flat(i,j), flat(k,l)} = L_{ik} * R_{lj}
#   = L_{ik} * (R^T)_{jl}

def build_AF_gen_16(L_4x4, R_4x4):
    """Build 16x16 A_F generator from 4x4 left and right actions."""
    gen = np.zeros((16, 16), dtype=complex)
    for i in range(4):
        for j in range(4):
            fi = flat_idx(i, j)
            for k in range(4):
                for l in range(4):
                    fk = flat_idx(k, l)
                    gen[fi, fk] = L_4x4[i, k] * R_4x4[l, j]
    return gen

# C generators: lambda = x + iy
# L_C(lambda) = diag(lambda, lambda-bar, lambda, lambda-bar)
#   BUT WAIT: for the left-handed doublet, lambda acts as... let me check.
# Actually in Connes' representation, lambda acts as:
#   row 0 (up-RH): lambda
#   row 1 (down-RH): lambda-bar
#   rows 2-3 (LH doublet): lambda * I_2  [as a complex number embedding in H]
# R_C = I_4 (C commutes with color)

def C_gen(which):
    """C generator: 'Re' or 'Im'."""
    L = np.zeros((4, 4), dtype=complex)
    R = np.eye(4, dtype=complex)
    if which == 'Re':
        L[0, 0] = 1.0    # lambda on up-RH
        L[1, 1] = 1.0    # lambda-bar on down-RH (Re part is same)
        L[2, 2] = 1.0    # lambda on up-LH
        L[3, 3] = 1.0    # lambda on down-LH
    elif which == 'Im':
        L[0, 0] = 1j     # i*lambda on up-RH
        L[1, 1] = -1j    # -i*lambda-bar on down-RH
        L[2, 2] = 1j     # i*lambda on up-LH
        L[3, 3] = -1j    # -i on down-LH... wait
        # For LH doublet: lambda embeds in H as q = (Re(lambda), Im(lambda), 0, 0)
        # The quaternion q = x + iy + 0j + 0k acts on C^2 as:
        #   [[x+iy, 0], [0, x-iy]] = diag(lambda, lambda-bar)
        L[2, 2] = 1j     # lambda on nu_L
        L[3, 3] = -1j    # lambda-bar on e_L
    return build_AF_gen_16(L, R)

# H generators: q = q0 + q1*i + q2*j + q3*k
# Acts on rows 2-3 (LH doublet) as 2x2 quaternion matrix:
#   q -> [[q0+iq1, q2+iq3], [-q2+iq3, q0-iq1]]
# Acts on row 0 (up-RH): q0 + iq1 (complex embedding)
# Acts on row 1 (down-RH): q0 - iq1 (conjugate embedding)
# R = I_4 (H commutes with color)

def H_gen(which):
    """H generator: '1', 'i', 'j', 'k'."""
    L = np.zeros((4, 4), dtype=complex)
    R = np.eye(4, dtype=complex)
    if which == '1':
        L = np.eye(4, dtype=complex)
    elif which == 'i':
        L[0, 0] = 1j     # q0+iq1 on up-RH: i -> 0+i*1 = i
        L[1, 1] = -1j    # q0-iq1 on down-RH: i -> 0-i*1 = -i
        L[2, 2] = 1j     # [[iq1, 0], [0, -iq1]] -> diag(i, -i)
        L[3, 3] = -1j
    elif which == 'j':
        L[0, 0] = 0      # q0+iq1 = 0 for j
        L[1, 1] = 0      # q0-iq1 = 0 for j
        L[2, 3] = 1.0    # [[0, 1], [-1, 0]] on doublet
        L[3, 2] = -1.0
    elif which == 'k':
        L[0, 0] = 0      # q0+iq1 = 0 for k
        L[1, 1] = 0      # q0-iq1 = 0 for k
        L[2, 3] = 1j     # [[0, i], [i, 0]] on doublet
        L[3, 2] = 1j
    return build_AF_gen_16(L, R)

# M_3(C) generators: m is a 3x3 complex matrix
# Acts on cols 1-3 (quark colors) via right multiplication by m^T
# L = I_4 (M_3 commutes with weak isospin)
# R = block_diag(1, m^T)

def M3_gen(a, b, part):
    """M_3(C) generator: E_{ab} (elementary matrix), part='Re' or 'Im'."""
    L = np.eye(4, dtype=complex)
    R = np.zeros((4, 4), dtype=complex)
    R[0, 0] = 0  # lepton: M_3 acts as 0 on col 0? NO!
    # Actually M_3 acts ONLY on quark indices (cols 1-3).
    # On col 0 (lepton), M_3 acts as 0. But then m*I on leptons = 0, which means
    # the M_3 factor doesn't even contain the identity on leptons.
    #
    # In Connes' framework, A_F = C + H + M_3(C) with:
    # - C and H act nontrivially on leptons, trivially on quarks (cols 1-3)
    # - M_3 acts nontrivially on quarks (cols 1-3), trivially on leptons (col 0)
    # Wait, that can't be right because then the identity of A_F wouldn't be
    # the identity matrix.
    #
    # Actually: each factor has its OWN identity:
    # 1_C = (1, 0, 0), 1_H = (0, 1_H, 0), 1_{M_3} = (0, 0, I_3)
    # And the GLOBAL identity is (1, 1_H, I_3).
    #
    # For M_3(C), the RIGHT action is on cols 1-3:
    #   R_{M_3} = block_diag(0, m^T)  [0 on col 0, m^T on cols 1-3]
    # But then pi(0, 0, m) acts on ALL rows (since L = I_4).
    #
    # Hmm, but that means M_3 acts nontrivially on nu_R (row 0, cols 1-3 = u_R).
    # Yes! M_3 permutes the COLORS of the right-handed up quarks.
    # And also colors of d_R, u_L, d_L (all quark rows).
    # On leptons (col 0), M_3 acts as 0.
    #
    # So L = I_4, R = diag(0, m^T) for the M_3 factor.
    # No, that's wrong: we want R on the COLUMN index.
    # pi(0,0,m): Psi_{ij} -> sum_l Psi_{il} m^T_{lj} = sum_l Psi_{il} m_{jl}
    # For j=0 (lepton): m_{0l} -- but m is 3x3 on indices 1,2,3.
    # So R = block_diag(1, m^T) where 1 is on col 0 and m^T is on cols 1-3.
    # Wait: for the A_F identity (1,1_H,I_3), we need R = diag(1, I_3) = I_4.
    # For a general m, R = diag(1, m^T).
    # But for the M_3 GENERATORS (not identity), we want m = E_{ab} (a,b in {0,1,2}
    # mapping to cols {1,2,3}).

    R[0, 0] = 1.0  # lepton column: identity (M_3 identity on lepton)
    # For the E_{ab} generator of M_3(C):
    #   m = E_{ab} means m_{a,b} = 1, all others 0
    #   m^T_{lj} = m_{jl} = delta_{j,a} delta_{l,b}
    #   R[col_b+1, col_a+1] = 1  (since R acts on cols and R = diag(1, m^T))
    # Wait, I need to be careful: a,b are 0-indexed within the 3x3 block.
    # The R matrix has col indices 0 (lepton), 1,2,3 (colors).
    # m^T in the (1,2,3) x (1,2,3) block: (m^T)_{(l-1)(j-1)} = m_{(j-1)(l-1)}
    # For E_{ab}: m_{ab} = 1, so m^T_{ba} = 1, meaning R[b+1, a+1] = 1.

    # Actually let me just set R directly:
    R = np.zeros((4, 4), dtype=complex)
    # R[0,0] = 0 for the generator (not the identity) -- actually wait.
    # The M_3 generator should be the TRACELESS part plus scaled identity.
    # For E_{ab} with a != b: pure off-diagonal, trace 0.
    # For a == b: diagonal element.
    #
    # Let me just build R = diag(0, E_{ab}^T) so M_3 generators have
    # NO action on leptons. The identity of M_3 will be R = diag(0, I_3).
    # Then the FULL identity of A_F is pi(1, 1_H, I_3):
    #   L = I_4, R_C = I_4, R_H = I_4, R_{M_3} = diag(0, I_3)
    # But then sum of these three R's = I_4 + I_4 + diag(0, I_3) which is wrong.
    #
    # No, A_F is a DIRECT SUM, not a direct product. The representation is:
    #   pi(lambda, q, m) = pi_C(lambda) + pi_H(q) + pi_{M_3}(m)
    # where each pi acts on DIFFERENT subspaces of H_F? No, they act on OVERLAPPING
    # subspaces.
    #
    # OK let me just take the simplest correct approach: build the LEFT action matrix.
    # For a = (lambda, q, m) in A_F, the 4x4 LEFT action matrix is:
    #   A_{4x4} = [[lambda, 0, 0, 0],
    #              [0, lambda-bar, 0, 0],
    #              [0, 0, q11, q12],
    #              [0, 0, q21, q22]]
    # And the 4x4 RIGHT action matrix is:
    #   B_{4x4} = [[1, 0, 0, 0],
    #              [0, m_11, m_12, m_13],
    #              [0, m_21, m_22, m_23],
    #              [0, m_31, m_32, m_33]]
    # (Note: C and H only act on the lepton column via left, M_3 only on quark
    # columns via right. They don't interfere.)
    #
    # The COMBINED action on Psi is: pi(a) . Psi = A . Psi . B^T
    # So pi(a)_{flat(i,j), flat(k,l)} = A_{ik} * B^T_{jl} = A_{ik} * B_{lj}

    # For M_3(C) generator E_{ab}: A = I_4, B = diag(1, E_{ab})
    # B_{lj}: B[0,0]=1, B[a+1, b+1]=1 (all others 0 in B)
    # pi_flat(i,j, k,l) = delta_{ik} * B_{lj}

    L_m = np.eye(4, dtype=complex)
    R_m = np.zeros((4, 4), dtype=complex)
    R_m[0, 0] = 1.0  # lepton column unchanged
    if part == 'Re':
        R_m[a + 1, b + 1] = 1.0
    elif part == 'Im':
        R_m[a + 1, b + 1] = 1j
    return build_AF_gen_16(L_m, R_m)

# Build all 24 generators (but the C_Re generator = H_1 generator = identity, so 23 independent + identity)
AF_gens_16 = []
AF_gen_names = []

# C factor: 2 real dims
AF_gens_16.append(C_gen('Re'))   # = identity (redundant with H '1')
AF_gen_names.append('C_Re')
AF_gens_16.append(C_gen('Im'))
AF_gen_names.append('C_Im')

# H factor: 4 real dims
AF_gens_16.append(H_gen('1'))    # = identity
AF_gen_names.append('H_1')
AF_gens_16.append(H_gen('i'))
AF_gen_names.append('H_i')
AF_gens_16.append(H_gen('j'))
AF_gen_names.append('H_j')
AF_gens_16.append(H_gen('k'))
AF_gen_names.append('H_k')

# M_3(C) factor: 18 real dims (9 Re + 9 Im entries)
for a in range(3):
    for b in range(3):
        AF_gens_16.append(M3_gen(a, b, 'Re'))
        AF_gen_names.append(f'M3_E{a}{b}_Re')
        AF_gens_16.append(M3_gen(a, b, 'Im'))
        AF_gen_names.append(f'M3_E{a}{b}_Im')

print(f"  Built {len(AF_gens_16)} generators on C^16")

# Extend to C^32 via J-compatibility
AF_gens_32 = build_full_32(AF_gens_16)
print(f"  Extended to C^32 via J")

# Test 1: Are these in the R_{u(2)} commutant?
print("\n  Test: A_F generators in R_u(2) commutant?")
max_comm_err = {}
for idx, (T, name) in enumerate(zip(AF_gens_32, AF_gen_names)):
    max_err = max(np.max(np.abs(T @ R_g - R_g @ T)) for R_g in R_u2_gens_32)
    max_comm_err[name] = max_err
    if max_err > 1e-8:
        print(f"    {name}: FAIL (error = {max_err:.4f})")

n_pass = sum(1 for v in max_comm_err.values() if v < 1e-8)
n_fail = len(max_comm_err) - n_pass
print(f"    PASS: {n_pass}, FAIL: {n_fail}")

if n_fail > 0:
    print("\n  Failing generators detail:")
    for name, err in sorted(max_comm_err.items(), key=lambda x: -x[1]):
        if err > 1e-8:
            print(f"    {name}: {err:.6f}")

# Test 2: Are these J-compatible?
print("\n  Test: A_F generators J-compatible?")
max_J_err = {}
for idx, (T, name) in enumerate(zip(AF_gens_32, AF_gen_names)):
    err = np.max(np.abs(T @ Xi - Xi @ np.conj(T)))
    max_J_err[name] = err
    if err > 1e-8:
        print(f"    {name}: FAIL (error = {err:.4f})")

n_pass_J = sum(1 for v in max_J_err.values() if v < 1e-8)
n_fail_J = len(max_J_err) - n_pass_J
print(f"    PASS: {n_pass_J}, FAIL: {n_fail_J}")

# Test 3: Quaternion relations
print("\n  Test: Quaternion relations in new H generators?")
new_H1 = AF_gens_32[AF_gen_names.index('H_1')]
new_Hi = AF_gens_32[AF_gen_names.index('H_i')]
new_Hj = AF_gens_32[AF_gen_names.index('H_j')]
new_Hk = AF_gens_32[AF_gen_names.index('H_k')]
new_quat_rels = [
    ('i*i=-1', new_Hi @ new_Hi, -new_H1),
    ('j*j=-1', new_Hj @ new_Hj, -new_H1),
    ('k*k=-1', new_Hk @ new_Hk, -new_H1),
    ('i*j=k',  new_Hi @ new_Hj, new_Hk),
    ('j*k=i',  new_Hj @ new_Hk, new_Hi),
    ('k*i=j',  new_Hk @ new_Hi, new_Hj),
]
new_quat_pass = True
for name, prod, expected in new_quat_rels:
    err = np.max(np.abs(prod - expected))
    status = 'PASS' if err < 1e-10 else 'FAIL'
    print(f"    {name}: {status} (err={err:.2e})")
    if err > 1e-10:
        new_quat_pass = False

# Test 4: Order-zero on these generators
print("\n  Test: Order-zero [a, Xi b^T Xi] on A_F generators?")
max_oz_AF = 0
oz_fail_pairs = []
for i, (Ti, ni) in enumerate(zip(AF_gens_32, AF_gen_names)):
    for j, (Tj, nj) in enumerate(zip(AF_gens_32, AF_gen_names)):
        b_opp = Xi @ Tj.T @ Xi
        comm = Ti @ b_opp - b_opp @ Ti
        err = np.max(np.abs(comm))
        max_oz_AF = max(max_oz_AF, err)
        if err > 1e-6:
            oz_fail_pairs.append((ni, nj, err))
print(f"    Max error: {max_oz_AF:.4f}")
print(f"    Violations: {len(oz_fail_pairs)} / {len(AF_gens_32)**2}")
if oz_fail_pairs:
    print("    Sample violations:")
    for ni, nj, err in sorted(oz_fail_pairs, key=lambda x: -x[2])[:10]:
        print(f"      [{ni}, o({nj})]: {err:.4f}")

# Test 5: Independence and dimension
print("\n  Test: Real dimension of A_F generator span?")
AF_vecs = [np.concatenate([T.flatten().real, T.flatten().imag]) for T in AF_gens_32]
AF_mat = np.column_stack(AF_vecs)
AF_rank = np.linalg.matrix_rank(AF_mat, tol=1e-8)
print(f"    Rank: {AF_rank} (target: 24 for A_F)")


# =============================================================================
# PART 9: SUMMARY AND ASSESSMENT
# =============================================================================

print("\n" + "=" * 72)
print("[PART 9] SUMMARY AND ASSESSMENT")
print("=" * 72)

print(f"""
PHASE 2b RESULTS
================

STAGE 1: Generator closure approach
  L + H algebraic closure: dim = {d_AF} (target: 24) -- TOO LARGE
  Order-zero on closure: VIOLATED ({max_o0:.2e})
  Maximal order-zero set (alternating proj): dim = {d_S_cur} -- TOO SMALL
  Wedderburn of closure: {len(wd_factors)} factors, center={center_dim}

STAGE 2: Direct Connes A_F construction
  Generators built: {len(AF_gens_16)}
  In R_u(2) commutant: {n_pass}/{len(AF_gens_16)}
  J-compatible: {n_pass_J}/{len(AF_gens_16)}
  Quaternion relations: {'PASS' if new_quat_pass else 'FAIL'}
  Order-zero violations: {len(oz_fail_pairs)}/{len(AF_gens_32)**2}
  Real dimension: {AF_rank}
""")

if n_fail == 0 and n_fail_J == 0 and len(oz_fail_pairs) == 0 and AF_rank == 24:
    print("VERDICT: DECISIVE SUCCESS")
    print("A_F = C + H + M_3(C) with Connes' representation matches Baptista's KK geometry!")
elif n_fail > 0:
    print(f"VERDICT: PARTIAL FAILURE -- {n_fail} generators not in commutant")
    print("This means A_F as constructed conflicts with R_u(2) gauge structure.")
    print("Generators that fail indicate where Baptista's geometry DIFFERS from Connes.")
elif len(oz_fail_pairs) > 0:
    print("VERDICT: A_F in commutant but order-zero VIOLATED")
    print("The Connes representation exists within Baptista's geometry but the")
    print("opposite algebra condition [a, JbJ^{-1}] = 0 fails for some generators.")
else:
    print(f"VERDICT: PARTIAL SUCCESS -- order-zero passes but dim = {AF_rank}")

print("\n" + "=" * 72)
print("PHASE 2b COMPUTATION COMPLETE")
print("=" * 72)

print(f"""
PHASE 2b RESULTS
================

1. R_u(2) J-compatible commutant: dim = {d_orth}

2. L_su(3) generators: IN commutant ({max_L_resid:.2e})
   Algebraic closure of L + I: dim = {d_L_closure}

3. H quaternion generators: IN commutant ({max_H_resid:.2e})
   Quaternion relations: {'PASS' if quat_pass else 'FAIL (j^2, k^2 fail on RH sector)'}

4. Combined L + H closure: dim = {d_AF} (A_F target: 24)
   o-stable: YES (o^2=I, +1 eigenspace: 20, -1 eigenspace: 20)
   Wedderburn: {len(wd_factors)} factors, ranks = {[f['alg_rank'] for f in wd_factors]}

5. Order-zero on full closure: VIOLATED ({max_o0:.2e})

6. Maximal order-zero set (alternating projection): dim = {d_S_cur}
""")

if d_S_cur >= 24:
    # Check if we found something
    if 'max_oz_alg' in dir() and max_oz_alg < 1e-6:
        if d_Salg == 24:
            print("VERDICT: DECISIVE SUCCESS")
            print("A_F = C + H + M_3(C) extracted from Baptista's KK geometry!")
        else:
            print(f"VERDICT: PARTIAL SUCCESS (dim = {d_Salg}, order-zero passes)")
    else:
        print(f"VERDICT: PARTIAL -- order-zero set found (dim {d_S_cur})")
elif d_S_cur > 0:
    print(f"VERDICT: PARTIAL -- order-zero set dim = {d_S_cur} (need 24)")
    print("The alternating projection converges too quickly.")
    print("This suggests the o-map mixes factors in a way that prevents")
    print("simple extraction. Phase 2.5 (order-ONE with Dirac operator) needed.")
else:
    print("VERDICT: ORDER-ZERO SET EMPTY within this closure.")
    print("The L + H generators do NOT form an order-zero algebra.")
    print("Phase 2.5: Need Dirac operator D_F to impose order-ONE condition.")

print("\n" + "=" * 72)
print("PHASE 2b COMPUTATION COMPLETE")
print("=" * 72)
