"""
Session 23a Step 2: Kosmann matrix elements in the (0,0) singlet sector.

Computes the CORRECT Kosmann spinorial correction K_a for the
Jensen-deformed SU(3), using the antisymmetric covariant derivative
formula from Baptista Paper 17, eq 4.1:

    K_a = -(1/8) sum_{r,s} [Gamma^s_{ra} - Gamma^r_{sa}] gamma_r gamma_s

where Gamma^b_{ca} are the Levi-Civita connection coefficients in the ON frame,
and a indexes the direction of the Lie derivative.

CRITICAL DISTINCTION from Session 22b:
    - s22b used (L_{e_a} g)^{jk} = Gamma^k_{ja} + Gamma^j_{ka} (SYMMETRIC part)
    - The correct Kosmann formula uses Gamma^s_{ra} - Gamma^r_{sa} (ANTISYMMETRIC part)
    - The symmetric part is the metric Lie derivative; the antisymmetric part is
      the endomorphism g^{-1}(nabla . X) - (nabla . X)^T, which measures the
      ROTATION part of the covariant derivative of X.
    - For Killing vectors: both parts vanish (nabla_{(r} X_{s)} = 0).
    - For non-Killing vectors: the symmetric part gives (L_X g) and the
      antisymmetric part gives the Kosmann correction.

Physical interpretation:
    The antisymmetric part A_{rs}^a = Gamma^s_{ra} - Gamma^r_{sa} measures
    the ROTATION generated by the covariant derivative of e_a. This is
    the infinitesimal rotation that the frame experiences when parallel-
    transported along e_a, minus the coordinate contribution. For Killing
    fields this vanishes; for non-Killing fields it gives the spinorial
    coupling that enters the BCS gap equation.

For the Jensen metric on SU(3):
    - U(2) directions (a = 0,1,2,7): Killing => K_a = 0
    - C^2 directions (a = 3,4,5,6): non-Killing => K_a != 0

The (0,0) singlet sector has D_pi = Omega (16x16 spinor space). Its 16
eigenstates are used to compute the matrix elements <n|K_a|m>.

Output: tier0-computation/s23a_kosmann_singlet.npz
    Keys:
        tau_values: (9,)
        K_a_matrices_{i}_{a}: (16,16) complex, K_a in eigenbasis at tau_i
        K_a_norms_{i}: (8,) float, Frobenius norms
        eigenvalues_{i}: (16,) float, singlet eigenvalues
        A_antisym_{i}_{a}: (8,8) float, antisymmetric part A^a_{rs}

Author: phonon-exflation-sim (Session 23a)
Date: 2026-02-20
"""

import sys
import os
import time
import numpy as np
from scipy.linalg import eigh

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, SCRIPT_DIR)

from tier1_dirac_spectrum import (
    su3_generators,
    compute_structure_constants,
    compute_killing_form,
    jensen_metric,
    orthonormal_frame,
    frame_structure_constants,
    connection_coefficients,
    spinor_connection_offset,
    build_cliff8,
    validate_clifford,
    validate_omega_hermitian,
    validate_connection,
    U1_IDX, SU2_IDX, C2_IDX, U2_IDX,
)


TAU_VALUES = np.array([0.0, 0.10, 0.15, 0.20, 0.25, 0.30, 0.35, 0.40, 0.50])


def kosmann_operator_antisymmetric(Gamma, gammas, a):
    """
    Compute the Kosmann spinorial correction K_a using the ANTISYMMETRIC
    covariant derivative formula (Baptista Paper 17, eq 4.1).

    K_a = -(1/8) sum_{r,s} [Gamma^s_{ra} - Gamma^r_{sa}] gamma_r gamma_s

    where Gamma^b_{ca} are connection coefficients: nabla_{e_c} e_a = Gamma^b_{ca} e_b.

    The antisymmetric tensor A^a_{rs} = Gamma^s_{ra} - Gamma^r_{sa} vanishes
    when e_a is Killing (because nabla_{(r} X_{s)} = 0 => nabla is antisymmetric
    in (r,s) after lowering, which means Gamma^s_{ra} = -Gamma^r_{sa} already
    from metric compatibility... wait, that would make A = 2*Gamma, not zero).

    Let me re-derive carefully:
    - Metric compatibility: Gamma^c_{ab} = -Gamma^b_{ac} (antisymmetric in upper + 2nd lower)
    - Torsion-free: Gamma^c_{ab} - Gamma^c_{ba} = ft^c_{ab} (structure constants)

    For a Killing field e_a:
        (L_{e_a} g)(e_r, e_s) = Gamma^s_{ra} + Gamma^r_{sa} = 0

    The antisymmetric part:
        A^a_{rs} = Gamma^s_{ra} - Gamma^r_{sa}

    Using metric compatibility Gamma^s_{ra} = -Gamma^r_{as}... wait, that's
    Gamma^{upper}_{lower lower}. Let me be very explicit:

    Gamma^b_{ca} means: (nabla_{e_c} e_a) = Gamma^b_{ca} e_b
    Index order: Gamma[upper_b, lower_c, lower_a]

    Metric compatibility: Gamma^b_{ca} + Gamma^a_{cb} = 0
    i.e., Gamma[b,c,a] = -Gamma[a,c,b]

    Now A^a_{rs} = Gamma^s_{ra} - Gamma^r_{sa}
                 = Gamma[s,r,a] - Gamma[r,s,a]

    This is the antisymmetric part of Gamma[.,.,a] in the first two indices.

    For Killing e_a:
        Gamma[s,r,a] + Gamma[r,s,a] = 0  (metric Lie derivative zero -- WRONG)

    Wait, the Killing condition is:
        (L_{e_a} g)(e_r, e_s) = g(nabla_{e_r} e_a, e_s) + g(e_r, nabla_{e_s} e_a)
                                = Gamma^s_{ra} + Gamma^r_{sa}    [in ON frame]
                                = Gamma[s,r,a] + Gamma[r,s,a] = 0

    So for Killing: Gamma[s,r,a] = -Gamma[r,s,a]
    => A^a_{rs} = Gamma[s,r,a] - Gamma[r,s,a] = Gamma[s,r,a] - (-Gamma[s,r,a]) = 2*Gamma[s,r,a]

    This means the antisymmetric part does NOT vanish for Killing fields!

    Hmm. Let me re-read the Kosmann formula. From Paper 17 eq 4.1:

    L_X psi = nabla_X psi + (1/8) g^{ir} g^{js}
              [g(nabla_{v_i} X, v_j) - g(nabla_{v_j} X, v_i)] v_r v_s psi

    Actually checking the signs: the paper uses a specific convention.

    g(nabla_{v_i} X, v_j) = g(Gamma^k_{i,X} v_k, v_j) = Gamma^j_{i,X}

    Wait, X = e_a, so nabla_{v_i} e_a = Gamma^k_{ia} v_k, and
    g(nabla_{v_i} e_a, v_j) = Gamma^j_{ia} = Gamma[j,i,a]

    So the bracket is:
        g(nabla_{v_i} e_a, v_j) - g(nabla_{v_j} e_a, v_i) = Gamma[j,i,a] - Gamma[i,j,a]

    And the operator is:
        K_a = (1/8) sum_{i,j} [Gamma[j,i,a] - Gamma[i,j,a]] * g^{ir} g^{js} * gamma_r * gamma_s

    In ON frame, g^{ir} = delta^{ir}, g^{js} = delta^{js}, so:
        K_a = (1/8) sum_{r,s} [Gamma[s,r,a] - Gamma[r,s,a]] * gamma_r * gamma_s

    (renamed i->r, j->s for clarity)

    Now for CLOSING e_a: Gamma[s,r,a] + Gamma[r,s,a] = 0 => Gamma[s,r,a] = -Gamma[r,s,a]
    => bracket = Gamma[s,r,a] - Gamma[r,s,a] = -Gamma[r,s,a] - Gamma[r,s,a] = -2*Gamma[r,s,a]

    This is NOT zero! For Killing vectors, the Kosmann correction should reduce to the
    standard spin connection term (since Killing vectors generate isometries).

    Actually, the FULL Kosmann-Lichnerowicz derivative is:
        L_X psi = nabla_X psi + K_a psi

    For an isometry (Killing X), L_X should reduce to the standard action of the
    isometry on spinors: L_X psi = X(psi) + (1/4) omega_{ab}(X) gamma^a gamma^b psi
    where omega_{ab}(X) = Gamma_{abX} - Gamma_{baX} is antisymmetric.

    The nabla_X psi term is: nabla_X psi = X(psi) + (1/4) Gamma_{bc,X} gamma^b gamma^c psi
    (using the spin connection).

    Wait, I think I have the connection coefficient index order confused.
    Let me standardize:

    nabla_{e_a} e_b = Gamma^c_{ab} e_c   [convention: nabla_first second = Gamma^result_first_second]

    So: Gamma^c_{ab} = (nabla_{e_a} e_b)^c

    Metric compatibility: Gamma^c_{ab} + Gamma^b_{ac} = 0
    (swap upper with one lower, holding the nabla-direction fixed)

    Actually wait. Metric compatibility is:
    0 = nabla_{e_a} g(e_b, e_c) = g(nabla_{e_a} e_b, e_c) + g(e_b, nabla_{e_a} e_c)
    = Gamma^d_{ab} delta_{dc} + Gamma^d_{ac} delta_{db}
    = Gamma^c_{ab} + Gamma^b_{ac}

    So: Gamma[c, a, b] + Gamma[b, a, c] = 0 where indices are [upper, 1st_lower, 2nd_lower]

    This means Gamma is antisymmetric in (upper, 2nd_lower) when the 1st_lower is fixed:
    Gamma^c_{ab} = -Gamma^b_{ac}

    OK. Now for the Kosmann formula with X = e_a:
    g(nabla_{v_r} e_a, v_s) = Gamma^s_{ra}  [= Gamma[s, r, a]]

    Bracket: Gamma[s,r,a] - Gamma[r,s,a]

    Using metric compat: Gamma[s,r,a] = -Gamma[a,r,s]
    So: bracket = -Gamma[a,r,s] - Gamma[r,s,a]

    Hmm, this doesn't simplify nicely. Let me just compute it numerically.

    Parameters:
        Gamma: (8,8,8) connection coefficients, Gamma[c,a,b] = Gamma^c_{ab}
        gammas: list of 8 Clifford generators (16x16)
        a: direction index for the Kosmann derivative

    Returns:
        K_a: (16,16) complex matrix (Kosmann spinorial correction)
        A_antisym: (8,8) float, the antisymmetric tensor A^a_{rs}
    """
    dim_spin = gammas[0].shape[0]
    K = np.zeros((dim_spin, dim_spin), dtype=complex)
    A_antisym = np.zeros((8, 8), dtype=np.float64)

    for r in range(8):
        for s in range(8):
            # A^a_{rs} = Gamma^s_{ra} - Gamma^r_{sa}
            # In our array convention: Gamma[upper, 1st_lower, 2nd_lower]
            # Gamma^s_{ra} = Gamma[s, r, a]
            # Gamma^r_{sa} = Gamma[r, s, a]
            A_rs = Gamma[s, r, a] - Gamma[r, s, a]
            A_antisym[r, s] = A_rs
            if abs(A_rs) > 1e-15:
                K += A_rs * (gammas[r] @ gammas[s])

    K *= (1.0 / 8.0)

    return K, A_antisym


def kosmann_operator_symmetric(Gamma, gammas, a):
    """
    Compute the SYMMETRIC metric Lie derivative operator (what s22b used).

    S_a = (1/4) sum_{r,s} [Gamma^s_{ra} + Gamma^r_{sa}] gamma_r gamma_s
        = (1/4) (L_{e_a} g)^{rs} gamma_r gamma_s

    This is the WRONG operator for the Kosmann derivative but useful for
    comparison and validation.

    Parameters:
        Gamma: connection coefficients
        gammas: Clifford generators
        a: direction index

    Returns:
        S_a: (16,16) complex matrix
        Lg_sym: (8,8) float, the symmetric tensor (L_{e_a} g)_{rs}
    """
    dim_spin = gammas[0].shape[0]
    S = np.zeros((dim_spin, dim_spin), dtype=complex)
    Lg_sym = np.zeros((8, 8), dtype=np.float64)

    for r in range(8):
        for s in range(8):
            L_rs = Gamma[s, r, a] + Gamma[r, s, a]
            Lg_sym[r, s] = L_rs
            if abs(L_rs) > 1e-15:
                S += L_rs * (gammas[r] @ gammas[s])

    S *= 0.25

    return S, Lg_sym


def extract_singlet_eigensystem(tau, gens, f_abc, gammas):
    """
    Extract eigenvalues and eigenvectors of D_K in the (0,0) singlet sector.

    In the trivial irrep (0,0), dim=1, so D_pi = I_1 x Omega = Omega (16x16).
    We diagonalize H = 1j * Omega (Hermitian) using eigh.

    Parameters:
        tau: Jensen deformation parameter
        gens: SU(3) generators
        f_abc: structure constants
        gammas: Cliff(8) gamma matrices

    Returns:
        evals: (16,) real eigenvalues of (1j * D)
        evecs: (16,16) unitary, columns = eigenvectors
        Gamma: (8,8,8) connection coefficients
        E: (8,8) orthonormal frame
    """
    B_ab = compute_killing_form(f_abc)
    g_s = jensen_metric(B_ab, tau)
    E = orthonormal_frame(g_s)
    ft = frame_structure_constants(f_abc, E)
    Gamma = connection_coefficients(ft)
    Omega = spinor_connection_offset(Gamma, gammas)

    # Verify anti-Hermiticity
    ah_err = np.max(np.abs(Omega + Omega.conj().T))

    # Diagonalize
    H = 1j * Omega
    h_err = np.max(np.abs(H - H.conj().T))

    evals, evecs = eigh(H)

    return evals, evecs, Gamma, E, ah_err, h_err


def compute_kosmann_matrix_elements(evecs, K_a):
    """
    Project the Kosmann operator K_a into the eigenbasis of D_K.

    K_a^{nm} = <n|K_a|m> = (evecs^dag @ K_a @ evecs)_{nm}

    Parameters:
        evecs: (16,16) unitary, columns = eigenvectors
        K_a: (16,16) Kosmann operator in spinor basis

    Returns:
        K_eig: (16,16) complex, K_a in eigenbasis
    """
    return evecs.conj().T @ K_a @ evecs


def run_extraction():
    """Main computation: Kosmann matrix elements in (0,0) singlet sector."""
    print("=" * 70)
    print("Session 23a Step 2: Kosmann Matrix Elements in (0,0) Singlet")
    print("=" * 70)
    print(f"Tau values: {TAU_VALUES}")
    print(f"Kosmann formula: K_a = (1/8) sum_{{r,s}} [Gamma^s_{{ra}} - Gamma^r_{{sa}}] gamma_r gamma_s")
    print(f"Directions: a = 3,4,5,6 (C^2 non-Killing) + a = 0,1,2,7 (u(2) Killing, expect K~0)")
    print()

    # Initialize infrastructure
    gens = su3_generators()
    f_abc = compute_structure_constants(gens)
    gammas = build_cliff8()

    cliff_err = validate_clifford(gammas)
    print(f"Clifford validation: max_err = {cliff_err:.2e}")

    # Storage
    npz_data = {"tau_values": TAU_VALUES}
    results = []

    t_total = time.time()

    for idx, tau in enumerate(TAU_VALUES):
        t_start = time.time()
        print(f"\n{'='*60}")
        print(f"tau = {tau:.2f}  ({idx+1}/{len(TAU_VALUES)})")
        print(f"{'='*60}")

        # 1. Extract singlet eigensystem
        evals, evecs, Gamma, E, ah_err, h_err = extract_singlet_eigensystem(
            tau, gens, f_abc, gammas
        )
        print(f"  D_K singlet: anti-Herm err = {ah_err:.2e}, Herm(1j*D) err = {h_err:.2e}")
        print(f"  Eigenvalues (1j*D): [{evals[0]:.6f}, ..., {evals[-1]:.6f}]")
        print(f"  |lambda| range: [{np.min(np.abs(evals)):.6f}, {np.max(np.abs(evals)):.6f}]")

        # Verify connection metric compatibility
        mc_err = validate_connection(Gamma)
        print(f"  Connection metric-compat err: {mc_err:.2e}")

        npz_data[f"eigenvalues_{idx}"] = evals
        npz_data[f"eigenvectors_{idx}"] = evecs

        # 2. Compute Kosmann operators for ALL 8 directions
        K_norms = np.zeros(8)
        K_antisym_norms = np.zeros(8)
        S_sym_norms = np.zeros(8)

        print(f"\n  {'Dir':>4s}  {'Type':>8s}  {'||K_a||':>12s}  {'||S_a||':>12s}  "
              f"{'||A_antisym||':>14s}  {'K Herm?':>8s}  {'K anti-H?':>10s}")
        print(f"  {'-'*80}")

        for a in range(8):
            # Correct Kosmann (antisymmetric)
            K_a, A_antisym = kosmann_operator_antisymmetric(Gamma, gammas, a)

            # Symmetric (metric Lie derivative) for comparison
            S_a, Lg_sym = kosmann_operator_symmetric(Gamma, gammas, a)

            K_norm = np.sqrt(np.sum(np.abs(K_a)**2))
            S_norm = np.sqrt(np.sum(np.abs(S_a)**2))
            A_norm = np.sqrt(np.sum(A_antisym**2))

            K_norms[a] = K_norm
            K_antisym_norms[a] = A_norm
            S_sym_norms[a] = S_norm

            # Check Hermiticity
            k_h_err = np.max(np.abs(K_a - K_a.conj().T))
            k_ah_err = np.max(np.abs(K_a + K_a.conj().T))
            k_type = "Herm" if k_h_err < 1e-10 else ("anti-H" if k_ah_err < 1e-10 else "MIXED")

            dir_type = "Killing" if a in U2_IDX else "C^2"

            print(f"  {a:>4d}  {dir_type:>8s}  {K_norm:12.6e}  {S_norm:12.6e}  "
                  f"{A_norm:14.6e}  {k_h_err:8.2e}  {k_ah_err:10.2e}  [{k_type}]")

            # Store the antisymmetric tensor
            npz_data[f"A_antisym_{idx}_{a}"] = A_antisym

            # 3. Project K_a into eigenbasis
            K_eig = compute_kosmann_matrix_elements(evecs, K_a)
            npz_data[f"K_a_matrix_{idx}_{a}"] = K_eig

            # Also store the symmetric operator for comparison
            S_eig = compute_kosmann_matrix_elements(evecs, S_a)
            npz_data[f"S_a_matrix_{idx}_{a}"] = S_eig

        npz_data[f"K_norms_{idx}"] = K_norms
        npz_data[f"S_norms_{idx}"] = S_sym_norms

        # 4. Summary for C^2 directions
        c2_K_total = np.sqrt(np.sum(K_norms[C2_IDX]**2))
        c2_S_total = np.sqrt(np.sum(S_sym_norms[C2_IDX]**2))
        u2_K_total = np.sqrt(np.sum(K_norms[U2_IDX]**2))

        print(f"\n  Total ||K|| over C^2: {c2_K_total:.6e}")
        print(f"  Total ||S|| over C^2: {c2_S_total:.6e} (metric Lie derivative, for comparison)")
        print(f"  Total ||K|| over u(2): {u2_K_total:.6e} (should NOT be zero for Killing)")

        # 5. Display gap-edge K_a matrix elements (2x2 block for gap-edge pair)
        abs_evals = np.abs(evals)
        sorted_indices = np.argsort(abs_evals)
        gap_edge_idx = sorted_indices[:2]  # two smallest |lambda| modes

        print(f"\n  Gap-edge modes: indices {gap_edge_idx}, "
              f"|lambda| = [{abs_evals[gap_edge_idx[0]]:.6f}, {abs_evals[gap_edge_idx[1]]:.6f}]")

        for a in C2_IDX:
            K_eig = npz_data[f"K_a_matrix_{idx}_{a}"]
            K_gap = K_eig[np.ix_(gap_edge_idx, gap_edge_idx)]
            print(f"  K_{a} gap-edge 2x2:")
            for i in range(2):
                for j in range(2):
                    val = K_gap[i, j]
                    print(f"    [{i},{j}] = {val.real:+.6e} + {val.imag:+.6e}j  "
                          f"(|.| = {abs(val):.6e})")

        # Store gap-edge info
        npz_data[f"gap_edge_indices_{idx}"] = gap_edge_idx

        elapsed = time.time() - t_start
        print(f"\n  Completed in {elapsed:.2f}s")

        results.append({
            'tau': tau,
            'evals': evals.copy(),
            'K_norms': K_norms.copy(),
            'gap_edge_idx': gap_edge_idx.copy(),
        })

    total_elapsed = time.time() - t_total
    print(f"\n{'='*70}")
    print(f"Total extraction time: {total_elapsed:.1f}s")
    print(f"{'='*70}")

    # ================================================================
    # K-0 GATE: Are all K_a matrix elements zero?
    # ================================================================
    print(f"\n{'='*70}")
    print("K-0 GATE: Kosmann Matrix Elements Zero?")
    print(f"{'='*70}")

    all_zero = True
    max_K_element = 0.0
    max_K_gap_element = 0.0

    for idx, tau in enumerate(TAU_VALUES):
        for a in C2_IDX:
            K_eig = npz_data[f"K_a_matrix_{idx}_{a}"]
            max_elem = np.max(np.abs(K_eig))
            max_K_element = max(max_K_element, max_elem)

            # Gap-edge elements
            gap_idx = npz_data[f"gap_edge_indices_{idx}"]
            K_gap = K_eig[np.ix_(gap_idx, gap_idx)]
            max_gap = np.max(np.abs(K_gap))
            max_K_gap_element = max(max_K_gap_element, max_gap)

            if max_elem > 1e-10:
                all_zero = False

    print(f"  Max |K_a^{{nm}}| over all tau, a, n, m: {max_K_element:.6e}")
    print(f"  Max |K_a^{{nm}}| gap-edge only: {max_K_gap_element:.6e}")

    if all_zero:
        print(f"\n  *** K-0 GATE: CLOSED ***")
        print(f"  All Kosmann matrix elements are zero to numerical precision.")
        print(f"  Gap equation has NO pairing interaction. Identically trivial.")
        print(f"  SESSION REDEFINES to P2 initiation.")
    else:
        print(f"\n  K-0 GATE: PASSED (matrix elements nonzero)")
        print(f"  Pairing interaction exists. Gap equation computation proceeds.")

    # ================================================================
    # SUMMARY TABLE
    # ================================================================
    print(f"\n{'='*70}")
    print("SUMMARY: Kosmann Correction Norms")
    print(f"{'='*70}")
    print(f"{'tau':>6s}  {'||K_3||':>10s}  {'||K_4||':>10s}  {'||K_5||':>10s}  {'||K_6||':>10s}  "
          f"{'Total C2':>10s}  {'gap max|K|':>12s}")
    for idx, tau in enumerate(TAU_VALUES):
        norms = npz_data[f"K_norms_{idx}"]
        total = np.sqrt(np.sum(norms[C2_IDX]**2))
        gap_idx = npz_data[f"gap_edge_indices_{idx}"]
        gap_max = 0.0
        for a in C2_IDX:
            K_eig = npz_data[f"K_a_matrix_{idx}_{a}"]
            K_gap = K_eig[np.ix_(gap_idx, gap_idx)]
            gap_max = max(gap_max, np.max(np.abs(K_gap)))
        print(f"{tau:6.2f}  {norms[3]:10.6e}  {norms[4]:10.6e}  {norms[5]:10.6e}  "
              f"{norms[6]:10.6e}  {total:10.6e}  {gap_max:12.6e}")

    # ================================================================
    # COMPARISON: Antisymmetric (correct) vs Symmetric (wrong, s22b)
    # ================================================================
    print(f"\n{'='*70}")
    print("COMPARISON: Antisymmetric (Kosmann) vs Symmetric (Lie derivative)")
    print(f"{'='*70}")
    print(f"{'tau':>6s}  {'||K_anti|| C2':>14s}  {'||S_sym|| C2':>14s}  {'ratio K/S':>10s}")
    for idx, tau in enumerate(TAU_VALUES):
        K_n = npz_data[f"K_norms_{idx}"]
        S_n = npz_data[f"S_norms_{idx}"]
        K_total = np.sqrt(np.sum(K_n[C2_IDX]**2))
        S_total = np.sqrt(np.sum(S_n[C2_IDX]**2))
        ratio = K_total / S_total if S_total > 1e-15 else float('inf')
        print(f"{tau:6.2f}  {K_total:14.6e}  {S_total:14.6e}  {ratio:10.4f}")

    # Save
    output_path = os.path.join(SCRIPT_DIR, "s23a_kosmann_singlet.npz")
    np.savez_compressed(output_path, **npz_data)
    file_size_mb = os.path.getsize(output_path) / (1024 * 1024)
    print(f"\nSaved: {output_path}")
    print(f"File size: {file_size_mb:.1f} MB")

    return output_path, all_zero


if __name__ == "__main__":
    output, k0_fired = run_extraction()
    print(f"\nDone. Output at: {output}")
    if k0_fired:
        print("*** K-0 GATE CLOSED: No pairing interaction ***")
    else:
        print("K-0 GATE PASSED: Pairing interaction exists.")
