#!/usr/bin/env python3
"""
_s74_w4y_writer.py — atomic edit of the W4-Y section in the S74 working paper.

Replaces the NOT-STARTED placeholder with the full harmonic-analytic SPT
classification write-up. Runs as a single read-modify-write so that concurrent
appends to the file do not race with the edit.
"""
import io
import os
import sys

PATH = r"C:\sandbox\Ainulindale Exflation\sessions\archive\session-74\session-74-results-workingpaper.md"

OLD = (
    "### W4-Y: HARMONIC-SPT-CLASSIFICATION-74 -- Harmonic-Analytic SPT Protection "
    "(van-den-dungen-bridge-theorist)\n"
    "\n"
    "**Status**: NOT STARTED\n"
    "**Gate**: `HARMONIC-SPT-CLASSIFICATION-74`. PASS if classification is complete "
    "AND distinguishable from solid-state SPT. INFO if partial. FAIL if "
    "indistinguishable.\n"
    "\n"
    "**Results**:\n"
    "\n"
    "*(Agent writes here)*\n"
)

NEW = (
    "### W4-Y: HARMONIC-SPT-CLASSIFICATION-74 -- Harmonic-Analytic SPT Protection "
    "(van-den-dungen-bridge-theorist)\n"
    "\n"
    "**Status**: COMPLETE\n"
    "**Gate**: `HARMONIC-SPT-CLASSIFICATION-74`. PASS if classification is complete "
    "AND distinguishable from solid-state SPT. INFO if partial. FAIL if "
    "indistinguishable.\n"
    "\n"
    "**Carry-forward source**: S73B landau-baptista workshop carry-forward item #9 "
    "(CV4 + Q-B2). Landau identified the (0,0)-sector protection as an algebraic "
    "SPT phase with no direct condensed-matter analog; Baptista accepted the "
    "characterization as a permanent structural finding. This W4-Y write-up "
    "formalises the category as a new entry in the framework's symmetry-protection "
    "taxonomy.\n"
    "\n"
    "**Script**: `computations/session-74/s74_harmonic_spt_classification.py`\n"
    "**Data**: `computations/session-74/s74_harmonic_spt_classification.npz` (15 keys, 39 KB)\n"
    "**Log**: `computations/_shared/_s74_harmonic_spt_classification.log` (131 lines)\n"
    "\n"
    "**Results**:\n"
    "\n"
    "**Numerical summary** (numbers first):\n"
    "\n"
    "| Quantity | Value |\n"
    "|:---|---:|\n"
    "| Gate verdict | **PASS** |\n"
    "| PASS criteria satisfied | 5 / 5 |\n"
    "| Axioms in the category (HA-SPT) | 10 |\n"
    "| Axioms distinguishing HA-SPT from solid-state SPT | **8 / 10** |\n"
    "| Axioms shared with solid-state SPT | 2 / 10 |\n"
    "| Framework theorems mapped into the category | **11** |\n"
    "| Protection-role theorems | 9 |\n"
    "| Invariant-role theorems | 2 |\n"
    "| Axioms covered by mapped theorems | 10 / 10 |\n"
    "| Altland-Zirnbauer classes tabulated | 10 |\n"
    "| HA-SPT 4-bit signature | (0, 0, 0, 0) |\n"
    "| Minimum Hamming distance to any AZ class | **4 / 4** |\n"
    "| Peter-Weyl sum dim(p,q)^2 at L_max=3 | 805 |\n"
    "| Plancherel weight of (0,0) sector W_(0,0) | 1.242236e-03 (= 1/805) |\n"
    "| Kasparov pairing index I_(0,0) | 0 (constant across 20 tau) |\n"
    "| Named pair invariant (I, W) | (0, 1/805) |\n"
    "| Precision of the load-bearing block-diagonality theorem | 8.4e-15 |\n"
    "| Precision of [J, D_K]=0 theorem | 3.29e-13 |\n"
    "| Precision of Kasparov factorisation K1-K5 | 2.2e-16 |\n"
    "| NPZ keys persisted | 15 |\n"
    "\n"
    "**Classification scheme (HA-SPT: Harmonic-Analytic Symmetry-Protected)**\n"
    "\n"
    "The category is defined by ten axioms, each with an HA-SPT value (1 = holds "
    "for harmonic-analytic SPT) and an SS-SPT value (1 = holds for at least one "
    "solid-state SPT class in the Altland-Zirnbauer 10-fold way). The "
    "distinguishing axioms are the ones where HA-SPT and SS-SPT disagree.\n"
    "\n"
    "| # | Axiom | Statement | HA | SS | Role |\n"
    "|:---|:------|:----------|:---:|:---:|:---|\n"
    "| AX1 | Substrate | Ambient object is a spectral triple (A,H,D,J,gamma), not a "
    "lattice Hamiltonian on site-mode Hilbert space | 1 | 0 | DISTINGUISHING |\n"
    "| AX2 | ProtectingGroupAction | Right regular action R_g of compact Lie group "
    "K on L^2(K,S), with [R_g, D_K]=0 | 1 | 0 | DISTINGUISHING |\n"
    "| AX3 | SpatialContent | Protecting symmetry has NO spacetime realisation (no "
    "M^4 coordinate action, no fermion number, no T/P) | 1 | 0 | DISTINGUISHING |\n"
    "| AX4 | DecompositionTheorem | L^2(K,S) splits by Peter-Weyl into direct sum "
    "of dim(p,q)^2-blocks; group action preserves it | 1 | 0 | DISTINGUISHING |\n"
    "| AX5 | SchurSelection | Schur's lemma forces any R_g-commuting operator "
    "block-diagonal; D_K block-diagonal for any left-invariant metric | 1 | 0 | "
    "DISTINGUISHING |\n"
    "| AX6 | CPTCompatibility | Connes real structure J satisfies [J,D_K]=0 with "
    "J^2=+I in KO-dim=6; real-symmetric protected sub-block | 1 | 1 | SHARED |\n"
    "| AX7 | Invariant | Topological label is the PAIR (Kasparov index I_(0,0), "
    "Plancherel weight W_(0,0)=1/sum dim^2) | 1 | 0 | DISTINGUISHING |\n"
    "| AX8 | Stability | Protection survives any D_K deformation preserving "
    "left-invariance and J. Jensen deformation is admissible | 1 | 1 | SHARED |\n"
    "| AX9 | EdgelessProtection | NO boundary/edge theorem. Protection is "
    "BULK-ONLY on a representation-theoretic sector, not an edge mode | 1 | 0 | "
    "DISTINGUISHING |\n"
    "| AX10 | HomogeneousFibreDependence | Category is obstructed on "
    "non-homogeneous fibres; available ONLY on compact Lie groups K or cosets "
    "G/H | 1 | 0 | DISTINGUISHING |\n"
    "\n"
    "Eight of ten axioms distinguish HA-SPT from solid-state SPT. The two shared "
    "axioms (AX6 CPTCompatibility, AX8 Stability) capture the features of "
    "solid-state SPT that lift to the harmonic setting without modification: the "
    "Connes real structure plays the role of the AZ antiunitary (C,T,S), and the "
    "deformation-stability inside a symmetry class is common to both.\n"
    "\n"
    "**Mapped framework theorems (11 total)**\n"
    "\n"
    "| ID | Theorem | Precision | Axes | Role |\n"
    "|:---|:--------|:----------|:-----|:---|\n"
    "| T-BD-UNIV | D_K Block-Diagonality Universality (PR#1, S22b) | 8.4e-15 | "
    "AX2, AX4, AX5 | protection |\n"
    "| T-JDK | [J, D_K]=0 over 79,968 matrix elements (PR II row 121) | 3.29e-13 "
    "| AX6 | protection |\n"
    "| T-JSQ | J^2=+I in KO-dim=6 (Connes sign triple +,+,-) | 1e-15 | AX6 | "
    "protection |\n"
    "| T-PW-INDEX | KASPAROV-VERIFY-61 factorisation K1-K5 on Jensen SU(3) | "
    "2.2e-16 | AX7 | **invariant** |\n"
    "| T-CF9 | CF-9 Triple Identity Berry=NCG=KK (PR#17, S62) | 2e-14 | AX1, AX3, "
    "AX7 | **invariant** |\n"
    "| T-ST-KASP | Scalar-Tensor Kasparov Decoupling (PR#T3, S63) | structural | "
    "AX3 | protection |\n"
    "| T-FS-LOCK | Fermi-surface lock v^2(B2[0])=1/2 (PR#31, S64 W2-C) | 1e-15 | "
    "AX2, AX5, AX9 | protection |\n"
    "| T-JENSEN-BD | Jensen block stability at all tau in [0, tau_fold] | 1e-13 | "
    "AX8 | protection |\n"
    "| T-3PHON-PERM | Three-phonon vertex suppression L_max-invariant (W5-D) | "
    "structural | AX5, AX9 | protection |\n"
    "| T-WILSON | Wilson loop triviality on (0,0); Berry Omega=0 (1.12e-16) | "
    "1.12e-16 | AX5, AX9 | protection |\n"
    "| T-HOMOGENEITY | Schur protection requires homogeneous fibre (Re:L3) | "
    "structural | AX10 | protection |\n"
    "\n"
    "All 10 axioms are covered by at least one mapped theorem (no uncovered "
    "axis). The two invariant-role theorems (T-PW-INDEX, T-CF9) carry the "
    "harmonic-analytic topological invariant; the remaining nine are "
    "protection-role theorems that enforce the axiomatic structure.\n"
    "\n"
    "**Signature distance to Altland-Zirnbauer 10-fold way**\n"
    "\n"
    "Each AZ class is tabulated along the four axes (lattice formulation, "
    "spacetime symmetry, K-theory classification, edge-mode theorem). Every AZ "
    "class has value 1 on all four axes. HA-SPT has value 0 on all four. Hamming "
    "distance to any AZ row is therefore the maximum possible distance of 4.\n"
    "\n"
    "| Class | (lattice, spacetime_sym, K_theory, edge_mode) | Hamming-to-HASPT |\n"
    "|:-----:|:---------------------------------------------|:----------------:|\n"
    "| A     | (1,1,1,1) | 4 |\n"
    "| AIII  | (1,1,1,1) | 4 |\n"
    "| AI    | (1,1,1,1) | 4 |\n"
    "| BDI   | (1,1,1,1) | 4 |\n"
    "| D     | (1,1,1,1) | 4 |\n"
    "| DIII  | (1,1,1,1) | 4 |\n"
    "| AII   | (1,1,1,1) | 4 |\n"
    "| CII   | (1,1,1,1) | 4 |\n"
    "| C     | (1,1,1,1) | 4 |\n"
    "| CI    | (1,1,1,1) | 4 |\n"
    "\n"
    "Minimum Hamming distance is 4 (maximal). HA-SPT is not adjacent to any AZ "
    "class. The gate's threshold of Hamming >= 2 is satisfied twice over; the "
    "distance is in fact maximal on this four-axis projection.\n"
    "\n"
    "**Invariant**\n"
    "\n"
    "The HA-SPT category is labelled by the pair\n"
    "\n"
    "- **I_(0,0)** = Kasparov pairing index = 0 (S61 KASPAROV-VERIFY-61, verified "
    "at 20 tau values; the KK-theory class of D_K with respect to the M^4 x SU(3) "
    "submersion factorisation); integer-valued in general,\n"
    "- **W_(0,0)** = Plancherel weight of the trivial sector = 1/sum_{p,q in "
    "L_max} dim(p,q)^2 = 1/805 at L_max=3; rational, L_max-dependent, approaches "
    "zero as L_max -> infinity.\n"
    "\n"
    "The pair (I, W) is the harmonic-analytic analog of the integer-valued Z or "
    "Z_2 invariants that label AZ classes. The qualitative difference: the "
    "SS-SPT invariants are classifying-space topological numbers of the bulk "
    "Hamiltonian bundle; the HA-SPT invariant has one topological component (I, "
    "from Kasparov KK-theory) and one representation-theoretic component (W, "
    "from Plancherel accounting) that together specify both the 'which sector' "
    "and the 'how much of the total' content of the protected object.\n"
    "\n"
    "**PASS criteria** (all five satisfied)\n"
    "\n"
    "| Criterion | Required | Actual | Status |\n"
    "|:----------|:--------:|:------:|:------:|\n"
    "| theorems_mapped_ge_5 | >= 5 | 11 | TRUE |\n"
    "| all_axioms_covered | 10/10 | 10/10 | TRUE |\n"
    "| dist_axioms_ge_3 | >= 3 distinguishing | 8 | TRUE |\n"
    "| hamming_ge_2 | min >= 2 | 4 | TRUE |\n"
    "| has_invariant | >= 1 invariant theorem | 2 | TRUE |\n"
    "\n"
    "**Gate verdict**\n"
    "\n"
    "`HARMONIC-SPT-CLASSIFICATION-74` : **PASS**\n"
    "Criteria passed: 5 / 5. Classification is complete (10 axioms, 11 theorems "
    "mapped, no uncovered axiom) and distinguishable from every Altland-Zirnbauer "
    "10-fold way class along 8 of 10 axioms with maximal Hamming distance 4 on "
    "the four-bit projection.\n"
    "\n"
    "**Substrate framing**\n"
    "\n"
    "The HA-SPT category is unavailable on a generic 8-manifold. It requires a "
    "homogeneous fibre with a Peter-Weyl decomposition. Paper 13's choice of "
    "K = SU(3) is simultaneously (a) the source of the SM gauge group through "
    "symmetry breaking and (b) the structural precondition for the substrate to "
    "occupy this new protection class. From the substrate perspective: the fibre "
    "IS the internal geometry, and the harmonic analysis of the right-regular "
    "action IS the spectral content of D_K. The protected 'sector' is not a "
    "region of space but a representation-theoretic summand of L^2(K,S). Space "
    "does not enter at any step of the classification. This is what makes the "
    "category genuinely non-solid-state: solid-state SPT phases are bulk "
    "Hamiltonians on a real-space lattice, and their protection invariably feeds "
    "through some spatial/charge/time symmetry. HA-SPT operates entirely on the "
    "harmonic structure of a spectral triple. The two categories are orthogonal "
    "rather than parent/child.\n"
    "\n"
    "**Assessment**\n"
    "\n"
    "The classification registers a new entry in the framework's structural "
    "taxonomy. In the Altland-Zirnbauer four-axis projection, HA-SPT lives at "
    "the all-zero corner while every AZ row lives at the all-ones corner; they "
    "are antipodal. The category is not a reformulation of BDI or DIII in "
    "different language; it is a genuinely different protection mechanism whose "
    "mathematical content is Peter-Weyl completeness, Schur's lemma, and "
    "Kasparov KK-theory rather than K-theory of Bloch bundles. The two features "
    "shared with solid-state SPT (CPT compatibility via the Connes real "
    "structure J, and deformation stability within the symmetry class) are "
    "exactly the features one expects to lift between any two symmetry-"
    "protection frameworks that use antiunitary operators and closed symmetry "
    "classes.\n"
    "\n"
    "Where the category sits in the project's architecture: HA-SPT is the "
    "algebraic ceiling for the 'structural floor' layer of the four-layer "
    "hierarchy (Topology / Representation / Metric / Functional, S72 canonical). "
    "Theorems T-BD-UNIV, T-JDK, T-JSQ, T-PW-INDEX sit in the Topology layer; "
    "they are L_max-independent and scheme-independent, and they are the same "
    "theorems that guarantee the structural predictions (w_0, w_a, c_s^2, mass "
    "ordering) are zero-parameter. HA-SPT is therefore not a decoration -- it is "
    "the symmetry-protection frame for the entire zero-parameter prediction "
    "class.\n"
    "\n"
    "Scope and caveats. The category is defined at the level of an "
    "axiomatisation + theorem mapping. It is NOT a statement that HA-SPT is "
    "'more fundamental' than solid-state SPT, nor a claim about the dynamics of "
    "the sector -- the BCS physics on the (0,0) sector is protected by HA-SPT, "
    "but the category is silent on what the sector DOES once protected. The "
    "Fermi-surface lock T-FS-LOCK is an example where HA-SPT protection (AX2, "
    "AX5, AX9) is a precondition for the B2[0] Kosmann-singlet value v^2=1/2, "
    "but the numerical value itself follows from particle-hole balance at xi=0, "
    "which is a dynamical rather than purely axiomatic statement. Treat HA-SPT "
    "as the container and the individual theorems as the contents.\n"
    "\n"
    "What is protected by HA-SPT (direct consequences): the permanent theorems "
    "in the structural floor that the framework has proven L_max-invariant; "
    "the block-diagonal decomposition of any R_g-invariant operator (not just "
    "D_K, so this extends to the Laplacian, the Casimir, any spectral "
    "functional f(D_K^2/Lambda^2), and any inner fluctuation of the form "
    "A + JAJ^{-1}); and the forbidden channels enumerated in the Plancherel/"
    "Schur-based closures (proton decay to tree level, three-phonon vertex "
    "suppression, Wilson loop triviality, etc.). What is NOT protected by "
    "HA-SPT (explicit scope limits): the Functional layer (f* shape, n_s "
    "absolute value at L_max=3), the Metric layer (sin^2 theta_W at M_KK, "
    "absolute values of a_k), and any observable that depends on the SIGN of a "
    "spectral derivative rather than its existence as a well-defined quantity. "
    "The category gives walls, not values.\n"
    "\n"
    "**Distinguishing HA-SPT from a reformulation of an existing class.** It is "
    "worth stating what would falsify the claim that HA-SPT is a genuinely new "
    "category. If a future paper established that the pair (I_(0,0), W_(0,0)) "
    "could be recovered as the K_d-classification of some auxiliary real-space "
    "Bloch bundle, HA-SPT would collapse into an exotic reformulation of some "
    "AZ class. This does not appear possible given AX1 (no lattice) and AX10 "
    "(Peter-Weyl unavailable on non-homogeneous fibres), but it is the "
    "conceptual line one would have to cross to retract the category. At the "
    "current state of the classification, no such reformulation is visible, and "
    "the minimum Hamming distance 4 on the four-axis projection confirms that "
    "HA-SPT does not sit adjacent to any AZ class.\n"
    "\n"
    "**Carry-forward**\n"
    "\n"
    "1. **HA-SPT-PAPER-75**: Write the full taxonomic paper 'Harmonic-Analytic "
    "Symmetry-Protected Phases on Spectral Triples' for JGP or CMP. The "
    "structure is set by the 10 axioms and 11 theorems mapped here. Reference "
    "Dukelsky-Pittel-Sierra RMP 2004 for the dilute Richardson-Gaudin limit, "
    "Gaiotto-Kapustin-Seiberg-Willett for the generalised global-symmetry "
    "framing of Schur superselection, and Paper 13/17 for the Jensen-SU(3) "
    "substrate. Target: post-S74, when the Wave 5 audit and HP4-PAIRING-74 "
    "have stabilised the Kasparov content.\n"
    "\n"
    "2. **HA-SPT-COSET-75**: Extend the classification from compact Lie groups "
    "K to homogeneous cosets G/H. The extension is straightforward in principle "
    "(Plancherel is available on G/H with a modified measure) but the "
    "invariant W_(0,0) gets a modification from the H-isotropy, and it is "
    "worth checking whether additional axioms are needed to cover the isotropy "
    "content. Scope: 1 session.\n"
    "\n"
    "3. **HA-SPT-DEFORMATION-75**: Characterise the full class of admissible "
    "deformations of D_K that preserve HA-SPT. The current statement in AX8 is "
    "that left-invariance + J is sufficient; a sharper statement would identify "
    "the minimal sub-algebra of the full algebra of deformations that preserves "
    "the category. This is the harmonic-analytic analog of the 'symmetry-"
    "preserving deformation space' for solid-state SPT phases.\n"
    "\n"
    "4. **HA-SPT-BDSPT-ANOMALY-75**: Check whether the Euclidean path integral "
    "over D_K configurations preserves the J-label structure at the non-"
    "perturbative level (S73B phonon-first-hawking workshop BDSPT-ANOMALY-74 "
    "item). If an anomaly is present, it affects AX6 and requires a "
    "modification of the CPT compatibility axiom. If no anomaly, the "
    "axiomatisation is clean at all orders.\n"
    "\n"
    "Items 1-4 are additions to the post-S74 carry-forward queue; none are S74 "
    "blockers.\n"
)


def main():
    with io.open(PATH, "r", encoding="utf-8") as f:
        content = f.read()

    if OLD not in content:
        print("ERROR: placeholder OLD block not found in file.", file=sys.stderr)
        sys.exit(1)

    if content.count(OLD) != 1:
        print(
            f"ERROR: placeholder OLD block appears {content.count(OLD)} times "
            "(expected 1).",
            file=sys.stderr,
        )
        sys.exit(1)

    new_content = content.replace(OLD, NEW, 1)

    # Atomic write via temp file + rename
    tmp_path = PATH + ".w4y.tmp"
    with io.open(tmp_path, "w", encoding="utf-8", newline="") as f:
        f.write(new_content)
    os.replace(tmp_path, PATH)

    print("OK: W4-Y section replaced.")
    print(f"  old length: {len(OLD)}")
    print(f"  new length: {len(NEW)}")
    print(f"  file length: {len(content)} -> {len(new_content)}")


if __name__ == "__main__":
    main()
