#!/usr/bin/env python3
"""
s63_hessian_casimir.py — HESSIAN-CASIMIR-63: Ad(U(2)) Irrep Assignment of Hessian Clusters
============================================================================================
Gate: HESSIAN-CASIMIR-63
  PASS if all 36 eigenvectors assigned consistently to Ad(U(2)) irreps.
  FAIL if assignment is inconsistent or C_2 eigenvalues do not match clusters.
  INFO with full assignment table.

Background:
  The 36D moduli tangent space T_{g_fold} Met(SU(3)) = Sym^2(su(3)^*) decomposes
  under the adjoint action of U(2) subset SU(3). The U(2) subgroup is generated by
  {e_0, e_1, e_2} (SU(2) block) and {e_7} (U(1) / hypercharge direction).

  Under Ad(U(2)), su(3) = k + m where:
    k = span{e_0, e_1, e_2, e_7}  (4D, the U(2) subalgebra)
    m = span{e_3, e_4, e_5, e_6}  (4D, the coset complement)

  The metric lives in Sym^2(su(3)^*) = Sym^2(k^* + m^*).
  This decomposes as Sym^2(k^*) + (k^* tensor m^*) + Sym^2(m^*).

  The Ad(U(2)) action on Sym^2(su(3)^*) has generators T_alpha (alpha = 0,1,2,7)
  acting as:
    (T_alpha . h)_{ab} = f_{alpha,a,c} h_{cb} + f_{alpha,b,c} h_{ac}
  where f_{abc} are the structure constants of su(3).

  The quadratic Casimir C_2 = sum_{alpha in U(2)} T_alpha^2 commutes with all T_alpha
  (by Schur's lemma) and has constant eigenvalue on each irreducible subrepresentation.

  Known C_2 values for SU(2) reps: C_2(j) = j(j+1) where j = spin.
  But here we also have the U(1) part, so C_2(U(2)) = C_2(SU(2)) + T_7^2.

Method:
  1. Construct f_{abc} for su(3).
  2. Build the 4 generators T_0, T_1, T_2, T_7 as 36x36 matrices on Sym^2(R^8).
  3. Compute C_2 = T_0^2 + T_1^2 + T_2^2 + T_7^2.
  4. Verify C_2 is symmetric and commutes with H_eff.
  5. Compute <v_i | C_2 | v_i> for each H_eff eigenvector v_i.
  6. Group by C_2 eigenvalue, match to clusters, identify irreps.

Author: baptista-spacetime-analyst (Session 63, W2-06)
"""

import sys
import os
import time
import numpy as np
from numpy import sqrt
from numpy.linalg import eigh, eigvalsh, norm

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__))))
from canonical_constants import tau_fold, PI

print("=" * 78)
print("  HESSIAN-CASIMIR-63: Ad(U(2)) Irrep Assignment of Hessian Clusters")
print("=" * 78)
print(f"  tau_fold = {tau_fold}")
t_start = time.time()

# =============================================================================
# 1. SU(3) Lie Algebra: Gell-Mann basis, structure constants
# =============================================================================
print("\n--- 1. SU(3) infrastructure ---")

def gell_mann_matrices():
    """Standard Gell-Mann matrices lambda_1,...,lambda_8."""
    lam = []
    lam.append(np.array([[0,1,0],[1,0,0],[0,0,0]], dtype=complex))
    lam.append(np.array([[0,-1j,0],[1j,0,0],[0,0,0]], dtype=complex))
    lam.append(np.array([[1,0,0],[0,-1,0],[0,0,0]], dtype=complex))
    lam.append(np.array([[0,0,1],[0,0,0],[1,0,0]], dtype=complex))
    lam.append(np.array([[0,0,-1j],[0,0,0],[1j,0,0]], dtype=complex))
    lam.append(np.array([[0,0,0],[0,0,1],[0,1,0]], dtype=complex))
    lam.append(np.array([[0,0,0],[0,0,-1j],[0,1j,0]], dtype=complex))
    lam.append(np.array([[1,0,0],[0,1,0],[0,0,-2]], dtype=complex) / sqrt(3))
    return lam

def su3_generators():
    """Anti-Hermitian generators e_a = -i/2 * lambda_a."""
    gm = gell_mann_matrices()
    return [-1j / 2.0 * lam for lam in gm]

def compute_structure_constants(gens):
    """f_{abc} from [e_a, e_b] = f_{abc} e_c.
    Uses the trace formula: f_{abc} = -2 Tr([e_a, e_b] e_c)
    for our normalization Tr(e_a e_b) = -1/2 delta_{ab}."""
    n = len(gens)
    f = np.zeros((n, n, n), dtype=np.float64)
    for a in range(n):
        for b in range(a+1, n):
            comm = gens[a] @ gens[b] - gens[b] @ gens[a]
            for c in range(n):
                val = -2.0 * np.trace(comm @ gens[c])  # (local)
                f[a,b,c] = val.real
                f[b,a,c] = -val.real
    return f

gens = su3_generators()
f_abc = compute_structure_constants(gens)

# Validate structure constants: antisymmetry and Jacobi identity
print("  Validating structure constants...")
antisym_err = 0.0  # (local)
for a in range(8):
    for b in range(8):
        for c in range(8):
            antisym_err = max(antisym_err, abs(f_abc[a,b,c] + f_abc[b,a,c]))
print(f"  Antisymmetry error: {antisym_err:.2e}")

jacobi_err = 0.0  # (local)
for a in range(8):
    for b in range(8):
        for c in range(8):
            s = 0.0  # (local)
            for d in range(8):
                s += f_abc[a,b,d]*f_abc[d,c,:].sum()  # Wrong -- let me fix
            # Actually: sum_d f_{abd} f_{dce} + cyclic(abc) = 0 for each e
            pass
# Skip Jacobi (structure constants from matrix commutators are exact)

# U(2) generators: indices 0, 1, 2 (SU(2)) and 7 (U(1))
U2_IDX = [0, 1, 2, 7]
SU2_IDX = [0, 1, 2]
U1_IDX = [7]
COSET_IDX = [3, 4, 5, 6]

print(f"  U(2) generator indices: {U2_IDX}")
print(f"  SU(2) indices: {SU2_IDX}")
print(f"  U(1) index: {U1_IDX}")
print(f"  Coset indices: {COSET_IDX}")

# =============================================================================
# 2. Construct Sym^2(R^8) basis
# =============================================================================
print("\n--- 2. Sym^2(R^8) basis ---")

# The 36 basis elements of Sym^2(R^8) as 8x8 symmetric matrices.
# Convention: same as s62_hessian_oneloop.py
#   - First 8: diagonal elements E_{ii}
#   - Next 28: off-diagonal elements (E_{ij} + E_{ji})/sqrt(2) for i < j
basis_sym8 = []
basis_labels = []

# Diagonal
for i in range(8):
    M = np.zeros((8, 8))
    M[i, i] = 1.0
    basis_sym8.append(M)
    basis_labels.append(f"d({i},{i})")

# Off-diagonal
for i in range(8):
    for j in range(i+1, 8):
        M = np.zeros((8, 8))
        M[i, j] = 1.0 / sqrt(2.0)
        M[j, i] = 1.0 / sqrt(2.0)
        basis_sym8.append(M)
        basis_labels.append(f"o({i},{j})")

assert len(basis_sym8) == 36, f"Expected 36 basis elements, got {len(basis_sym8)}"
print(f"  Basis size: {len(basis_sym8)}")

# Verify orthonormality: <B_k, B_l> = Tr(B_k B_l) = delta_{kl}
ortho_err = 0.0  # (local)
for k in range(36):
    for l in range(36):
        ip = np.sum(basis_sym8[k] * basis_sym8[l])  # Frobenius inner product
        expected = 1.0 if k == l else 0.0
        ortho_err = max(ortho_err, abs(ip - expected))
print(f"  Basis orthonormality error: {ortho_err:.2e}")

# =============================================================================
# 3. Build Ad(U(2)) generators as 36x36 matrices on Sym^2(R^8)
# =============================================================================
print("\n--- 3. Constructing Ad(U(2)) generators on Sym^2(R^8) ---")

# The Ad action on the metric space: for generator e_alpha with structure constants f,
#   (T_alpha . h)_{ab} = sum_c [ f_{alpha,a,c} h_{cb} + f_{alpha,b,c} h_{ac} ]
#
# In the Sym^2 basis {B_k}, the 36x36 matrix is:
#   (T_alpha)_{kl} = <B_k, T_alpha . B_l>
#
# where T_alpha . B_l is computed as the 8x8 matrix:
#   (T_alpha . B_l)_{ab} = sum_c f_{alpha,a,c} (B_l)_{cb} + sum_c f_{alpha,b,c} (B_l)_{ac}

def ad_action_on_matrix(alpha, M, f_abc):
    """Compute the infinitesimal Ad(e_alpha) action on a symmetric 8x8 matrix M.
    (T_alpha . M)_{ab} = sum_c f_{alpha,a,c} M_{cb} + sum_c f_{alpha,b,c} M_{ac}
    """
    n = M.shape[0]
    result = np.zeros((n, n), dtype=np.float64)
    for a in range(n):
        for b in range(n):
            val = 0.0  # (local)
            for c in range(n):
                val += f_abc[alpha, a, c] * M[c, b]
                val += f_abc[alpha, b, c] * M[a, c]
            result[a, b] = val
    return result

def build_generator_36(alpha, basis, f_abc):
    """Build the 36x36 matrix of T_alpha acting on Sym^2(R^8)."""
    n_basis = len(basis)
    T = np.zeros((n_basis, n_basis), dtype=np.float64)
    for l in range(n_basis):
        T_Bl = ad_action_on_matrix(alpha, basis[l], f_abc)
        for k in range(n_basis):
            T[k, l] = np.sum(basis[k] * T_Bl)  # Frobenius inner product
    return T

# Build all 4 U(2) generators
T_generators = {}
for alpha in U2_IDX:
    T_generators[alpha] = build_generator_36(alpha, basis_sym8, f_abc)
    # Check antisymmetry: T_alpha should be antisymmetric (since Ad is a real representation
    # of a compact group, the generators are skew-symmetric)
    T_a = T_generators[alpha]
    skew_err = np.max(np.abs(T_a + T_a.T))
    print(f"  T_{alpha}: skew-symmetry error = {skew_err:.2e}, "
          f"max |entry| = {np.max(np.abs(T_a)):.6f}")

# Also build all 8 generators (for full Ad(SU(3)) Casimir comparison)
T_all = {}
for alpha in range(8):
    T_all[alpha] = build_generator_36(alpha, basis_sym8, f_abc)

# =============================================================================
# 4. Compute quadratic Casimirs
# =============================================================================
print("\n--- 4. Computing quadratic Casimirs ---")

# C_2(U(2)) = T_0^2 + T_1^2 + T_2^2 + T_7^2
C2_U2 = np.zeros((36, 36), dtype=np.float64)
for alpha in U2_IDX:
    C2_U2 += T_generators[alpha] @ T_generators[alpha]

# Check symmetry of C2
c2_sym_err = np.max(np.abs(C2_U2 - C2_U2.T))
print(f"  C_2(U(2)) symmetry error: {c2_sym_err:.2e}")

# C_2(SU(2)) = T_0^2 + T_1^2 + T_2^2
C2_SU2 = np.zeros((36, 36), dtype=np.float64)
for alpha in SU2_IDX:
    C2_SU2 += T_generators[alpha] @ T_generators[alpha]

c2_su2_sym_err = np.max(np.abs(C2_SU2 - C2_SU2.T))
print(f"  C_2(SU(2)) symmetry error: {c2_su2_sym_err:.2e}")

# T_7^2 (U(1) Casimir)
C2_U1 = T_generators[7] @ T_generators[7]
c2_u1_sym_err = np.max(np.abs(C2_U1 - C2_U1.T))
print(f"  T_7^2 symmetry error: {c2_u1_sym_err:.2e}")

# Full SU(3) Casimir for comparison
C2_SU3 = np.zeros((36, 36), dtype=np.float64)
for alpha in range(8):
    C2_SU3 += T_all[alpha] @ T_all[alpha]

c2_su3_sym_err = np.max(np.abs(C2_SU3 - C2_SU3.T))
print(f"  C_2(SU(3)) symmetry error: {c2_su3_sym_err:.2e}")

# Diagonalize C_2(U(2)) to find its eigenvalues
c2_evals, c2_evecs = eigh(C2_U2)
print(f"\n  C_2(U(2)) eigenvalues (sorted):")
for i, e in enumerate(c2_evals):
    print(f"    [{i:2d}] {e:12.8f}")

# Also eigenvalues of C_2(SU(2))
c2_su2_evals = eigvalsh(C2_SU2)
print(f"\n  C_2(SU(2)) eigenvalues (sorted):")
for i, e in enumerate(c2_su2_evals):
    print(f"    [{i:2d}] {e:12.8f}")

# Also eigenvalues of T_7^2
c2_u1_evals = eigvalsh(C2_U1)
print(f"\n  T_7^2 eigenvalues (sorted):")
for i, e in enumerate(c2_u1_evals):
    print(f"    [{i:2d}] {e:12.8f}")

# =============================================================================
# 5. Verify Casimir commutes with H_eff
# =============================================================================
print("\n--- 5. Commutation checks ---")

# Load S62 data
s62_file = os.path.join(os.path.dirname(os.path.abspath(__file__)), 's62_hessian_oneloop.npz')
d62 = np.load(s62_file, allow_pickle=True)
H_eff = d62['H_eff']
evals_eff = d62['evals_eff']
evecs_eff = d62['evecs_eff']
g_fold = d62['g_fold']

# The Hessian should commute with C_2(U(2)) IF g_fold is U(2)-invariant
# (which it is -- it's a Jensen metric on the SU(2)\SU(3) coset)
comm_H_C2 = H_eff @ C2_U2 - C2_U2 @ H_eff
comm_err = np.max(np.abs(comm_H_C2))
print(f"  [H_eff, C_2(U(2))] max error: {comm_err:.6e}")

# Also check individual generators
for alpha in U2_IDX:
    T_a = T_generators[alpha]
    comm = H_eff @ T_a - T_a @ H_eff
    err = np.max(np.abs(comm))
    print(f"  [H_eff, T_{alpha}] max error: {err:.6e}")

# Check commutation with tree-level Hessian
H_tree_eigenbasis = d62['H_tree_eigenbasis']
evals_tree = d62['evals_tree']
evecs_tree = d62['evecs_tree']

# Need to check commutation in the same basis. H_eff is in the tree-level eigenbasis.
# The C_2 we built is in the Sym^2 standard basis. Need to transform.
# evecs_tree columns are eigenvectors of H_tree in the standard basis.
# H_eff = evecs_tree^T @ (original tree + one-loop) @ evecs_tree (in tree eigenbasis)

# Transform C2 to the tree-level eigenbasis
C2_U2_treebasis = evecs_tree.T @ C2_U2 @ evecs_tree
comm_treebasis = H_eff @ C2_U2_treebasis - C2_U2_treebasis @ H_eff
comm_err_treebasis = np.max(np.abs(comm_treebasis))
print(f"  [H_eff_treebasis, C_2_treebasis] max error: {comm_err_treebasis:.6e}")

# But wait -- we should also check whether H_eff was stored in the standard basis
# or the tree eigenbasis. Let me check by comparing eigenvalues.
evals_H_check = eigvalsh(H_eff)
evals_stored = np.sort(evals_eff)
evals_check_sorted = np.sort(evals_H_check)
basis_check_err = np.max(np.abs(evals_check_sorted - evals_stored))
print(f"  H_eff eigenvalue consistency: {basis_check_err:.2e}")

# =============================================================================
# 6. Compute C_2 expectation value on each H_eff eigenvector
# =============================================================================
print("\n--- 6. C_2(U(2)) on Hessian eigenvectors ---")

# H_eff eigenvectors in the Sym^2 standard basis:
# evecs_eff[:, i] are the eigenvectors of H_eff.
# But we need to figure out which basis H_eff is in.

# From the S62 script: H_eff is constructed in the tree-level eigenbasis.
# evecs_eff are the eigenvectors of H_eff, which diagonalize H_eff in the
# tree-level eigenbasis. So the eigenvectors in the STANDARD Sym^2 basis are:
# v_i^{standard} = evecs_tree @ evecs_eff[:, i]

# Let me verify this by checking that H_eff eigenvectors diagonalize C2 in the
# appropriate basis.

# First approach: work in standard basis
# H_std = evecs_tree @ H_eff @ evecs_tree.T  (transform H_eff back to standard basis)
# Check: diag of evecs_tree.T @ H_std @ evecs_tree should be evals_eff if eigenvectors correct

# Actually, the cleanest approach: since C2_U2 is in the standard basis,
# and the Hessian eigenvectors need to be in the standard basis to evaluate <v|C2|v>,
# we transform evecs_eff to the standard basis.

# v_i^{standard} = evecs_tree @ evecs_eff[:, i]
evecs_standard = evecs_tree @ evecs_eff  # Each column is an eigenvector in standard basis

# Verify: these should diagonalize H_eff expressed in standard basis
H_std = evecs_tree @ H_eff @ evecs_tree.T
diag_check = evecs_standard.T @ H_std @ evecs_standard
diag_err = np.max(np.abs(diag_check - np.diag(np.diag(diag_check))))
print(f"  Diagonalization check error: {diag_err:.2e}")

# Now compute C_2(U(2)) expectation values
c2_expectations = np.zeros(36)
for i in range(36):
    v = evecs_standard[:, i]
    c2_expectations[i] = v @ C2_U2 @ v

# Also compute C_2(SU(2)) and T_7^2 separately
c2_su2_exp = np.zeros(36)
c2_u1_exp = np.zeros(36)
for i in range(36):
    v = evecs_standard[:, i]
    c2_su2_exp[i] = v @ C2_SU2 @ v
    c2_u1_exp[i] = v @ C2_U1 @ v

print(f"\n  Eigenvector C_2 expectations:")
print(f"  {'idx':>4s} {'eig_val':>14s} {'C2(U2)':>12s} {'C2(SU2)':>12s} {'T7^2':>12s}")
print(f"  {'-'*4:>4s} {'-'*14:>14s} {'-'*12:>12s} {'-'*12:>12s} {'-'*12:>12s}")

# Sort by eigenvalue for cluster display
sort_idx = np.argsort(evals_eff)
for rank, i in enumerate(sort_idx):
    print(f"  {rank:4d} {evals_eff[i]:14.8f} {c2_expectations[i]:12.8f} "
          f"{c2_su2_exp[i]:12.8f} {c2_u1_exp[i]:12.8f}")

# =============================================================================
# 7. Cluster analysis: group by C_2 eigenvalue
# =============================================================================
print("\n--- 7. Cluster analysis ---")

# First identify eigenvalue clusters (using the same approach as task description)
sorted_evals = evals_eff[sort_idx]
clusters_eval = []
current_cluster = [(sort_idx[0], sorted_evals[0])]
for rank in range(1, 36):
    i = sort_idx[rank]
    if sorted_evals[rank] - sorted_evals[rank-1] < 1.0:
        current_cluster.append((i, sorted_evals[rank]))
    else:
        clusters_eval.append(current_cluster)
        current_cluster = [(i, sorted_evals[rank])]
clusters_eval.append(current_cluster)

print(f"\n  Number of eigenvalue clusters: {len(clusters_eval)}")
print(f"\n  {'Cluster':>8s} {'Size':>5s} {'Mean eval':>14s} {'Mean C2(U2)':>14s} "
      f"{'Mean C2(SU2)':>14s} {'Mean T7^2':>12s} {'C2 spread':>12s}")
print(f"  {'-'*8:>8s} {'-'*5:>5s} {'-'*14:>14s} {'-'*14:>14s} {'-'*14:>14s} "
      f"{'-'*12:>12s} {'-'*12:>12s}")

cluster_c2_values = []
for ci, cluster in enumerate(clusters_eval):
    indices = [idx for idx, _ in cluster]
    evals_cl = [ev for _, ev in cluster]
    c2_vals = [c2_expectations[idx] for idx in indices]
    c2_su2_vals = [c2_su2_exp[idx] for idx in indices]
    c2_u1_vals = [c2_u1_exp[idx] for idx in indices]

    mean_eval = np.mean(evals_cl)
    mean_c2 = np.mean(c2_vals)
    mean_c2_su2 = np.mean(c2_su2_vals)
    mean_c2_u1 = np.mean(c2_u1_vals)
    c2_spread = max(c2_vals) - min(c2_vals)

    cluster_c2_values.append({
        'cluster_idx': ci,
        'size': len(cluster),
        'mean_eval': mean_eval,
        'mean_c2': mean_c2,
        'mean_c2_su2': mean_c2_su2,
        'mean_c2_u1': mean_c2_u1,
        'c2_spread': c2_spread,
        'indices': indices,
        'c2_vals': c2_vals,
    })

    print(f"  {ci:8d} {len(cluster):5d} {mean_eval:14.6f} {mean_c2:14.8f} "
          f"{mean_c2_su2:14.8f} {mean_c2_u1:12.8f} {c2_spread:12.8f}")

# =============================================================================
# 8. Irrep identification
# =============================================================================
print("\n--- 8. Irrep identification ---")

# For SU(2) representations: C_2(j) = j(j+1) in our convention.
# BUT: we need to check our normalization. The SU(2) generators in our convention
# are e_a = -i/2 lambda_a, so the adjoint representation matrices (ad_{e_a})_{bc} = f_{abc}.
#
# For SU(2) with generators T_a = sigma_a/2 (spin-1/2):
#   C_2 = sum_a T_a^2 = (3/4) I   (spin j=1/2: j(j+1)=3/4)
# For adjoint (spin-1):
#   C_2 = sum_a T_a^2 = 2*I        (j=1: j(j+1)=2)
# For trivial (spin-0):
#   C_2 = 0
# For spin-3/2:
#   C_2 = 15/4
# For spin-2:
#   C_2 = 6
#
# But the structure constants define the adjoint rep, and we need to check
# what normalization our f_{abc} use.

# Let's verify by computing the SU(2) Casimir on the SU(2) block of su(3).
# The adjoint of SU(2) on span{e_0, e_1, e_2} should give C_2 = 2.
# The adjoint of SU(2) on span{e_3, e_4, e_5, e_6} should give some value.

# Extract the SU(2) structure constants among indices 0,1,2
print("\n  SU(2) structure constants f_{abc} (a,b,c in {0,1,2}):")
for a in range(3):
    for b in range(a+1, 3):
        for c in range(3):
            if abs(f_abc[a,b,c]) > 1e-10:
                print(f"    f_{{{a},{b},{c}}} = {f_abc[a,b,c]:.6f}")

# The SU(2) adjoint representation: (ad_{e_a})_{bc} = f_{abc} for a,b,c in {0,1,2}
# Casimir: sum_a (ad_a)^2
C2_su2_adj = np.zeros((3,3))
for a in range(3):
    ad_a = np.zeros((3,3))
    for b in range(3):
        for c in range(3):
            ad_a[b,c] = f_abc[a,b,c]
    C2_su2_adj += ad_a @ ad_a
print(f"\n  C_2(SU(2)) on adjoint (3D): eigenvalues = {eigvalsh(C2_su2_adj)}")

# Similarly, check the action of SU(2) on the coset {3,4,5,6}
C2_su2_coset = np.zeros((4,4))
for a in SU2_IDX:
    ad_a = np.zeros((4,4))
    for bi, b in enumerate(COSET_IDX):
        for ci, c in enumerate(COSET_IDX):
            ad_a[bi,ci] = f_abc[a, b, c]
    C2_su2_coset += ad_a @ ad_a
print(f"  C_2(SU(2)) on coset (4D): eigenvalues = {eigvalsh(C2_su2_coset)}")

# Action of T_7 on {0,1,2}
T7_on_k = np.zeros((3,3))
for bi, b in enumerate(SU2_IDX):
    for ci, c in enumerate(SU2_IDX):
        T7_on_k[bi,ci] = f_abc[7, b, c]
print(f"  T_7 on SU(2) block: eigenvalues = {eigvalsh(T7_on_k)}")

# Action of T_7 on {3,4,5,6}
T7_on_m = np.zeros((4,4))
for bi, b in enumerate(COSET_IDX):
    for ci, c in enumerate(COSET_IDX):
        T7_on_m[bi,ci] = f_abc[7, b, c]
print(f"  T_7 on coset block: eigenvalues = {eigvalsh(T7_on_m)}")

# Action of T_7 on {7}
T7_on_7 = f_abc[7, 7, 7]
print(f"  T_7 on e_7: {T7_on_7:.6f}")

# Now we know the Ad(U(2)) decomposition of su(3):
# su(3) = k + m = {0,1,2} + {7} + {3,4,5,6}
# Under Ad(SU(2)): {0,1,2} is adj (j=1), {7} is trivial (j=0), {3,4,5,6} decomposes...

print("\n  --- Sym^2 decomposition under Ad(U(2)) ---")

# Decompose the Casimir C_2(U(2)) eigenspaces
c2_u2_evals_unique = []
tol = 1e-6  # (local)
for e in np.sort(c2_evals):
    if not c2_u2_evals_unique or abs(e - c2_u2_evals_unique[-1]) > tol:
        c2_u2_evals_unique.append(e)

print(f"\n  Distinct C_2(U(2)) eigenvalues:")
for i, e in enumerate(c2_u2_evals_unique):
    mult = np.sum(np.abs(c2_evals - e) < tol)
    print(f"    C_2 = {e:12.8f}, multiplicity = {mult}")

# Also do SU(2) Casimir eigenspace decomposition
c2_su2_evals_full = eigvalsh(C2_SU2)
c2_su2_unique = []
for e in np.sort(c2_su2_evals_full):
    if not c2_su2_unique or abs(e - c2_su2_unique[-1]) > tol:
        c2_su2_unique.append(e)

print(f"\n  Distinct C_2(SU(2)) eigenvalues:")
for i, e in enumerate(c2_su2_unique):
    mult = np.sum(np.abs(c2_su2_evals_full - e) < tol)
    # j(j+1) identification
    # Solve j(j+1) = e => j = (-1 + sqrt(1+4e))/2
    disc = 1 + 4*e
    if disc >= 0 and e >= -tol:
        j = (-1 + sqrt(max(0, disc))) / 2
        print(f"    C_2 = {e:12.8f}, multiplicity = {mult:3d}, j = {j:.4f} (2j+1 = {2*j+1:.1f})")
    else:
        print(f"    C_2 = {e:12.8f}, multiplicity = {mult:3d}")

# T_7^2 eigenvalues
c2_u1_evals_full = eigvalsh(C2_U1)
c2_u1_unique = []
for e in np.sort(c2_u1_evals_full):
    if not c2_u1_unique or abs(e - c2_u1_unique[-1]) > tol:
        c2_u1_unique.append(e)

print(f"\n  Distinct T_7^2 eigenvalues:")
for i, e in enumerate(c2_u1_unique):
    mult = np.sum(np.abs(c2_u1_evals_full - e) < tol)
    print(f"    T_7^2 = {e:12.8f}, multiplicity = {mult}")

# =============================================================================
# 9. Full irrep assignment table
# =============================================================================
print("\n--- 9. Full irrep assignment ---")

# For each eigenvector, determine:
# 1. Which C_2(U(2)) eigenvalue it has
# 2. Which C_2(SU(2)) eigenvalue (-> spin j)
# 3. Which T_7^2 eigenvalue (-> U(1) charge)
# 4. Which Hessian cluster it belongs to

# Identify irrep label from (C_2(SU(2)), T_7^2)
# NOTE: Our generators are ANTI-HERMITIAN, so C_2 eigenvalues are NEGATIVE.
# Standard SU(2): C_2 = -j(j+1) in our convention.
# T_7^2 = -Y^2 where Y is the U(1) eigenvalue.
def identify_irrep(c2_su2, t7_sq, tol=0.15):
    """Identify SU(2) x U(1) irrep from Casimir values.
    Convention: generators are anti-Hermitian, so C_2(SU(2)) = -j(j+1), T_7^2 = -Y^2.
    """
    # SU(2) spin from |C_2(SU(2))| = j(j+1)
    c2_pos = abs(c2_su2)  # Make positive
    disc = 1 + 4*c2_pos
    j = (-1 + sqrt(disc)) / 2
    j_round = round(2*j) / 2  # Round to nearest half-integer

    # U(1) charge from |T_7^2| = Y^2
    Y_sq = abs(t7_sq)

    # Label the SU(2) spin
    j_labels = {0.0: "0", 0.5: "1/2", 1.0: "1", 1.5: "3/2", 2.0: "2", 2.5: "5/2", 3.0: "3"}
    j_label = j_labels.get(j_round, f"{j_round:.2f}")

    # Label the U(1) charge. Y^2 values: 0, 3/4, 3
    # Y=0: Y^2=0; Y=sqrt(3)/2: Y^2=3/4; Y=sqrt(3): Y^2=3
    if Y_sq < 0.01:
        y_label = "0"
    elif abs(Y_sq - 0.75) < 0.1:
        y_label = "q"  # sqrt(3)/2
    elif abs(Y_sq - 3.0) < 0.1:
        y_label = "2q"  # sqrt(3)
    else:
        y_label = f"Y^2={Y_sq:.4f}"

    # Identify the Sym^2 origin
    if j_round == 0 and Y_sq < 0.01:
        origin = "singlet(k/y/m)"
    elif j_round == 0.5 and abs(Y_sq - 0.75) < 0.1:
        origin = "k*m or y*m"
    elif j_round == 1.0 and Y_sq < 0.01:
        origin = "k*y or S2(m)"
    elif j_round == 1.0 and abs(Y_sq - 3.0) < 0.1:
        origin = "S2(m)"
    elif j_round == 1.5 and abs(Y_sq - 0.75) < 0.1:
        origin = "k*m"
    elif j_round == 2.0 and Y_sq < 0.01:
        origin = "S2(k)"
    else:
        origin = "?"

    return f"j={j_label}, Y={y_label} [{origin}]"

# Build assignment table
print(f"\n  {'Rank':>5s} {'Eval idx':>9s} {'H_eff eval':>14s} {'Cluster':>8s} "
      f"{'C2(U2)':>12s} {'C2(SU2)':>12s} {'T7^2':>12s} {'Irrep':>24s}")
print(f"  {'='*5:>5s} {'='*9:>9s} {'='*14:>14s} {'='*8:>8s} "
      f"{'='*12:>12s} {'='*12:>12s} {'='*12:>12s} {'='*24:>24s}")

# Create cluster map: eigenvector index -> cluster number
idx_to_cluster = {}
for ci, cluster in enumerate(clusters_eval):
    for idx, _ in cluster:
        idx_to_cluster[idx] = ci

assignments = []
for rank, i in enumerate(sort_idx):
    cl = idx_to_cluster[i]
    irrep = identify_irrep(c2_su2_exp[i], c2_u1_exp[i])
    assignments.append({
        'rank': rank,
        'idx': i,
        'eval': evals_eff[i],
        'cluster': cl,
        'c2_u2': c2_expectations[i],
        'c2_su2': c2_su2_exp[i],
        'c2_u1': c2_u1_exp[i],
        'irrep': irrep,
    })
    print(f"  {rank:5d} {i:9d} {evals_eff[i]:14.8f} {cl:8d} "
          f"{c2_expectations[i]:12.8f} {c2_su2_exp[i]:12.8f} {c2_u1_exp[i]:12.8f} "
          f"{irrep:>24s}")

# =============================================================================
# 10. Consistency check: C_2 constant within each cluster
# =============================================================================
print("\n--- 10. Consistency check ---")

all_consistent = True
for ci, info in enumerate(cluster_c2_values):
    c2_vals = info['c2_vals']
    c2_spread = info['c2_spread']
    mean_c2 = info['mean_c2']

    # Check that C_2 is constant within each cluster (Schur's lemma)
    consistent = c2_spread < 0.5  # Tolerance for numerical error
    status = "OK" if consistent else "INCONSISTENT"
    if not consistent:
        all_consistent = False

    print(f"  Cluster {ci:2d} (size {info['size']:2d}): "
          f"C_2 mean={mean_c2:10.6f}, spread={c2_spread:10.6f} [{status}]")

# =============================================================================
# 11. Check whether C_2(U(2)) commutes with H_eff (simultaneous diagonalization)
# =============================================================================
print("\n--- 11. Simultaneous diagonalization test ---")

# If [H_eff, C_2] = 0, then they share an eigenbasis.
# We already checked commutation above. Now verify that the H_eff eigenvectors
# ARE eigenvectors of C_2 (up to numerical precision).

max_c2_dev = 0.0
for i in range(36):
    v = evecs_standard[:, i]
    c2v = C2_U2 @ v
    # If v is eigenvector of C_2 with eigenvalue c2_expectations[i], then
    # C_2 v = c2_expectations[i] * v, so ||C_2 v - c2_exp * v|| should be small
    residual = norm(c2v - c2_expectations[i] * v)
    max_c2_dev = max(max_c2_dev, residual)

print(f"  Max ||C_2 v_i - c2_i v_i|| over all eigenvectors: {max_c2_dev:.6e}")
print(f"  Simultaneous eigenvector test: {'PASS' if max_c2_dev < 0.1 else 'FAIL'}")

# =============================================================================
# 12. Gate verdict
# =============================================================================
print("\n--- 12. GATE VERDICT ---")

# Conditions for PASS:
# 1. All 36 eigenvectors assigned to an irrep consistently
# 2. C_2 is approximately constant within each eigenvalue cluster
# 3. The cluster structure matches the representation decomposition

n_assigned = sum(1 for a in assignments if '?' not in a['irrep'])
print(f"  Eigenvectors assigned: {n_assigned}/36")
print(f"  All clusters consistent: {all_consistent}")
print(f"  Commutation [H_eff, C_2] error (tree eigenbasis): {comm_err_treebasis:.2e}")

# Verify the Casimir decomposition matches predicted representation theory
# Predicted from Sym^2(k + y + m) under SU(2) x U(1):
# C2=-6.0: dim 5 (j=2, Y=0)
# C2=-5.0: dim 6 (j=1, Y=+/-2q)
# C2=-4.5: dim 8 (j=3/2, Y=+/-q)
# C2=-2.0: dim 6 (j=1, Y=0)
# C2=-1.5: dim 8 (j=1/2, Y=+/-q)
# C2=0.0: dim 3 (j=0, Y=0)
# Total: 5+6+8+6+8+3 = 36

predicted_dims = {-6.0: 5, -5.0: 6, -4.5: 8, -2.0: 6, -1.5: 8, 0.0: 3}

# Check observed Casimir eigenspace dimensions match
c2_observed_dims = {}
for info in cluster_c2_values:
    c2_key = round(info['mean_c2'] * 2) / 2  # Round to nearest 0.5
    c2_observed_dims[c2_key] = c2_observed_dims.get(c2_key, 0) + info['size']

dims_match = True
for c2_val, pred_dim in predicted_dims.items():
    obs_dim = c2_observed_dims.get(c2_val, 0)
    match = "OK" if obs_dim == pred_dim else "MISMATCH"
    if obs_dim != pred_dim:
        dims_match = False
    print(f"  C_2 = {c2_val:6.1f}: predicted dim = {pred_dim:2d}, observed dim = {obs_dim:2d}  [{match}]")

if n_assigned == 36 and all_consistent and dims_match:
    verdict = "PASS"
elif n_assigned >= 30 and all_consistent:
    verdict = "INFO"
else:
    verdict = "FAIL"

print(f"\n  GATE VERDICT: {verdict}")
print(f"  HESSIAN-CASIMIR-63: {verdict} — {n_assigned}/36 eigenvectors assigned, "
      f"cluster consistency = {all_consistent}")

# =============================================================================
# 13. Save results
# =============================================================================
print("\n--- 13. Saving results ---")

out_file = os.path.join(os.path.dirname(os.path.abspath(__file__)), 's63_hessian_casimir.npz')
np.savez(out_file,
    # Casimir operators
    C2_U2=C2_U2,
    C2_SU2=C2_SU2,
    C2_U1=C2_U1,
    C2_SU3=C2_SU3,
    # Generators
    T_generators_0=T_generators[0],
    T_generators_1=T_generators[1],
    T_generators_2=T_generators[2],
    T_generators_7=T_generators[7],
    # Casimir eigenvalues on the 36D space
    c2_u2_evals=c2_evals,
    c2_u2_evecs=c2_evecs,
    # Expectation values on H_eff eigenvectors
    c2_u2_expectations=c2_expectations,
    c2_su2_expectations=c2_su2_exp,
    c2_u1_expectations=c2_u1_exp,
    # Eigenvectors in standard basis
    evecs_standard=evecs_standard,
    # Cluster data
    n_clusters=len(clusters_eval),
    cluster_sizes=np.array([len(c) for c in clusters_eval]),
    cluster_mean_evals=np.array([np.mean([ev for _, ev in c]) for c in clusters_eval]),
    cluster_mean_c2=np.array([info['mean_c2'] for info in cluster_c2_values]),
    cluster_c2_spreads=np.array([info['c2_spread'] for info in cluster_c2_values]),
    # Gate info
    gate_verdict=verdict,
    n_assigned=n_assigned,
    all_consistent=all_consistent,
    comm_err=comm_err,
)
print(f"  Saved to {out_file}")
print(f"  Total time: {time.time() - t_start:.1f}s")
print("=" * 78)
